Add scopeNote to uniqueText
semanticarts/gist pull request #1005
Opened 2023-11-08 21:19 UTC by uscholdm

Add scopeNote to uniqueText explaining that uniqueness only goes in one direction.

2023-11-08 23:28 UTC, rjyounes requested changes

2023-11-08 23:28 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "The uniqueness only goes in one direction. A case may arise where two different objects have the same unique text."^^xsd:string ;
This sounds like it is a remote case, but I don't think it is necessarily, given that IDs can represent all sorts of things.

2023-11-09 03:16 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "The uniqueness only goes in one direction. A case may arise where two different objects have the same unique text."^^xsd:string ;
Can you give a specific and realistic example of two different objects that have the same unique text? I could not think of any. The wording reflected this.

2023-11-09 12:04 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "The uniqueness only goes in one direction. A case may arise where two different objects have the same unique text."^^xsd:string ;
Two organizations issue employee IDs. Both employee A at org 1 and employee B at org 2 have ID "12345." I consider this to be a potentially common occurrence.

2023-11-09 14:48 UTC, uscholdm commented
Thanks, that's a good example, in principle, but  Im not sure how often o

2023-11-09 15:58 UTC, rjyounes approved these changes

2023-11-09 15:58 UTC, merged