Issue 1001, removing the shacl-based prefix declaration and replacing…
semanticarts/gist pull request #1020
Opened 2024-01-11 19:32 UTC by pwin

… with small ttl file.

2024-01-11 20:33 UTC, sa-bpelakh approved these changes
LGTM.

2024-01-11 20:33 UTC, sa-bpelakh commented on gistCore.ttl
> +	skos:editorialNote "Information about the standard namespace prefix is in gistNamespaceInformation.ttl  ."
```suggestion
	skos:editorialNote "Information about the standard namespace prefix is in gistNamespaceInformation.ttl."
```
Tiny nit.

2024-01-26 15:50 UTC, stevenchalem approved these changes

2024-01-29 17:47 UTC, rjyounes requested changes
We need a note in this file to the effect that importing it take the user out of DL. And we need a release note.

2024-01-30 14:29 UTC, rjyounes requested changes

2024-01-30 14:29 UTC, rjyounes commented on gistNamespaceInformation.ttl
>  <https://w3id.org/semanticarts/ontology/gistCore>
Why is this going into the gistCore ontology? It should have its own ontology declaration.

2024-01-30 14:29 UTC, rjyounes commented on gistNamespaceInformation.ttl
> +	skos:editorialNote "Please note that including the file gistNamespaceInformation.ttl will break the OWL2 DL conformance of the gist ontology.  This need for this change is described in https://githu
```suggestion
	skos:editorialNote "Please note that importing this ontology will break OWL2 DL conformance because SHACL is not an OWL ontology." ;
```

2024-01-30 14:31 UTC, rjyounes commented on docs/release_notes/1001-Remove-SHACL-terms.md
> +- Removed SHACL terms to the file gistNamespaceInformation.ttl in order to preserve the OWL2 DL conformance of the core ontology. Issue [#1001](https://github.com/semanticarts/gist/issues/1001).
```suggestion
- Moved SHACL references to  the `gistPrefixDeclarations` file. Issue [#1001](https://github.com/semanticarts/gist/issues/1001).
```

Note that we don't include rationale in the release notes. They can look it up in the issue if they want. This seems nitpicky but if we go down that route we'll end up with a lot of unnecessary stuff in the release notes.

2024-01-30 14:33 UTC, rjyounes commented on gistCore.ttl
> +	skos:editorialNote "Information about the standard namespace prefix is in gistNamespaceInformation.ttl."
I prefer not to reference this file in gistCore. 

Why have we changed the name from prefix declarations to namespace information? Perhaps namespace declarations would be the best choice. Should we also be deleting the gistPrefixDeclarations file?

2024-02-04 13:59 UTC, rjyounes approved these changes

2024-02-04 13:59 UTC, merged