Issue 607 is recognized by
semanticarts/gist pull request #1023
Opened 2024-01-12 23:09 UTC by uscholdm

- Updated annotations for `gist:isRecognizedBy`
- Deprecated `gist:isRecognizedDirectlyBy`

2024-02-02 15:16 UTC, rjyounes requested changes
I've suggested a couple of minor tweaks.

2024-02-02 15:16 UTC, rjyounes commented on docs/release_notes/607-isRecognizedBy.md
> +- deprecated `gist:isRecognizedDirectlyBy`. Issue [#607](https://github.com/semanticarts/gist/issues/607).
```suggestion
- Deprecated `gist:isRecognizedDirectlyBy`. Issue [#607](https://github.com/semanticarts/gist/issues/607). 
```

2024-02-02 15:16 UTC, rjyounes commented on docs/release_notes/607-isRecognizedBy.md
> +- Updated annotations for `gist:isRecognizedBy`
What I like to do here is add a note something like 'Updated a variety of annotations.' so that we don't list out every one. Then the release manager should combine these into a single note.

2024-02-08 17:29 UTC, uscholdm commented on docs/release_notes/607-isRecognizedBy.md
> +- Updated annotations for `gist:isRecognizedBy`
There is no consistency about this, so I will leave it for now.

2024-02-08 21:49 UTC, rjyounes approved these changes

2024-02-08 21:49 UTC, merged