Add skeletal definitions for SKOS terms
semanticarts/gist pull request #1027
Opened 2024-01-25 16:55 UTC by dylan-sa

Adding skeletal definitions for SKOS terms. Omitting definitions for SHACL terms in anticipation of #1001.

Closes #934.

2024-01-25 20:11 UTC, rjyounes commented
Does the non-conforming label approach work here, or is some label required even if the format is not conformant?

2024-01-25 20:13 UTC, rjyounes commented
My preference would be to tweak the shacl so that it only applies to terms in the gist namespace.

2024-01-30 15:38 UTC, dylan-sa commented
@rjyounes @marksem -- I have tweaked the SHACL to target only classes/properties in the gist namespace.

2024-02-01 16:56 UTC, marksem approved these changes

2024-02-01 18:57 UTC, rjyounes requested changes

2024-02-01 18:57 UTC, rjyounes commented on gistCore.ttl
> +
```suggestion
skos:scopeNote a owl:AnnotationProperty ;
```

2024-02-01 18:57 UTC, rjyounes commented on validation/shapes/ontologyShapes.ttl
> +		skos:definition "Target only properties in the gist namespace."^^xsd:string ;
```suggestion
		skos:definition "Target all OWL properties in the gist namespace."^^xsd:string ;
```

2024-02-01 18:57 UTC, rjyounes commented on validation/shapes/ontologyShapes.ttl
> +		sh:select "SELECT $this WHERE { $this a ?property_type . values ?property_type { owl:DatatypeProperty owl:ObjectProperty owl:AnnotationProperty } filter(contains(str($this), 'gist')) }"^^xsd:string
```suggestion
		sh:select "SELECT $this WHERE { $this a ?property_type . VALUES ?property_type { owl:DatatypeProperty owl:ObjectProperty owl:AnnotationProperty } FILTER(CONTAINS(STR($this), 'gist')) }"^^xsd:string ;
```

2024-02-01 19:07 UTC, dylan-sa commented
@rjyounes -- Thanks for review. I have pushed changes to address comments.

2024-02-01 20:57 UTC, rjyounes commented on validation/shapes/ontologyShapes.ttl
> +		skos:definition "Target only classes in gist namespace. Filter out blank node classes to avoid noise from OWL constructs."^^xsd:string ;
Sorry, I didn't notice this the first time through. I realize this isn't new to you, but what do you think "OWL constructs" means? Do they mean restrictions?

2024-02-01 20:57 UTC, rjyounes reviewed
I have one question. Once you've clarified it, I'll approve.

2024-02-01 21:13 UTC, dylan-sa commented on validation/shapes/ontologyShapes.ttl
> +		skos:definition "Target only classes in gist namespace. Filter out blank node classes to avoid noise from OWL constructs."^^xsd:string ;
That's what I'm thinking. Could be restrictions or unions, intersections, enumerations, etc. Worth mentioning more explicitly?

```suggestion
		skos:definition "Target only classes in gist namespace. Filter out blank node classes to avoid noise from OWL constructs like property restrictions and intersections."^^xsd:string ;
```

2024-02-08 21:47 UTC, rjyounes approved these changes

2024-02-08 21:47 UTC, merged