Documentation updates
semanticarts/gist pull request #1028
Opened 2024-02-02 20:54 UTC by rjyounes

Closes #918 
Closes #993 

Also includes some minor wording changes. Note that some individual changes listed in the above issues are no longer relevant  based on previous changes to the documents.

2024-02-04 16:30 UTC, rjyounes commented
@kchastain703 @stevenchalem Asking for your review because you are or have recently been involved in managing a release, and I'd like to get your feedback on whether the new documentation is clear. Please don't forget to check out the [Confluence page](https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists) too. Thanks.

2024-02-06 15:56 UTC, uscholdm approved these changes
I did not pick over everything with a fine-tooth comb, but I did read through it all. A couple of  minor suggestions.

2024-02-06 15:56 UTC, uscholdm commented on docs/Contributing.md
> -- Prevents commits to the following branches: develop, main, and master.
Remove reference to master.

2024-02-06 19:29 UTC, stevenchalem requested changes

2024-02-06 19:29 UTC, stevenchalem commented on docs/ChangeAndReleaseManagement.md
> +- Fast-tracking. Some issues are small and non-controversial enough to bypass the group triage sessions (this is admittedly not entirely objective). These are labelled `fast-track` and put into the "
1. remove "though"
2. Change "triage sessions (this is admittedly not entirely objective)." to "triage sessions. (This is admittedly not entirely objective.)"

2024-02-06 19:29 UTC, stevenchalem commented on docs/Contributing.md
> +- The repository is configured to automatically delete the remoted branch on merge.
is "remoted" really intended here?

2024-02-06 19:29 UTC, stevenchalem commented on docs/Namespace.md
> +## An ontology needn't have any IRIs minted it its "own" namespace
is this missing a period?

2024-02-06 20:22 UTC, rjyounes commented on docs/ChangeAndReleaseManagement.md
> +- Fast-tracking. Some issues are small and non-controversial enough to bypass the group triage sessions (this is admittedly not entirely objective). These are labelled `fast-track` and put into the "
Incorporated both @stevenchalem's and @uscholdm's comments.

@uschold Thanks for the "self-assign" idea. I dislike "themselves" and "him or her" is always awkward.

2024-02-06 20:26 UTC, rjyounes commented on docs/Contributing.md
> -- Prevents commits to the following branches: develop, main, and master.
This is tricky because the pre-commit hook literally does look for all three. So I've rephrased it as 
```
 - Prevents commits to the branches `develop`, `main`, and `master` (though the latter is no longer used in the gist repository).
```

2024-02-06 20:27 UTC, rjyounes commented on docs/Contributing.md
> +- The repository is configured to automatically delete the remoted branch on merge.
Should be "remote" - thanks.

2024-02-06 20:28 UTC, rjyounes commented
@stevenchalem I've addressed all your comments - can you do a quick re-review? Thanks.

2024-02-06 21:01 UTC, stevenchalem approved these changes

2024-02-06 21:17 UTC, merged