post 531 actions - deprecating gist:symbolUnicode and gist:symbolHtml
semanticarts/gist pull request #1040
Opened 2024-02-12 22:01 UTC by pwin

2024-02-12 22:23 UTC, uscholdm requested changes
These should be removed, not deprecated. Here is why.

This is very confusing.  I'm not exactly sure what is going on. @rjyounes  It looks like the net effect of what we ended up doing was to rename `unitSymbol` to `symbol` and to remove `unitSymbolUnicode` and `unitSymbolHtml`, but we did it in two steps:
1. First we 'renamed' `unitSymbol`, and `unitSymbolUnicode` and `unitSymbolHtml`, to `unitSymbol`, `symbol` and `symbolUnicode` and `symbolHtml`,.  By rename, I mean we deprecated the original and created new properties.
2. We removed `symbolUnicode` and `symbolHtml`

Normally we do not remove things except on a major release, but in this case we are not removing anything we added during this release, we are removing something we created during this release that we then removed.

2024-02-12 22:39 UTC, uscholdm approved these changes

2024-02-13 18:46 UTC, rjyounes requested changes

2024-02-13 18:46 UTC, rjyounes commented on docs/release_notes/531-extend-symbol-predicates.md
> +  - Deleted  `gist:symbolUnicode` and `gist:symbolHtml` since they were added within this change - see above
```suggestion
  - Added predicate `gist:symbol`.
  - Added symbol triples for existing units, anticipating the removal of `gist:unitSymbol`.
```

Note: you don't need to mention deletion when they were added in this release. From the user's perspective they simply never existed. The actual changes are the deprecation of 3 predicates and the addition of one.

2024-02-13 18:48 UTC, rjyounes commented on docs/release_notes/531-extend-symbol-predicates.md
> +  - Deleted  `gist:symbolUnicode` and `gist:symbolHtml` since they were added within this change - see above
Note also that line 3 should have "Extended" rather than "Extending."

2024-02-13 19:31 UTC, rjyounes approved these changes

2024-02-13 19:31 UTC, merged