Run subclass inference during bundling
semanticarts/gist pull request #1052
Opened 2024-02-23 21:45 UTC by sa-bpelakh

Fixes #1051 

When this merges, we should remove the instructions from https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists#Materialize-Subclass-Inferences

2024-02-26 14:26 UTC, dylan-sa requested changes
Working perfectly on my end. Thanks for helping with this @bpelakh!

2024-02-26 19:28 UTC, rjyounes requested changes

2024-02-26 19:28 UTC, rjyounes commented on tools/subclass_inferences/materialize_subclass_inferences.py
> +"""Generate subClassOf inferences to help OWL-RL reasoners."""
```suggestion
"""Materialize rdfs:subClassOf inferences to help OWL-RL reasoners."""
```

2024-02-26 19:28 UTC, rjyounes commented on tools/subclass_inferences/materialize_subclass_inferences.py
> +                                 "subclass assertions that are already explicit in gistCore.",
```suggestion
        (SKOS.scopeNote, Literal("This ontology contains supplementary subclass "
                                 "assertions to aid some automated reasoners.   For example, "
                                 "while an OWL DL reasoner infers from the class equivalence that "
                                 "gist:Commitment is a subclass of gist:Intention, an RL "
                                 "reasoner does not. More precisely, the ontology contains (1) "
                                 "direct subclass assertions derived using an OWL DL reasoner and "
                                 "(2) the subclass assertions that are already explicit in gistCore.",
```

@sa-bpelakh Can you confirm the following:
* (2) is still true (if not, remove it)
* The indirect subclass triples are filtered out (if not, please remove the word "direct")

2024-02-26 19:28 UTC, rjyounes commented on tools/subclass_inferences/materialize_subclass_inferences.py
> +         description="Use OWL-DL reasoner to generate inferred rdfs:subClassOf triples. "
```suggestion
         description="Use OWL DL reasoner to generate inferred rdfs:subClassOf triples. "
```

2024-03-07 22:21 UTC, rjyounes requested changes
We need a release note. This may have changed since you were last here - consult the documentation in docs/Contributing.md.

Should we settle the question of whether to include the ontology definition or not? Or leave that until you move this over to the submodule? I'm fine with the latter.

2024-03-19 22:57 UTC, rjyounes commented
@sa-bpelakh I will approve this once the release note has been added. See comment above. Thanks.

2024-03-21 15:49 UTC, rjyounes commented
@sa-bpelakh I believe there is one more issue that hasn't been addressed: when running the script on any ontology that imports gistCore (or any ontology, for that matter), we would like to add gist to the graph but output only the subclass assertions for the classes defined in the lower ontology. This should be generalizable to any number of imports. 

One thought I had was to load the ontology you want to generate inferences for into a different graph (possibly in addition to the main graph that will be inferred over) in order to reference the classes defined there when generating the output file - I.e., only output inferences with subject in that second graph. We can't rely on namespace because gistCore shares a namespace with all the sub-gists.

2024-05-10 14:29 UTC, rjyounes commented
Adding myself as assignee to write a release note.

2024-05-29 13:22 UTC, rjyounes approved these changes

2024-05-29 13:24 UTC, merged