changes to support UoM reference data
semanticarts/gist pull request #1064
Opened 2024-03-05 15:20 UTC by philblackwood

Adding two classes and one property. Partially addresses UoM #1033.

2024-03-05 21:23 UTC, uscholdm reviewed
A few suggestions.

2024-03-05 21:23 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	.
As I understand it, the idea of a UnitGroup is a good idea serving as a convenience to the user, it can contain any set of units, depending on the desires of the user.  Suppose there is a user that has no particular need to group units together - can the idea of a UnitGroup be regarded as optional?   If not, how is a user to know what unit group (or groups) they must create?

2024-03-05 21:23 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
What if an aspect can be measured by any number of unit groups? Is it useful, or necessary or good practice to link to all of them?

2024-03-05 21:23 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
A unit group by definition has units of measure as members, you could leave that out of the definition.

2024-03-05 21:23 UTC, uscholdm commented on ontologies/gistCore.ttl
> +gist:hasUnitGroup
I preferred the term `isMeasuredBy`, from a prior proposal.

2024-03-11 20:02 UTC, philblackwood commented
Working on release notes. A brief guide to review the new ontology is attached: 
[Review Guide for Units of Measure.docx](https://github.com/semanticarts/gist/files/14563977/Review.Guide.for.Units.of.Measure.docx)

2024-04-08 14:50 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:scopeNote "When adding a unit of measure to a Unit Group, make sure it has the same exponents as the other members of the Unit Group. For example, miles per gallon and gallons per mile could bo
The exponents are with the Unit Group (and the entire data set is not large), and the conversionFactor can be used to sort the Units of Measure within a group so that ones with the scale the user cares about are easy to identify.

2024-04-08 14:52 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	.
The contents of the Unit Group should be all units that can be used to measure the same Aspect. The Unit Group serves to identify which units can be used to measure a given Aspect, so it should always be there.

2024-04-08 14:54 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
True. The redundancy is intended to make it easier for someone new to gist to understand how the concepts tie together. Not sure it is needed, but we could put the redundant part in parentheses to make the meaning of the sentence clearer.

2024-04-08 14:56 UTC, philblackwood commented on ontologies/gistCore.ttl
> +gist:hasUnitGroup
Originally I liked the "measuredBy" term but several people said they found it ambiguous, e.g. temperature is actually measured by a thermometer. 

An advantage of "hasUnitGroup" is that it implies the intended range, and is consistent with hasUnitOfMeasure and hasAspect.

2024-04-09 14:50 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:scopeNote "When adding a unit of measure to a Unit Group, make sure it has the same exponents as the other members of the Unit Group. For example, miles per gallon and gallons per mile could bo
I don't quite follow this. It would be a great help to see exactly how you would represent this exact example so I can assess it by looking at the triples.  That is the only way I can be sure to understand the proposal. Better still, for myself and future gist users, it would be helpful to have the new representation of what has been in gist for many years there as a set of triples ready to use.  I'm not sure at the moment how I would proceed using the new approach with a new client.

2024-04-09 14:52 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	.
See above comment.

2024-04-09 14:53 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
This is a matter of style/prefernce. Not sure what our general policy is. Perhaps @rjyounes can opine?

2024-04-09 15:10 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
What about the hypothetical example of astronomical units vs. teeny ones. That would seem to be a good case where two unit groupls would make sense. What is your recommendation for handling that situation?

2024-04-09 15:17 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
> "Relates an aspect to a group of units of measure. The aspect can be measuring using any of the units in the unit group."

I think you mean 'can be measured using', not 'measuring using'

2024-04-09 15:24 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
> "Relates an aspect to a group of units of measure. The aspect can be measuring using any of the units in the unit group."

This allow for any grouping of units, e..g meter, mile per hour, milligram. But that is not intended. As best as I can tell, the class `UnitGroup` is a standin for a dimension with a standard unit.

Also the definition should link the `relates` to the meaning of the relationship, such as:
`Relates an aspect to a group of units of measure whereby the aspect can be measured using any of the units in the unit group.` or

`Relates an aspect to a group of units of measure all of which can be used to measure the aspect.`

2024-04-10 19:56 UTC, kchastain703 commented on ontologies/gistCore.ttl
> -		"The precision should be in the same type of unit as the magnitude."^^xsd:string
Do we want to keep this scope note about precision in the new Magnitude definition? Or, rather, should the precision at least be in the same Unit Group as the Magnitude?

2024-04-12 12:53 UTC, rjyounes requested changes
This is amazing work! I've made some comments related to improving annotations.

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "The aspect area."^^xsd:string ;
I'd like more substantive definitions. You could take them from the current gist class definitions or grab them off Google. E.g., 

"A measure of two-dimensional space." (gist)
"A measure of a region's size on a surface." (Wikipedia)
"The extent of measurement of a surface."
etc.

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "This instance has been duplicated from reference data so it can be used in class equivalence statements."^^xsd:string ;
```suggestion
	skos:editorialNote "This instance has been duplicated from reference data so it can be used in class equivalence statements."^^xsd:string ;
```

Here and below - these are all editorial notes.

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A measurable characteristic such as cost, cycle time, or defect rate."^^xsd:string ;
```suggestion
	skos:definition "A measurable characteristic such as length, weight, cost, cycle time, or defect rate."^^xsd:string ;
```

Proposing a couple of other common examples.

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +				owl:someValuesFrom [
It would be more concise not to repeat the entire range of `gist:numericValue`. I'd be in favor of using `owl:minCardinality 1` here.

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +				owl:someValuesFrom [
Alternatively, you could go with `owl:someValuesFrom rdfs:Literal`.

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> -		"The precision should be in the same type of unit as the magnitude."^^xsd:string
@philblackwood Do we still allow for a Magnitude to have a precision? Should we keep it as a restriction (which doesn't have to be stated due to OWA)?

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "The amount of a measurable characteristic (Aspect)."^^xsd:string ;
```suggestion
	skos:definition "The amount of a measurable characteristic (aspect)."^^xsd:string ;
```

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	owl:disjointWith gist:UnitOfMeasure ;
Shouldn't be needed, since a collection is not a unit of measure (not sure if that gets stated explicitly anywhere in gist 12, but it seems out of place here. Maybe just add the disjoint on `gist:UnitOfMeasure`, since it already has a bunch of them.

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "Typically there is one UnitGroup per aspect. An example of an aspect with two unit groups is vehicle efficiency, which can be measured by miles per gallon (distance per volume) or by
```suggestion
	skos:scopeNote "Typically there is one unit group per aspect. An example of an aspect in two unit groups is vehicle efficiency, which can be measured by miles per gallon (distance per volume) or by liters per 100 kilometers (volume per distance). These two units of measure need to be in different unit groups because they have different values of exponents. When adding a unit of measure to a unit group, make sure it has the same exponents as the other members of the unit group."^^xsd:string ;
```

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A value that relates a unit of measure to units of the International System of Units. For example, in the equation 1 inch = 0.0254 meters, the value 0.0254 is the conversion factor
```suggestion
	skos:definition "A value that relates a unit of measure to units of the International System of Units. For example, in the equation 1 inch = 0.0254 meters, the value 0.0254 is the factor used to convert meters to inches."^^xsd:string ;
```

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A value that relates a unit of measure to units of the International System of Units. For example, in the equation 1 inch = 0.0254 meters, the value 0.0254 is the conversion factor
Should we add a scopeNote to the effect that standard units have a conversion factor of 1?

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "The exponent of kelvin in a product of powers of base units."^^xsd:string ;
Is Kelvin capitalized or not? Can you make it consistent either way?

2024-04-12 12:53 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:prefLabel "has unit group"^^xsd:string ;
Add example.

2024-04-12 14:55 UTC, rjyounes requested changes
Additional comments and questions.

2024-04-12 14:55 UTC, rjyounes commented on ontologies/gistCore.ttl
> +gist:exponentOfAmpere
For my own understanding - why do we have exactly these exponents?

2024-04-12 14:55 UTC, rjyounes commented on ontologies/gistCore.ttl
> +		Every member of a unit group containing milliampere will have a similar decomposition, although with a different conversionFactor."""^^xsd:string ;
Here and below:

```suggestion
		Every member of a unit group containing milliampere will have a similar decomposition, although with a different conversion factor."""^^xsd:string ;
```

2024-04-12 14:55 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "Typically there is one UnitGroup per aspect. An example of an aspect with two unit groups is vehicle efficiency, which can be measured by miles per gallon (distance per volume) or by
If a unit group has two members with the same conversion factor, do we say these are `owl:sameAs`? Otherwise you can't tell which is the standard unit.

2024-04-12 14:55 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:prefLabel "Discipline"^^xsd:string ;
How do we formally relate units to disciplines?

2024-04-12 14:57 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	owl:disjointWith gist:UnitOfMeasure ;
We should also have a restriction relating an aspect to a unit group, shouldn't we?

2024-04-12 16:56 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	owl:disjointWith gist:UnitOfMeasure ;
> We should also have a restriction relating an aspect to a unit group, shouldn't we?

A top level aspect always relates to a unit group, e.g. distance, but the lower level ones e.g. width, outer diameter point to a broader aspect, not a unit group. @philblackwood Is this right?

2024-04-12 17:16 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	owl:disjointWith gist:UnitOfMeasure ;
@uscholdm Yes, you're right.

2024-04-12 17:20 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	owl:disjointWith gist:UnitOfMeasure ;
Shouldn't be needed, since a collection is not a unit of measure. Not sure if that gets stated explicitly anywhere in gist 12, but it seems out of place here. Maybe just add the disjoint on gist:UnitOfMeasure, since it already has a bunch of them.

2024-04-12 19:28 UTC, uscholdm reviewed
On the restrictions for say, GeoRegion, the semantics is incomplete.  GeoRegion hasMagnitude a magnitude that has the aspect area. But the area aspect is not tied to any unit group or unit. This would be solved by having a separate module of unit groups, units and aspects that replace the ones in gist 12, rather than removing them.

Rather than duplicating from reference data, have the aspect instances for mass, volume etc be in a separate module that is imported by gist.y has gist:Goal gone away? 

The restriction on magnitude about precision gives infinite regress of magnitudes, there is an issue on this. #980 

The definition of Magnitude could be a bit more elaborate. 
- gist12.1.0 definition: `A quantity expressed with a unit of measure and a number.`
- current definition: `The amount of a measurable characteristic (Aspect).`
I suggest more like: 
- `The amount of a measurable characteristic intended to be used to describe something.`

Magnitude example annotation:
- Current example: `A model of car could have a wheelbase of 113.2 inches. In this example, the Aspect is wheelbase, the Unit of Measure is inch, and the numericValue is 113.2`.
- I suggest: `The magnitude of a wheelbase being equal to 116.7 inches describes the 2024 Tesla Model X. In this example, the Aspect is wheelbase, the Unit of Measure is inch, and the numericValue is 116.7.`

With the exponent properties  having a domain of `UnitGroup`, if you say the logically sensible thing, that the unit for milli-second has exponent of second equal to 1, then second will be inferred into the class `UnitGroup`. I suggest using `domainIncludes` rather than range.  This could be useful in a scenario where materialization is used for compute efficiency.

Problems with the annotations for the exponent properties:
 the example for exponentOfMeter says:
`Every member of a Unit Group containing microgram per milliliter will have a similar decomposition, although with a different conversionFactor.`

- First off, why are we talking about micograms per millilitere for the meter exponent? Probably a cut/paste and forget to edit error.
- Next, units are not given exponents, only unit groups are so it is misleading to speak of decomposition of a unit.
- Finally, term 'decomposition' is used but not explained.
I suggest this alternative:
- Have a superpropety of all the exponent properties and explain what that is all about. 
  - May or may not need/want to use the word decomposition.
  - Have a comment something like: `Every member of the unit group containing meter (e..g inch, kilometer) inherits the exponents from the unit group.`

2024-04-15 16:01 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	owl:disjointWith gist:UnitOfMeasure ;
It is a true statement. If it is inferable from other disjoint and subclass statements, then it is redundant.  Can you point that out, I'm not seeing it. Otherwise, it makes sense to keep it.

2024-04-17 18:11 UTC, kchastain703 commented on ontologies/gistCore.ttl
> +	skos:scopeNote "Every aspect should be related to a broader aspect or to a unit group. For example, angle of incidence should be related to the broader concept of angle, which in turn is related to
The scopeNote for UnitGroup mentions that an aspect can potentially have more than one unit group (the vehicle efficiency example). Should we change this note to "... to one or more unit groups" to align with that?

2024-04-17 20:40 UTC, kchastain703 commented on ontologies/gistCore.ttl
> +	skos:definition "Which unit of measure you are using. All measures are expressed in some unit of measure."^^xsd:string ;
Since we're juggling the word "measure" here a lot, do you think it might be helpful to say instead, "All measurements are expressed in..."?

2024-04-17 22:20 UTC, kchastain703 commented on ontologies/gistCore.ttl
> +	skos:example "In the equation profit = revenue - expenses, revenue is an addend and expenses is a subtrahend."^^xsd:string ;
For this example and the ones for the other math term properties, do you think it would make it more readable to set off the equation in quotation marks, like a sentence?
as in,
"In the equation 'profit = revenue - expenses', 'revenue' is an addend and 'expenses' is a subtrahend'." ?

2024-04-17 22:30 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "Which unit of measure you are using. All measures are expressed in some unit of measure."^^xsd:string ;
But the syntax needs to be cleaned up:

"Relates a magnitude to the unit of measure it uses to express a quantity." - or something.

2024-04-17 22:31 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "In the equation profit = revenue - expenses, revenue is an addend and expenses is a subtrahend."^^xsd:string ;
How about:

"""In the equation

profit = revenue - expenses

revenue is an addend and expenses is a subtrahend."""

2024-04-19 14:03 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	owl:versionIRI <https://w3id.org/semanticarts/ontology/gistCore13.0.0> ;
Fixed

2024-04-19 14:08 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
Updated to say:

skos:definition "Relates an aspect to a unit group. The aspect can be measured using any of the members of the unit group."^^xsd:string ;

2024-04-19 14:12 UTC, philblackwood commented on ontologies/gistCore.ttl
> -		"The precision should be in the same type of unit as the magnitude."^^xsd:string
Added a note about consistency. And yes, I think we need to keep precision.

note added: Note that the unit of measure of the precision has to be compatible with the unit of measure of the original magnitude (e.g. something measured in meters could have a precision in terms of millimeters or any other unit that measures distance).

2024-04-19 14:15 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:scopeNote "This instance has been duplicated from reference data so it can be used in class equivalence statements."^^xsd:string ;
Fixed

2024-04-19 14:18 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "A measurable characteristic such as cost, cycle time, or defect rate."^^xsd:string ;
Done

2024-04-19 14:46 UTC, philblackwood commented on ontologies/gistCore.ttl
> +				owl:someValuesFrom [
Nice. Done.

2024-04-19 16:13 UTC, uscholdm commented on ontologies/gistCore.ttl
> -		"The precision should be in the same type of unit as the magnitude."^^xsd:string
> And yes, I think we need to keep precision.

This results in an infinite regress of precisions (see #980 )

2024-04-19 16:18 UTC, uscholdm commented on ontologies/gistCore.ttl
> +				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
I like limiting the type to be just nonNegativeInteger, but independently, the someValuesFrom has chagned to min 1 cardinality. This goes against the style guide, which says to use someValuesFrom

2024-04-23 13:58 UTC, philblackwood commented on ontologies/gistCore.ttl
> -		"The precision should be in the same type of unit as the magnitude."^^xsd:string
Yes. In fact, a precision does have a precision, and if anybody wanted to record these they could. Are there any practical negative consequences?

2024-04-23 14:02 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "The amount of a measurable characteristic (Aspect)."^^xsd:string ;
fixed

2024-04-23 14:07 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "A value that relates a unit of measure to units of the International System of Units. For example, in the equation 1 inch = 0.0254 meters, the value 0.0254 is the conversion factor
I don't think there is a need to suggest there is a concept of "standard unit".

2024-04-23 14:11 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "A value that relates a unit of measure to units of the International System of Units. For example, in the equation 1 inch = 0.0254 meters, the value 0.0254 is the conversion factor
The original definition gives an example of a conversion factor. The proposed change doesn't say that 0.254 is a conversion factor. The scope note explains how to use the conversion factors, so nothing has been omitted.

2024-04-23 14:15 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:prefLabel "exponent of us dollar"^^xsd:string ;
done

2024-04-23 14:17 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "The exponent of kelvin in a product of powers of base units."^^xsd:string ;
Yes, Kelvin should be capitalized. Fixed.

2024-04-23 14:22 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	rdfs:range gist:Magnitude ;
I think it's OK as is.   hasAltitude makes sense. We could make it a subProperty of hasMagnitude. Also, the Domain should be expanded, so that something like an airplane can have an altitude (future change).

2024-04-23 14:28 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	.
done

2024-04-23 14:32 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:example "Miles per hour has miles as a multiplier and hour as a divisor."^^xsd:string ;
done. speed has distance as multiplier and duration as divisor.

2024-04-23 14:38 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "Relates a Thing to a magnitude."^^xsd:string ;
A magnitude can be a stand-alone amount, used by multiple things. There might also be cases when design considerations lead to making each magnitude specific to one individual. The ontology should be the same either way.

2024-04-23 14:45 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:scopeNote "Provides a supplemental method of decomposing an aspect or UnitOfMeasure into component factors. Enables dimensional analysis such as miles per hour x hours = miles."^^xsd:string ;
done

2024-04-23 14:49 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:prefLabel "has unit group"^^xsd:string ;
done

2024-04-23 14:59 UTC, philblackwood commented on ontologies/gistCore.ttl
> +gist:exponentOfAmpere
The exponents allow math such as creating a new unit of measure from existing units. Without the exponents, parsing is required. Example:

1 watt-hour per mile

= watt x hour x mile-1

= (1 x kilogram x meter2 x second-3) x (3600 x second) x (1609.344 meter)-1

= (1 x 3600 x 1609.344-1)  x kilogram x (meter2 x meter-1) x (second-3 x second)

= 2.237 x kilogram x meter x second-2

2024-04-23 15:00 UTC, philblackwood commented on ontologies/gistCore.ttl
> +		Every member of a unit group containing milliampere will have a similar decomposition, although with a different conversionFactor."""^^xsd:string ;
done

2024-04-23 15:04 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:prefLabel "Discipline"^^xsd:string ;
Discipline is a subclass of Category, so we can use gist:isCategorizedBy to relate things to disciplines. For ease of maintaining the data, it is probably simpler to relate only aspects to disciplines and then tailor the unit groups to the aspects instead of tailoring them to disciplines as I was originally thinking. For example, diastolic blood pressure would have its own unit group with just a few entries, even though theoretically we could say it has a broader aspect of pressure, and any unit of pressure could be used for blood pressure. Unfortunately, there are over 100 units for pressure and most of them are never used for blood pressure.

2024-04-23 15:09 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	owl:disjointWith gist:UnitOfMeasure ;
Volume is no longer a class. I don't see an issue.

2024-04-23 15:20 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:scopeNote "Every aspect should be related to a broader aspect or to a unit group. For example, angle of incidence should be related to the broader concept of angle, which in turn is related to
I think 99.9% of the time an aspect will be related to one unit group. But never say never. So the informal annotation describes the main case, while the ontology allows for the outlier.

2024-04-23 17:18 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:example "In the equation profit = revenue - expenses, revenue is an addend and expenses is a subtrahend."^^xsd:string ;
Added single quotes around equations.

2024-04-23 17:21 UTC, philblackwood commented on ontologies/gistCore.ttl
> +				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
As far as I can tell, someValuesFrom would require the complete list of types listed as the range of numericValue, or we can use minCardinality. Is there another option? I like the minCardinality because it is more concise, and also because it eliminates redundant listing of all the types.

2024-04-23 17:24 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "A measurable characteristic such as cost, cycle time, or defect rate."^^xsd:string ;
done

2024-04-24 14:26 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "A value that relates a unit of measure to units of the International System of Units. For example, in the equation 1 inch = 0.0254 meters, the value 0.0254 is the conversion factor
> I don't think there is a need to suggest there is a concept of "standard unit".

There is such a concept in physics, it is called 'coherent unit', it is the basis for conversions.  I am in favor of adding a scope note about this, given it is a fundamental concept in physics that the decision to not explicitly include it in the model.

2024-04-24 14:43 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	rdfs:range gist:Magnitude ;
> I think it's OK as is. hasAltitude makes sense. We could make it a subProperty of hasMagnitude.

@rjyounes makes a good point.  Doing this without an aspect undermines the goal of doing magnitudes in a consistent way.  It would serve as an example of how to use aspect in the new way.

> Also, the Domain should be expanded, so that something like an airplane can have an altitude (future change). [as opposed to just `GeoPoint`s]

Good point, so to speak, which will be moot if we choose to use an aspect instead.

2024-04-24 14:48 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:example "Height is a context-specific notion of distance, so height has broader distance."^^xsd:string ;
This is not natural English.  How about: 
- `the aspect, distance is broader than the aspect height`

I cannot think of a good way to say this mentioning the height first and still using the term 'broader'.

2024-04-24 15:17 UTC, uscholdm commented on ontologies/gistCore.ttl
> +gist:exponentOfAmpere
Perhaps add a scopeNote somewhere to explain this?

2024-04-24 15:32 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:example "Height is a context-specific notion of distance, so height has broader distance."^^xsd:string ;
reworded as requested

2024-04-24 15:33 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:prefLabel "Discipline"^^xsd:string ;
> Discipline is a subclass of Category, so **we can** use gist:isCategorizedBy to relate things to disciplines.

**we can** or **we do in fact** use gist:isCategorizedBy to relate things to disciplines.

2024-04-24 16:00 UTC, uscholdm commented on ontologies/gistCore.ttl
> +				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
In Manchester syntax, the two options are as follows (cut and pasted from Protege)
-  (gist:numericValue some xsd:nonNegativeInteger)
-  (gist:numericValue min 1 xsd:nonNegativeInteger)

Conciseness is the same.

2024-04-24 17:40 UTC, uscholdm commented on ontologies/gistCore.ttl
> +				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
Oops, my mistake.   Direct from Protege, the proper comparison is:
-  (gist:numericValue min 1 rdfs:Literal)
-  (gist:numericValue some rdfs:Literal)

The Turtle will look slightly different.

The are semantically identical and there is no significant difference in conciseness.    
The first follows our style guidelines.

2024-04-24 19:09 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:prefLabel "Discipline"^^xsd:string ;
Can. Not sure we need to. The reference data is not part of this pull request.

2024-04-24 19:17 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Aspect to a Unit Group whose members are Units of Measure. The Aspect can be measured using any of the members of the Unit Group."^^xsd:string ;
If the aspect indicates a particular range of values is needed, create a unit group for the aspect and put the appropriate units of measure in it. 

Example: pressure could have 100 different values, but diastolic blood pressure could have just a few.

2024-04-24 19:31 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:prefLabel "Discipline"^^xsd:string ;
Ok - im guessing that the evolving reference data does it this way at the moment, it's good to do so.

2024-04-24 21:12 UTC, kchastain703 commented on ontologies/gistCore.ttl
> +	skos:example "Height is a context-specific notion of distance, so height has broader distance."^^xsd:string ;
What about something like, 
"Height is specifically a distance between a lower point and a higher point..."

2024-05-09 03:06 UTC, Jamie-SA commented on ontologies/tmp.domain
Maybe I missed it somewhere, but what is this file for?

2024-05-09 13:44 UTC, uscholdm commented on ontologies/tmp.domain
@philblackwood Looks like a mistake,

2024-05-29 13:25 UTC, rjyounes commented on docs/releaseNote1033.md
> +This is a major release which includes several changes which break compatibility with previous versions of gist, most notably an entirely revised model of units and magnitudes. See the [migration gui
```suggestion
This is a major release that includes several changes which break compatibility with previous versions of gist, most notably an entirely revised model of units and magnitudes. See the [migration guide](./MajorVersionMigration.html) for documentation on updating existing gist-based ontologies and instance data. Migration scripts are included to facilitate the upgrade process.
```

2024-05-29 13:26 UTC, rjyounes commented on docs/releaseNote1033.md
> +- Deleted all subclass of `gist:UnitOfMeasure`:
```suggestion
- Deleted all subclasses of `gist:UnitOfMeasure`:
```

2024-05-29 13:43 UTC, rjyounes commented on ontologies/gistCore.ttl
> +				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
```suggestion
				owl:someValuesFrom rdfs:Literal ;
```

2024-06-03 15:54 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:scopeNote "A precision can be assigned to a magnitude to describe the probabilistic accuracy of the numeric value."^^xsd:string ;
The meaning of precision in gist is not the number of decimal places that are significant. It is intended to represent the plus/minus accuracy of a measurement (e.g. accurate to within 1 millimeter 95% of the time).

2024-06-06 15:02 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:scopeNote "A precision can be assigned to a magnitude to describe the probabilistic accuracy of the numeric value."^^xsd:string ;
It looks like the concept we want to capture is accuracy, not precision.

I suggest we change the name of the property to gist:hasAccuracy.

From the link Rebecca provided (which agrees with other sources):

"Accuracy is degree to which the measured value agrees with true value. Example-Our objective is to make rod of 25mm And we are able to make it of 25 mm then it is accurate.

Precision is the repeatability of the measuring process. Example-Our objective is to make 10 rods of 25mm and we make all rods of 24mm then we are precise as we make all rods of same size,but it is not accurate as true value is 25 mm."

2024-06-06 15:30 UTC, kchastain703 commented on ontologies/gistCore.ttl
> +	skos:scopeNote "A precision can be assigned to a magnitude to describe the probabilistic accuracy of the numeric value."^^xsd:string ;
That makes sense to me: re: changing to gist:hasAccuracy.

2024-06-07 14:32 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:scopeNote "A precision can be assigned to a magnitude to describe the probabilistic accuracy of the numeric value."^^xsd:string ;
> Precision is the repeatability of the measuring process. Example-Our objective is to make 10 rods of 25mm and we make all rods of 24mm then we are precise as we make all rods of same size,but it is not accurate as true value is 25 mm.

this surprises me. I always thought precision was about number of digits. E.g. 3.14 is less precise than 3.14159.  I would ask Dave  @mkumba what he was thinking.   Note  spurious digits may arise which should be ignored.

2024-06-07 17:36 UTC, uscholdm requested changes
Nearly there.

2024-06-07 17:36 UTC, uscholdm commented on ontologies/gistCore.ttl
> +		;
gist:Duration is no more.

2024-06-07 17:36 UTC, uscholdm commented on ontologies/gistCore.ttl
> +				owl:someValuesFrom rdfs:Literal ;
Would it make sense to use the following instead of rdfs:LIteral?
```
[
		a rdfs:Datatype ;
		owl:unionOf (
			xsd:decimal
			xsd:double
		) ;
	]
```

2024-06-07 17:36 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	rdfs:range xsd:decimal ;
Why use a different range than for conversionFactor and numericValue?

2024-06-07 17:36 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates a magnitude to the accuracy of the numeric value."^^xsd:string ;
per above comments,  I think Dave originally had in mind precision in the sense of finer granularity (e.g. more digits) rather than accuracy.

2024-06-07 22:09 UTC, kchastain703 commented on docs/releaseNote1033.md
> +Import URL: <https://w3id.org/semanticarts/ontology/gistCore13.0.0>.
I believe these are the scripts that @philblackwood wrote in order to identify and amend UoM triples in gist users' stores using the new patterns.

2024-06-08 22:46 UTC, uscholdm commented on docs/releaseNote1033.md
> +Import URL: <https://w3id.org/semanticarts/ontology/gistCore13.0.0>.
> I believe these are the scripts that @philblackwood wrote in order to identify and amend UoM triples in gist users' stores using the new patterns.

Yes, I agree. There is a separate PR for the data conversion scripts,it would be appropriate to have these comments in the other PR

2024-06-13 15:30 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "A precision can be assigned to a magnitude to describe the probabilistic accuracy of the numeric value."^^xsd:string ;
Phil: hasAccuracy = how close is the measurement to the actual measurement (probability distribution of error). This is needed for magnitudes. 

Decision: Change `hasPrecision` to `hasAccuracy`.

2024-06-13 15:30 UTC, rjyounes approved these changes

2024-06-13 15:47 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	rdfs:range xsd:decimal ;
In gist12, the conversion factor is a double. Most can be decimals (simpler to read), but some have to be double because they have so many decimal places.

So I added decimal as an option. This is generally curated data, and we can say decimal where possible, double where necessary. Keeps things simpler.

2024-06-13 15:48 UTC, philblackwood commented on ontologies/gistCore.ttl
> +	skos:definition "Relates a magnitude to the accuracy of the numeric value."^^xsd:string ;
It says "degree of _accuracy_" in the original definition.

2024-06-13 15:51 UTC, philblackwood commented on ontologies/gistCore.ttl
> +		;
changed gist:Duration to "duration"

2024-06-13 16:00 UTC, philblackwood commented on ontologies/gistCore.ttl
> +				] ;
Currently follows the same usage as gist12. 

Would be better to use gistd:_Aspect_altitude in the definition. Changed.

2024-06-13 16:04 UTC, philblackwood commented on docs/releaseNote1033.md
> +- Added scripts for the migration of existing client ontologies and instance data. [TODO - add pointer]
pointer to what?

2024-06-18 22:09 UTC, kchastain703 commented on docs/release_notes/issue1033-units-and-magnitudes.md
> +  - `gist:hasPrecision`
We changed "hasPrecision" to "hasAccuracy", right?
(I'm having a bit of trouble finding the previous discussion on it, but I think we went with "hasAccuracy".)

2024-06-19 13:40 UTC, philblackwood commented on docs/release_notes/issue1033-units-and-magnitudes.md
> +  - `gist:hasPrecision`
Yes, I will update the release notes (and the data conversion).

2024-06-19 14:10 UTC, rjyounes requested changes
@philblackwood I think the `hasAltitude` property should be removed, don't you?

2024-06-20 18:22 UTC, uscholdm submitted a review, later dismissed
@philblackwood - Im not sure which changes have been made, so this may be ready to approve. Apparently I had a few comments stacked up waiting for me to submit review.

2024-06-20 18:22 UTC, uscholdm commented on docs/release_notes/issue1033-units-and-magnitudes.md
> +  - `gist:unitSymbolUnicode`
@rjyounes I think these were removed as part of another PR/Issue,  not sure how best to rationalize the release notes, maybe it does not matter.

2024-06-21 15:31 UTC, kchastain703 approved these changes
This looks good to me.

2024-06-24 13:24 UTC, rjyounes commented on docs/release_notes/issue1033-units-and-magnitudes.md
> +  - `gist:unitSymbolUnicode`
I'll look into it when I compile the release notes.

2024-06-24 13:26 UTC, rjyounes commented on ontologies/gistCore.ttl
> +				owl:someValuesFrom rdfs:Literal ;
No. Have a look at the range of `numericValue`.

2024-06-24 13:29 UTC, rjyounes commented on ontologies/gistCore.ttl
>  				] ;
@uscholdm I guess this is an arguable point. My winning the lottery is contingent on my buying a winning ticket? If you think it's a problem, go ahead and add an issue for it. As you say, this is a hangover from the previous implementation.

2024-06-24 13:32 UTC, rjyounes approved these changes

2024-06-24 13:41 UTC, merged

2024-06-24 15:45 UTC, uscholdm commented on ontologies/gistCore.ttl
>  				] ;
Its a small point with little practical implications - I'll leave it for now.