uom data conversion explanation and queries
semanticarts/gist pull request #1071
Opened 2024-04-02 15:16 UTC by philblackwood

Unit of Measure data conversion steps (powerpoint) and SPARQL. Fixes #1034.

2024-04-02 15:21 UTC, mkumba commented
I don't think I know how to do a git review and or approval, or if I know what I'd be looking at.  There appears to be a lot to look at.



On Apr 2, 2024, at 9:18 AM, Phil Blackwood ***@***.***> wrote:



@philblackwood<https://github.com/philblackwood> requested your review on: #1071<https://github.com/semanticarts/gist/pull/1071> uom data conversion explanation and queries.

—
Reply to this email directly, view it on GitHub<https://github.com/semanticarts/gist/pull/1071#event-12327812584>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAAGJPVGOV7YTGKZJUL7HPLY3LD43AVCNFSM6AAAAABFTTDM3WVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGMZDOOBRGI2TQNA>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-04-02 22:04 UTC, rjyounes commented
You can make comments or modifications in a copy and then upload it into a GitHub comment.

From: Michael Uschold ***@***.***>
Date: Tuesday, April 2, 2024 at 3:27 PM
To: semanticarts/gist ***@***.***>
Cc: Rebecca Younes ***@***.***>, Mention ***@***.***>
Subject: Re: [semanticarts/gist] uom data conversion explanation and queries (PR #1071)

@philblackwood<https://github.com/philblackwood> @rjyounes<https://github.com/rjyounes> I want to make comments in the PowerPoint deck, what is the best way for me to do that? One way is to make a separate copy and email it to Phil who can make any desired changes and then make another commit. How can I do it more publicly on git?

—
Reply to this email directly, view it on GitHub<https://github.com/semanticarts/gist/pull/1071#issuecomment-2032943127>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAM5PZFOCFM667RSYINZYHTY3MBCVAVCNFSM6AAAAABFTTDM3WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMZSHE2DGMJSG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-29 13:49 UTC, rjyounes approved these changes
I haven't done a thorough review of the queries but I assume everything works.

2024-06-04 23:03 UTC, kchastain703 approved these changes
This looks good. Thank you for your hard work!

2024-06-07 21:44 UTC, uscholdm requested changes
Very impressive overall, and also fairly complicated. and hard to follow. Would be much easier if there were examples.  Has every one of the queries been road tested? 

Also, the lack of availability of the unit ref data makes it more or less impossible for anyone to do the conversion.

2024-06-07 21:44 UTC, uscholdm commented on migration/v13.0/queries/prepareClientReferenceData-template.rq
> +  }
An example would be super useful here. I found it difficult to make one up, in part because of the abstraction. 
- broaderAspectPredicate
- unitGroupPredicate
- unitOfMeasurePredicate

i would not epect these to vary, so much easier to just put them in.

2024-06-07 21:44 UTC, uscholdm commented on migration/v13.0/uomDataConversion.pptx
[uomDataConversion-MU.pptx](https://github.com/user-attachments/files/15745182/uomDataConversion-MU.pptx)

This is a copy of the deck with comments and a few added slides.

2024-06-14 15:01 UTC, philblackwood commented on migration/v13.0/uomDataConversion.pptx
Updates included: 
Remove slide showing SA internal process steps of updating, validating, and extracting subset of reference data for client.
Clarify that client reference data is not the full data reference data set, only the subset used by the client.
Improve diagrams (":" before Area and remove diagram using hasAspect).
Remove double arrows from mapping between SA reference data and client existing data.

Complete model is not included because it is not required to do the conversion.

2024-06-14 21:22 UTC, uscholdm commented on migration/v13.0/uomDataConversion.pptx
> Complete model is not included because it is not required to do the conversion.

ok

2024-06-14 21:33 UTC, uscholdm commented on migration/v13.0/uomDataConversion.pptx
> Improve diagrams (":" before Area and remove diagram using hasAspect).

There is no ':' in the current copy as of commit:

Commit: 254f98139fdc0d8a0ceb0e12c48d5fda6e5dd760 [254f981]
Parents: 28275d3ffa
Author: philblackwood <phil.blackwood@semanticarts.com>
Date: Monday, 10 June, 2024 10:50:23
Committer: philblackwood

2024-06-14 21:51 UTC, uscholdm commented on migration/v13.0/uomDataConversion.pptx
> Remove double arrows from mapping between SA reference data and client existing data.

The double arrows are still there. Perhaps you made changes but they did not make it to the commit?

2024-06-14 23:38 UTC, philblackwood commented on migration/v13.0/uomDataConversion.pptx
changes committed and pushed

2024-06-19 20:33 UTC, uscholdm approved these changes

2024-06-19 20:33 UTC, uscholdm commented on migration/v13.0/uomDataConversion.pptx
Phil and I have had several go-rounds on this and it keeps improving to the point where we are mostly just fine-tuning.

2024-06-24 13:22 UTC, merged