Bugfix/issue 944: tweaks to ordered member and has first member
semanticarts/gist pull request #1074
Opened 2024-04-02 21:28 UTC by brett-heffelfinger

- tweaked `scopeNote` for `hasFirstMember`: updated language to reflect that strict orderings *are* allowed
- added `providesOrderFor` restriction to `OrderedMember`
- change filter class for `hasFirstMember` restriction on `OrderedCollection` from `owl:Thing` to `OrderedMember`

2024-04-02 22:08 UTC, turingtest37 approved these changes
This looks good.

2024-04-02 22:11 UTC, rjyounes requested changes
OWL looks good, release notes need some fixes.

2024-04-02 22:11 UTC, rjyounes commented on docs/release_notes/Issue-944-tweaks-to-OrderedMember-and-hasFirstMember.md
> +- added `providesOrderFor` restriction to `OrderedMember`
You should review the format for release notes and make appropriate corrections.

2024-04-03 13:47 UTC, brett-heffelfinger commented on docs/release_notes/Issue-944-tweaks-to-OrderedMember-and-hasFirstMember.md
> +- added `providesOrderFor` restriction to `OrderedMember`
I've made changes based on the Contributing guidelines; can you re-review and let me know if there are any further changes needed? Thank you!

2024-04-03 16:13 UTC, uscholdm approved these changes
I'm good with this. Let's see what Rebecca thinks.

2024-04-03 19:48 UTC, rjyounes reviewed
Thanks for fixing the release notes. I've just suggested the addition of periods at the line ends.

2024-04-03 19:48 UTC, rjyounes commented on docs/release_notes/Issue-944-tweaks-to-OrderedMember-and-hasFirstMember.md
> +- Adjusted `skos:scopeNote` for `gist:hasFirstMember`: updated language to reflect that strict orderings *are* allowed.  Issue [944](https://github.com/semanticarts/gist/issues/944)
```suggestion
- Added `gist:providesOrderFor` restriction to `gist:OrderedMember`. Issue [944](https://github.com/semanticarts/gist/issues/944).
- Changed filter class for `gist:hasFirstMember` restriction on `gist:OrderedCollection` from `owl:Thing` to `gist:OrderedMember`. Issue [944](https://github.com/semanticarts/gist/issues/944).

### Patch Updates
- Adjusted `skos:scopeNote` for `gist:hasFirstMember`: updated language to reflect that strict orderings *are* allowed.  Issue [944](https://github.com/semanticarts/gist/issues/944).
```

Looks good now, just adding periods to the end of the sentences (understood that they aren't full sentences).

2024-04-03 21:34 UTC, rjyounes approved these changes

2024-04-03 21:34 UTC, merged