Feature/new issue 831 add event specification
semanticarts/gist pull request #1077
Opened 2024-04-15 14:51 UTC by uscholdm

Fixes #831 
- Added `EventSpecification`.
- Added and updated annotations for `Specification`.

OPEN QUESTION: there is now an incorrect subclass relationship.

`Requirement`: gist 12.0: 
- "A documented physical or functional need that a particular design, product, or process must be able to perform.  Alternately, the obligation of a person or organization to behave in a certain way (i.e., drive on the right side of the road)."

Updated definition of `Specification`:
- "One or more characteristics that specify what it means to be a particular type of thing such as a material, product, service or event. A specification is sufficiently precise to allow conformance of something to the specification to be tested."

A Specification is often not a need to be performed, so Specification cannot be a subclass of Requirement.  It includes the idea of a law or regulation which is outside the scope of a specification.
 
Options include:
1. Broaden the definition of Requirement to include Specification so the subclass relationship can remain. Easier said than done. 
2. Remove the class Requirement, it's never been use in my experience, if anyone want to represent a law or regulation, they can create a separate subclass.

2024-04-18 11:44 UTC, rjyounes commented
@uscholdm Is this PR ready for review? You've requested my review but it's still in draft state.

2024-04-18 21:01 UTC, rjyounes commented
You could tweak the definition of `Requirement` to include the sense of `Specification` that includes `EventSpecification`. This makes perfect semantic sense to me: a certain weather event is required to have certain characteristics in order to be a hail storm and thus covered under insurance policy XYZ. 

What I really don't like is that - as acknowledged in the current definition - `Requirement` merges two entirely separate concepts, presumably because they use the same English word - that's a trap we shouldn't fall into. Is this what you are suggesting? - to remove `Requirement` and promote `Specification` and `Restriction` to direct subclasses of `Intention`? Thus not combining the two different meanings of "requirement" into one class?

That might be nice, but that is too large a change to be rolled into this PR without group consideration. So for right now I would choose the first option I mentioned, and add a new issue for the second, to be considered for version 13.1.0.

2024-04-19 02:06 UTC, uscholdm commented
> What I really don't like is that - as acknowledged in the current definition - `Requirement` merges two entirely separate concepts, presumably because they use the same English word - that's a trap we shouldn't fall into. Is this what you are suggesting? - to remove `Requirement` and promote `Specification` and `Restriction` to direct subclasses of `Intention`? Thus not combining the two different meanings of "requirement" into one class?

Yes exactly! 

> That might be the right thing to do, but that is too large a change to be rolled into this PR without group consideration. 

agreed

> So for right now I would choose the first option I mentioned, and add a new issue for the second, to be considered for version 13.1.0.

I tried a bunch of wording tweaks and failed to find something much better.  I propose to just leave it for now and add an issue.  It's only by chance I happened to notice anyway, and its only an annotation for a class that as far as I know rarely gets used.

2024-04-19 13:58 UTC, rjyounes requested changes
Looks good. I've proposed some wording tweaks.

2024-04-19 13:58 UTC, rjyounes commented on docs/release_notes/Issue-831-EventSpecification.md
> +- Added `EventSpecification` [#831](https://github.com/semanticarts/gist/issues/831).
```suggestion
- Added `gist:EventSpecification`. Issue [#831](https://github.com/semanticarts/gist/issues/831).
```

2024-04-19 13:58 UTC, rjyounes commented on docs/release_notes/Issue-831-EventSpecification.md
> +- Added and updated annotations for `Specification` [#831](https://github.com/semanticarts/gist/issues/831).
```suggestion
- Added and updated annotations for `gist:Specification`. Issue [#831](https://github.com/semanticarts/gist/issues/831).
```

2024-04-19 13:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "A hail storm that is covered by an insurance policy.  Someone defaults on a loan."^^xsd:string ;
How about something like:

An insurance company defines the characteristics of a weather event that must be satisfied for it to qualify as a hail storm covered in its homeowner's policy. Defaulting on a loan.

2024-04-19 13:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "It is useful for risk assessment and insurance policies."^^xsd:string ;
```suggestion
	skos:scopeNote "This concept is useful for risk assessment and insurance policies."^^xsd:string ;
```

2024-04-19 13:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "The specification of the iPhone 14; hypothetical events covered by a home owner's insurance policy."^^xsd:string ;
```suggestion
	skos:example "The specification of the iPhone 14; hypothetical events covered by a homeowner's insurance policy."^^xsd:string ;
```

2024-04-19 13:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "One or more characteristics that specify what it means to be a particular type of thing such as a material, product, service or event. A specification is sufficiently precise to all
```suggestion
	skos:definition "One or more characteristics that specify what it means to be a particular type of thing such as a material, product, service or event. A specification is sufficiently precise to allow evaluating conformance to the specification."^^xsd:string ;
```

"Evaluating" seems like a more accurate term in the case of event specifications.

2024-04-19 14:02 UTC, rjyounes commented
@uscholdm I've created issue #1087 for the `Requirement` proposal.

2024-04-19 14:58 UTC, uscholdm reviewed
@rjyounes This is ready for review again.

2024-06-13 20:40 UTC, rjyounes requested changes

2024-06-14 17:25 UTC, uscholdm reviewed
I don't know why I am being asked to review my own PR

2024-06-14 19:03 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	rdfs:subClassOf gist:Specification ;
You could, but Im not sure we want to.  It says if anything conforms to the event spec, then that thing must be an event. Its rather self-evident, and i suspect we could do this sort of thing in many places.

2024-06-19 15:17 UTC, rjyounes approved these changes

2024-06-19 15:18 UTC, merged