Remove occupies predicates and shorten isGeographicallyContainedIn
semanticarts/gist pull request #1085
Opened 2024-04-18 15:27 UTC by rjyounes

Fixes #809 - see https://github.com/semanticarts/gist/issues/947#issuecomment-1679565100
Fixes #812 

NB: I've deliberately kept the full prefLabel "is geographically contained in" for `isGeoContainedIn`. This is a bending of our rule about constructing pref labels, but in this case is warranted, in my opinion. I've updated the style guide to reflect this change.

2024-04-18 22:55 UTC, kchastain703 commented on docs/gistStyleGuide.md
> +- Deviation from typographical conventions such as case. For example, a proper name in a property label could appropriately be capitalized. Since this will fail the SHACL validation constraints durin
Should we give an example of this, too?

2024-04-19 01:33 UTC, uscholdm approved these changes
Looks good.

2024-04-22 20:35 UTC, dylan-sa requested changes

2024-04-22 20:35 UTC, dylan-sa commented on docs/gistStyleGuide.md
> +- Deviation from typographical conventions such as case. For example, a proper name in a property label could appropriately be capitalized. Since this will fail the SHACL validation constraints durin
I agree w/ @kchastain703 that an example would be helpful.

2024-04-22 20:35 UTC, dylan-sa commented on docs/gistStyleGuide.md
> +- Deviation from typographical conventions such as case. For example, a proper name in a property label could appropriately be capitalized. Since this will fail the SHACL validation constraints durin
In the 'Properties' section above, it already says we can deviate from lower case for proper nouns. So the exception here doesn't seem like a genuine exception to the convention as stated. Maybe we can say the convention is simply lowercase, and then the bit about normalizing to natural language standards can be left to the 'Valid Exceptions' section?

2024-05-23 14:30 UTC, rjyounes commented on docs/gistStyleGuide.md
> +- Deviation from typographical conventions such as case. For example, a proper name in a property label could appropriately be capitalized. Since this will fail the SHACL validation constraints durin
I can't think of a good one. I think the text following "For example..." is pretty self-explanatory, so I'm going to resolve this.

2024-05-23 14:32 UTC, rjyounes commented on docs/gistStyleGuide.md
> +- Deviation from typographical conventions such as case. For example, a proper name in a property label could appropriately be capitalized. Since this will fail the SHACL validation constraints durin
This is a good point. I think I'll just remove that point and add a note about the validation annotations.

2024-05-29 13:07 UTC, merged