Removes sensor-related terms to fix issue 462
semanticarts/gist pull request #1089
Opened 2024-04-25 15:21 UTC by turingtest37

Fixes #462

2024-05-09 03:09 UTC, Jamie-SA requested changes

2024-05-09 03:09 UTC, Jamie-SA commented on ontologies/Issue-462-Remove-Sensor-Related-Items.md
> +  - `gist:Controller`
```suggestion
  - `gist:Controller`
  - `gist:ControllerType`
```

2024-05-09 13:58 UTC, uscholdm reviewed
- `gist:MessageDefinition` looks to be sensors-specific. I propose that we remove it unless there is justification for having it independently from sensors.
- `gist:directs` looks to be sensors-specific. I propose that we remove it unless there is justification for having it independently from sensors.
- `gist:accepts` looks to be sensors-specific. I propose that we remove it unless there is justification for having it independently from sensors.

2024-05-09 13:58 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Each communication to and from a remote device or application programming interface is reflected in a message."^^xsd:string ;
This looks to be specific to sensors. I propose to remove the class MessageDefinition.

2024-05-09 15:34 UTC, rjyounes commented
DECISION:

* Remove `MessageDefinition` and `directs`
* Rewrite definition of `accepts` as "Relates something to the types of inputs it accepts."

2024-05-09 15:34 UTC, rjyounes requested changes
See decision in main comment thread.

2024-05-27 21:05 UTC, rjyounes commented on ontologies/Issue-462-Remove-Sensor-Related-Items.md
> +  - `gist:Controller`
Should remove `PhenomenaType`

2024-05-27 21:06 UTC, rjyounes commented on ontologies/Issue-462-Remove-Sensor-Related-Items.md
> +- Changed `skos:definition` of `gist:directs` to remove sensor references.
We should delete this.

2024-05-29 14:55 UTC, rjyounes requested changes

2024-05-29 14:55 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "To issue orders to someone or something by right of authority."^^xsd:string ;
We have agreed to delete this term: https://github.com/semanticarts/gist/pull/1089#issuecomment-2102900192

2024-05-30 11:45 UTC, turingtest37 commented on ontologies/gistCore.ttl
> +	skos:definition "Each communication to and from a remote device or application programming interface is reflected in a message."^^xsd:string ;
I'm not sure I agree. A Message Definition is not specific to sensors at all. Any data exchange with a remote service / API will have a message definition. I think it makes sense to leave this class as an example of what SchemaMetaData represents.

2024-06-13 15:09 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "Each communication to and from a remote device or application programming interface is reflected in a message."^^xsd:string ;
Michael and I agree that this should be removed by the same logic as `gist:directs`.

2024-06-13 15:10 UTC, rjyounes commented
@uscholdm  to contact @turingtest37 to resolve questions about term deletions.

2024-06-14 16:47 UTC, uscholdm requested changes
Remove MessageDefinition

2024-06-14 16:47 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Each communication to and from a remote device or application programming interface is reflected in a message."^^xsd:string ;
The idea is that, as originally conceived, MessageDefinition was specifically aligned with sensor concepts, and thus should be removed. 

@turingtest37 Separately, if we think that there is a need for something like MessageDefinition that has broader use outside the sensors context, then a new issue to that effect should be created, just like we do for adding a totally new concept to gist.

2024-06-24 13:51 UTC, rjyounes approved these changes

2024-06-24 13:54 UTC, merged