Issue/633 media type
semanticarts/gist pull request #1095
Opened 2024-05-24 22:10 UTC by uscholdm

2024-05-29 13:06 UTC, rjyounes requested changes

2024-05-29 13:06 UTC, rjyounes commented on docs/release_notes/Issue-633-MediaType.md
> +- `gist:MediaType` & `gist:uniqueText`
```suggestion
- `gist:MediaType`
```

I think this is primarily about `MediaType`, not `uniqueText`.

2024-05-29 13:06 UTC, rjyounes commented on docs/release_notes/Issue-633-MediaType.md
> +  - Added example and scope note annotations to `gist:MediaType`
```suggestion
  - Added example and scope note annotations to `gist:MediaType`.
```

2024-05-29 13:06 UTC, rjyounes commented on docs/release_notes/Issue-633-MediaType.md
> +  - Added `gist:MediaType` to `gist:domainIncludes` for `gist:uniqueText`
```suggestion
  - Added `gist:MediaType` to `gist:domainIncludes` for `gist:uniqueText`.
```

2024-05-29 13:06 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "The unique text for a media type is the concatenation of the 'Type name', a slash '/', and the 'Subtype name' as provided on the page displayed when you resolve the URI of the MediaT
This strikes me as a SHACL rule and not part of the meaning of the term. The unique text is only constrained at an implementation level, IMO. We show what we are using in the example and also in our supplementary vocabulary.

2024-05-31 14:49 UTC, uscholdm commented on docs/release_notes/Issue-633-MediaType.md
> +- `gist:MediaType` & `gist:uniqueText`
Primarily, yes. I included it because it adds a domain includes on uniqueText.

2024-05-31 14:54 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:scopeNote "The unique text for a media type is the concatenation of the 'Type name', a slash '/', and the 'Subtype name' as provided on the page displayed when you resolve the URI of the MediaT
It's just a scope note, I found it illuminating, I prefer to keep it. If you feel strongly about it, run it by Jamie, it was his comment.

2024-06-13 15:35 UTC, marksem commented on ontologies/gistCore.ttl
> +			a owl:Restriction ;
This is saying the _meaning_ of a media type is that it has a unique ID string.  Is that was is intended?  (I suppose it is reasonable).

2024-06-13 20:35 UTC, rjyounes requested changes

2024-06-13 20:35 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "The unique text for a media type is the concatenation of the 'Type name', a slash '/', and the 'Subtype name' as provided on the page displayed when you resolve the URI of the MediaT
How about this?

```suggestion
	skos:scopeNote "The unique text for an IANA media type is the concatenation of the 'Type name', a slash '/', and the 'Subtype name' as provided on the page displayed when you resolve the URI of the media type."^^xsd:string ;
```

2024-06-14 17:52 UTC, uscholdm commented on ontologies/gistCore.ttl
> +			a owl:Restriction ;
It means that in the real world, every media type has a unique string, whether or not it is in the KG.

2024-06-19 14:28 UTC, dylan-sa approved these changes

2024-06-19 15:20 UTC, rjyounes approved these changes

2024-06-19 15:21 UTC, merged