Added Determination class.
semanticarts/gist pull request #1096
Opened 2024-05-24 23:29 UTC by uscholdm

I made the class a direct subclass of `Event` because a `Determination` need not be historical, it may be planned but unscheduled, or scheduled, in the process of happening, or already happened.

2024-05-29 13:03 UTC, rjyounes requested changes

2024-05-29 13:03 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "An event whose central purpose is to obtain some kind of result, value or outcome. The basis for the determination can be qualitative, quantitative or a combination of both. "^^xsd:
This definition seems a little off, perhaps because of the use of "obtain." Many events are held to obtain a result - e.g., a campaign speech has the purpose of gathering support, but this is not a determination. 

Some suggestions based on various dictionary definitions:
* An event whose purpose is to establish something by calculation or research. The basis for the determination can be..."
* The act of measuring, evaluating, or calculating something.
* The process of finding out or calculating something.
* The act of determining the properties of something, usually by research or calculation.

2024-05-29 13:03 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "This class is meant to exclude cases such as the chemical makeup of food determining its taste. "^^xsd:string ;
This is not needed if you modify the definition as suggested.

2024-05-31 14:31 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "An event whose central purpose is to obtain some kind of result, value or outcome. The basis for the determination can be qualitative, quantitative or a combination of both. "^^xsd:
How about "An event whose purpose is to establish a specific result, value, or outcome usually by research, measuring, evaluating, or calculating."

2024-06-13 15:33 UTC, marksem commented on ontologies/gistCore.ttl
> +gist:Determination
I like the work done so far. 

Q: Is there any property that would always be the case on a determination?  Otherwise this is just a named class.

2024-06-13 20:31 UTC, rjyounes requested changes
I like your proposed definition, so will approve this once you've added it and removed the scope note.

2024-06-13 20:31 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "An event whose central purpose is to obtain some kind of result, value or outcome. The basis for the determination can be qualitative, quantitative or a combination of both. "^^xsd:
That's good, but needs a comma after "outcome."

2024-06-14 17:40 UTC, uscholdm commented on ontologies/gistCore.ttl
> +gist:Determination
@marksem In real world terms, a determination 
- will always have an entity that does the determining (maybe inverse of `produces`) with the doer being a person, org or program
- will always have an outcome (in the past I have used `hasOutput` for this)
- will often have a method (min 0).

2024-06-14 17:41 UTC, uscholdm reviewed
Not sure why Im being asked to review my own PR

2024-06-19 15:27 UTC, rjyounes commented
@uscholdm I'm leaving this unmerged to consider whether we want to name it `DeterminationEvent` rather than `Determination`. Looks like it also needs to be updated with latest changes on develop.

2024-06-20 14:37 UTC, uscholdm commented
> @uscholdm I'm leaving this unmerged to consider whether we want to name it `DeterminationEvent` rather than `Determination`. Looks like it also needs to be updated with latest changes on develop.

Lets leave it as it is. Its a subclass of `Event`.

2024-06-20 16:09 UTC, rjyounes approved these changes

2024-06-20 16:09 UTC, merged