Style guide updates
semanticarts/gist pull request #1098
Opened 2024-05-29 20:29 UTC by rjyounes

Closes #511 - Best practices for negative examples in `skos:example`
Closes #966 - Using or not using ontology terms in annotations
Closes #1080 - Fixed broken link to OntoClean
Closes #1086 - Best practices for inverses (don't)

2024-05-29 22:14 UTC, dylan-sa requested changes

2024-05-29 22:14 UTC, dylan-sa commented on docs/gistStyleGuide.md
>  Note: As of version 12.0.0, gist itself does not itself follow the infix convention, though it does use the leading underscore. This is under consideration for a future update.
After the unit instances are removed in 13.0.0, will we have any remaining violations of this guideline (maybe the media types)? If not, we can remove this. If yes, we can bump to 13.0.0.

2024-05-31 17:10 UTC, uscholdm commented on docs/gistStyleGuide.md
> +| Child | Parent |
Suggest:

`| Child to Parent (used) | Parent to Child (not used)|`

COme to think of it, why include parent to child in this documentation when the ontology does not include  it?
If we do want them, then make it more obvious that they are being left out

2024-06-13 14:51 UTC, rjyounes commented on docs/gistStyleGuide.md
> +| Child | Parent |
The purpose of the examples is to illustrate how the principle applies to the choices we made.

2024-06-13 14:51 UTC, rjyounes commented on docs/gistStyleGuide.md
> +| Child | Parent |
```suggestion
| Child to Parent | Parent to Child |
```

2024-06-13 14:52 UTC, rjyounes commented on docs/gistStyleGuide.md
>  Note: As of version 12.0.0, gist itself does not itself follow the infix convention, though it does use the leading underscore. This is under consideration for a future update.
Is this comment out of date? I've changed it to organizations.

2024-06-13 20:27 UTC, rjyounes commented
Sorry about this, the release notes here actually go with a different PR which has been merged. The release notes for this PR got merged with that PR. So I'm leaving these release notes to merge in with this PR.

2024-06-13 20:28 UTC, merged