Update definition of patch release
semanticarts/gist pull request #1099
Opened 2024-05-29 20:43 UTC by rjyounes

Closes #973.

2024-05-30 19:40 UTC, stevenchalem requested changes
This looks good other than the minor quibbles I noted.

2024-05-30 19:40 UTC, stevenchalem commented on docs/ChangeAndReleaseManagement.md
> +- **Patch:** Backward-compatible bug fixes, documentation, and infrastructure changes that affect process but not the ontology itself. Examples:
I suggest "... changes that affect _the gist release_ process but not ...". It might not be clear to everyone process we're referring to.

2024-05-30 19:40 UTC, stevenchalem commented on docs/ChangeAndReleaseManagement.md
> +  - Modification of the bundle configuration.
For grammatical consistency, this should be "modifying", not "modification of".

2024-05-31 13:23 UTC, rjyounes commented on docs/ChangeAndReleaseManagement.md
> +- **Patch:** Backward-compatible bug fixes, documentation, and infrastructure changes that affect process but not the ontology itself. Examples:
```suggestion
- **Patch:** Backward-compatible bug fixes, documentation, and infrastructure changes that affect the gist release process but not the ontology itself. Examples:
```

2024-05-31 13:24 UTC, rjyounes commented on docs/ChangeAndReleaseManagement.md
> +  - Modification of the bundle configuration.
```suggestion
  - Modifying the bundle configuration.
```

2024-05-31 13:58 UTC, uscholdm approved these changes
Looks good

2024-05-31 15:08 UTC, stevenchalem approved these changes

2024-05-31 17:14 UTC, uscholdm approved these changes

2024-06-13 14:50 UTC, merged