Add predicate isOfferOf - fixes #528
semanticarts/gist pull request #1102
Opened 2024-06-11 19:01 UTC by stevenchalem

2024-06-11 19:37 UTC, Jamie-SA submitted a review, later dismissed
The prefLabel needs to be fixed, and a possible suggestion for the release notes.

2024-06-11 19:37 UTC, Jamie-SA commented on docs/release_notes/issue528-add-isOfferOf.md
> +- Added `gist:isOfferOf` predicate
I would say that the addition of a new predicate is a Minor update, but line below about changing the restrictions of an existing item is Major. Not sure if it should be separated into 2 parts in the release notes.

2024-06-11 19:37 UTC, Jamie-SA commented on ontologies/gistCore.ttl
> +	skos:prefLabel "is order of"^^xsd:string ;
```suggestion
	skos:prefLabel "is offer of"^^xsd:string ;
```

2024-06-12 21:44 UTC, uscholdm requested changes
Change prefLabel per Jamie's suggestion.
Update release notes per my suggestion

2024-06-12 21:44 UTC, uscholdm commented on docs/release_notes/issue528-add-isOfferOf.md
> +- Added `gist:isOfferOf` predicate
I agree with Jamie on this, one is major one is minor. However, I'm inclined to just put both changes together in one place in the major changes section.

2024-06-12 21:44 UTC, uscholdm commented on docs/release_notes/issue528-add-isOfferOf.md
> +- Added `gist:isOfferOf` predicate
- Made changes to `gist:Offer`
  - Added `gist:isOfferOf` predicate
  - Modified restriction on `gist:Offer` to refer to `gist:isOfferOf`. Issue [#528](https://github.com/semanticarts/gist/issues/528)

2024-06-13 14:49 UTC, rjyounes requested changes

2024-06-13 14:49 UTC, rjyounes commented on docs/release_notes/issue528-add-isOfferOf.md
> +- Added `gist:isOfferOf` predicate
Michael's version looks good to me.

2024-06-13 14:49 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Offer to a thing being offered."^^xsd:string ;
```suggestion
	skos:definition "Relates an offer to the thing being offered."^^xsd:string ;
```

Our convention is to use ordinary language rather than ontology terms wherever possible.

2024-06-13 15:25 UTC, marksem commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Offer to a thing being offered."^^xsd:string ;
Late to the party, but wouldn't `offers` be less contrived, and mean the same thing, and be more generally useful? 

Like 
Offering  offers X  (Product Spec, etc)
Organization offers Y (Benefit, etc.)

2024-06-13 15:26 UTC, marksem commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an Offer to a thing being offered."^^xsd:string ;
And I think it doesn't just 'relates an Offer to'.... it can relate lots of things.  Saying it relates an Offer is akin to a domain restriction.  We avoid such global constraints.

2024-06-13 15:59 UTC, rjyounes commented
We've agreed to change from `isOfferOf` to `offers`. Add scopeNote/example about the different uses (with `Offer` vs `Organization/Person etc`).

2024-06-13 16:36 UTC, rjyounes commented
```
skos:definition "Relates something to a thing it makes available for acceptance or rejection." ;
skos:example "An instance of gist:Offer offers a specific product at a particular price; a company offers an employee benefit; Honda offers vehicles for sale.";

```

2024-06-14 18:03 UTC, uscholdm commented
@stevenchalem 

> `skos:definition "Relates something to a thing it makes available for acceptance or rejection."`

I suggest: 
- `skos:definition "Relates something to a thing that is being made available for acceptance or rejection."`

2024-06-14 18:08 UTC, uscholdm requested changes
A couple of rewording suggestions.

2024-06-14 18:08 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates something to a thing it makes available for acceptance or rejection."^^xsd:string ;
The word, 'it' here is ambiguous. I suggest:
- `skos:definition "Relates something to a thing that is being made available for acceptance or rejection."`

2024-06-14 18:08 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:prefLabel "is offer of"^^xsd:string ;
label should be `offers`

2024-06-20 22:41 UTC, rjyounes commented
@stevenchalem Sorry about the back and forth. Michael is willing to go ahead with `offers` and I trust his judgment on this. So let's go ahead and finalize this PR. Thanks.

2024-06-24 13:43 UTC, rjyounes commented on docs/release_notes/issue528-add-isOfferOf.md
> +  - Modified restriction on `gist:Offer` to refer to `gist:offers`. Issue [#528](https://github.com/semanticarts/gist/issues/528)
```suggestion
  - Modified restriction on `gist:Offer` to refer to `gist:offers`. Issue [#528](https://github.com/semanticarts/gist/issues/528).
```

2024-06-24 13:43 UTC, rjyounes approved these changes

2024-06-24 13:46 UTC, rjyounes commented on docs/release_notes/issue528-add-isOfferOf.md
> +  - Modified restriction on `gist:Offer` to refer to `gist:offers`. Issue [#528](https://github.com/semanticarts/gist/issues/528).
```suggestion
- Made changes to `gist:Offer`. Issue [#528](https://github.com/semanticarts/gist/issues/528).
  - Added `gist:offers` predicate.
  - Modified restriction on `gist:Offer` to refer to `gist:offers`. 
```

2024-06-24 13:47 UTC, merged