Added updates for addresses
semanticarts/gist pull request #1106
Opened 2024-06-14 20:07 UTC by kchastain703

updates to address modelling, resolving https://github.com/semanticarts/gist/issues/1060

2024-06-14 21:40 UTC, rjyounes commented on docs/AddressGuidance.md
> +- gist:\ElectronicMessageAddress
Here and throughout, there is a problem with backslashes.

```suggestion
- gist:ElectronicMessageAddress
```

2024-06-14 23:24 UTC, uscholdm requested changes
- gist:PrecedenceType is in the documentation but not in the ontology
- there should be a traditional concise version of release notes which refers to the address guidance. For example:
  - classes added and removed
  - properties added and removed
-  - A bunch of small suggestions, mostly annotations.

2024-06-14 23:24 UTC, uscholdm commented on docs/AddressGuidance.md
> +The gist:ElectronicAddress class has no formal restriction definition. But it does have a text definition: _"_ _Content referring to a locatable virtual place not physically existing, as such, but ma
```suggestion
The `gist:ElectronicAddress` class has no formal restriction definition. But it does have a text definition: _"_ _Content referring to a locatable virtual place not physically existing, as such, but made by software or electronics to appear to do so."_ From a practical perspective, it is an address which is not tangible. One cannot touch it. (One might touch the WI-FI router associated with your IP Address. But that is _not_ the address itself.)

2024-06-14 23:24 UTC, uscholdm commented on docs/AddressGuidance.md
> +
PrecedenceType is NOT in the ontology. Either put it in or remove this bullet.

2024-06-14 23:24 UTC, uscholdm commented on docs/AddressGuidance.md
> +- ex:\_PrecedenceType_non_primary
PrecedenceType is NOT in the ontology.

2024-06-14 23:24 UTC, uscholdm commented on docs/AddressGuidance.md
> +In the case of some electronic address types (e.g., email addresses), one might choose not to use the gist:references property, at all.
```suggestion
In the case of some electronic address types (e.g., email addresses), one might choose not to use the `gist:refersTo` property, at all.

2024-06-19 15:56 UTC, kchastain703 commented on docs/AddressGuidance.md
> +- ex:\_PrecedenceType_non_primary
Do you think we should add this in as `PrecedenceType` or as `AddressPrecedenceType`?

2024-06-19 15:58 UTC, rjyounes requested changes
@kchastain703 @DanCarey404 Have you figured out who will be addressing the review comments? Hopefully both of you.

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +# New Patterns for Using gist:Address
@DanCarey404 @kchastain703 Our decision was to put this document into the `gist-doc` repo, and limit our documentation in the `gist` repo to migration information.

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +# New Patterns for Using gist:Address
@DanCarey404 @kchastain703 I'm also not convinced that we need all this justification and comparison with the previous state here. This is not something we normally do, and it will be irrelevant to anyone who hasn't used gist12 or earlier. In the `gist-doc` documentation, I would just describe the model itself without justifying or explaining the changes relative to previous versions.

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +| **Pattern Set 2** | gist:ElectronicAddress | gist:containedText | xsd:string |
```suggestion

```

Duplicate line

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +Beyond the physical/electronic distinction made by the classes, other important distinctions need to be made. One reasonably might ask, "Still, what _kind_ of address are we talking about?" These add
Scratch the term "CBox." 
```suggestion
Beyond the physical/electronic distinction made by the classes, other important distinctions need to be made. One reasonably might ask, "Still, what _kind_ of address are we talking about?" These additional distinctions are to be handled using categories (i.e., instances of `gist:Category`).
```

We are no longer using the term "CBox."

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +gist v13.0.0 supplies three "starter" categories for distinguishing addresses.
```suggestion
gist v13.0.0 supplies three "starter" category classes for distinguishing addresses.
```

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +However, in keeping with our self-imposed rules around the gistCore ontology, we do not supply member instances of those classes as part of the gist release. But fear not. This document will provide
```suggestion
However, in keeping with our self-imposed rules around the `gistCore` ontology, we do not define member instances of those classes. But fear not. This document will provide some concrete suggestions.
```

It's not just the release - it's the ontology itself - e.g., as sitting in GitHub.

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +Every user will need to evaluate how best to categorize their address instances to suit their context. In many cases, this may be influenced by legacy system data. Often, there are implicit distincti
```suggestion
Every user will need to evaluate how best to categorize their address instances to suit their context. In many cases, this may be influenced by legacy system data. Often, there are implicit distinctions made based on column names. Too often, there are more distinctions than are truly necessary, based upon old usage. The choice of categories and instances to implement in the knowledge graph should be given careful consideration, and not be chained to outdated or inappropriate concepts.
```

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +Below are some examples we recommend for consideration. (The instance IRIs should use the appropriate domain namespace, not _gist_'s or _example_'s.) But ultimately, the classes and instances must su
```suggestion
Below are some examples we recommend for consideration. (The instance IRIs should use the appropriate domain namespace, not `gist:` or `ex:`.) But ultimately, the classes and instances must suit the user's particular context.
```

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +In addition to the three classes provided within gistCore, we encourage adding ex:PrecedenceType to the domain ontology. In our experience, the combination of these four categories should cover most
This needs a bit of explanation to clarify what precedence means in this case.

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +Rather than assigning an Address instance directly to a person or organization, it is almost certainly more correct to model addresses in a temporal relation with other things and assign the usage an
Add an example of what exactly this would look like.

You could also point out that, e.g., one person's billing address might be another's residence address.

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +Because gist:Address and its subclasses are subclasses of gist:Content, it does not make semantic sense to say that an address "is contained in a georegion". However, it does make sense to say that t
```suggestion
Because `gist:Address` and its subclasses are subclasses of `gist:Content`, it does not make semantic sense to say that an address "is contained in a georegion". However, it does make sense to say that the address "refers to something". That "something" can be a geo-point (with a very specific latitude & longitude), a city, state, or country, a postal zone, or some custom-defined area. Hence, we do not assign a range to the gist:refersTo property (and it can be used outside the context of addresses as well).
```

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +In the case of some electronic address types (e.g., email addresses), one might choose not to use the gist:references property, at all.
Well, one might always choose _not_ to use `gist:refersTo` at all - there are many use cases that won't call for it, which I would point out. You might say that there are some types of addresses (e.g., email addresses) that don't necessarily refer to anything.

2024-06-19 15:58 UTC, rjyounes commented on docs/AddressGuidance.md
> +There are arguments for and against treating typographical variants of an address (e.g., _"Street"_ vs "_St"_, _"Avenue"_ vs _"Ave"_) as different individuals and assigning them different IRIs. The d
```suggestion
There are arguments for and against treating typographical variants of an address (e.g., _"Street"_ vs "_St"_, _"Avenue"_ vs _"Ave"_) as different individuals and assigning them different IRIs, or perhaps using the same `Address` object with multiple `containedText` values. The decision of which paradigm to employ must be decided with each new ontology and knowledge graph. Semantic Arts makes no recommendation.
```

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "EXAMPLE: A PO Box or a Web URL to a PDF file."^^xsd:string ;
```suggestion
	skos:example "A PO Box, a URL to a PDF file."^^xsd:string ;
```

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A categorization of the context or manner in which an address may be used."^^xsd:string ;
How does content come into play? It's specifically the _usage_ that's being addressed.

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A categorization of the context or manner in which an address may be used."^^xsd:string ;
You should also say "in which an address is used in a particular context." Not "may be used" - the whole point is we want to say how this address is being used by this particular person/organization (billing, residence, etc). In general a street address could have myriad uses.

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "EXAMPLES: a file directory, a website, an IP address."^^xsd:string ;
```suggestion
	skos:example "A path to a file in a file system, a website, an IP address."^^xsd:string ;
```

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A categorization of virtual electronic addresses based, usually, upon the technology that enables routing to the address referent."^^xsd:string ;
I like Michael's version except cut "virtual." This is just an alternate term for "electronic," as we're using it, so it's redundant.

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "Content referring to a locatable place within the material, physical universe."^^xsd:string ;
I like Michael's version but cut "material." Again, it's just redundant.

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A categorization of physical addresses based upon local customary characterizations."^^xsd:string ;
As Michael has suggested previously: "A category indicating..."

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "Relates the Subject to its physical or electronic address Object."^^xsd:string ;
+1 Michael's version, except add "to" after "something."

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "The street address of a building. The email address of a person."^^xsd:string ;
```suggestion
	skos:example "The street address of a building; the email address of a person."^^xsd:string ;
```

2024-06-19 15:58 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "The Subject points to, indicates, or references the Object."^^xsd:string ;
```suggestion
	skos:definition "Relates something to another resource that it points to, indicates, or references.^^xsd:string ;
	skos:example "A US street address refers to a building number, street, city, state, and postal code."
```

I'd like to add an example from another domain - something like "A history book refers to actual people and events," but this is awkward phrasing. 

Note: The "Subject...Object" pattern is not one we've adopted in gist for definitions, and moreover we would not capitalize them.

2024-06-19 15:59 UTC, kchastain703 commented on docs/AddressGuidance.md
> +- ex:\_PrecedenceType_non_primary
Oh, Dan's further recommendation is to add `PrecedenceType` in the domain ontology:
> In addition to the three classes provided within gistCore, we encourage adding ex:PrecedenceType to the domain ontology. In our experience, the combination of these four categories should cover most addresses.

2024-06-19 15:59 UTC, rjyounes commented
Aside from all the small comments, the major comment is that this doc belongs in `gist-doc`, and what was promised here was a narrative migration guide.

2024-06-19 16:28 UTC, kchastain703 commented on docs/AddressGuidance.md
> +In the case of some electronic address types (e.g., email addresses), one might choose not to use the gist:references property, at all.
Updated

2024-06-19 16:29 UTC, kchastain703 commented on docs/AddressGuidance.md
> +- gist:\ElectronicMessageAddress
These should all be fixed now

2024-06-19 16:36 UTC, kchastain703 commented on ontologies/gistCore.ttl
> +	skos:definition "A categorization of the context or manner in which an address may be used."^^xsd:string ;
Fixed

2024-06-19 16:41 UTC, kchastain703 commented on ontologies/gistCore.ttl
> +	skos:example "EXAMPLES: a file directory, a website, an IP address."^^xsd:string ;
Fixed

2024-06-19 16:43 UTC, kchastain703 commented on ontologies/gistCore.ttl
> +	skos:definition "A categorization of virtual electronic addresses based, usually, upon the technology that enables routing to the address referent."^^xsd:string ;
Fixed

2024-06-19 16:48 UTC, kchastain703 commented on docs/AddressGuidance.md
> +The formal restriction definition for gist:PhysicalAddress is "gist:Address and (gist:refersTo some gist:Place)". In other words, a physical address exists in the real, physical world. It is possible
Fixed

2024-06-19 16:49 UTC, kchastain703 commented on docs/AddressGuidance.md
> +| **Pattern Set 2** | gist:ElectronicAddress | gist:containedText | xsd:string |
Fixed

2024-06-19 17:00 UTC, kchastain703 commented on docs/AddressGuidance.md
> +# New Patterns for Using gist:Address
@DanCarey404 is OOO until July 5th, so I'll be going through these. I believe he will still be checking Teams, though, so I'll try to take care of all that I can myself, and pass along daily only what most requires his input.

2024-06-19 18:17 UTC, kchastain703 commented on docs/AddressGuidance.md
> +# New Patterns for Using gist:Address
Alright, so I should remove the AddressGuidance.md file completely from `gist/docs`, and create a new branch for it on `gist-doc`?

2024-06-19 20:27 UTC, uscholdm requested changes
Aside from moving the .md file to gist docs, Im good with this PR.

2024-06-19 20:27 UTC, uscholdm commented on docs/AddressGuidance.md
> +# New Patterns for Using gist:Address
> Alright, so I should remove the AddressGuidance.md file completely from `gist/docs`, and create a new branch for it on `gist-doc`?

That seems to be the right thing to do.

2024-06-19 20:27 UTC, uscholdm commented on docs/AddressGuidance.md
> +# New Patterns for Using gist:Address
@rjyounes 
> In the `gist-doc` documentation, I would just describe the model itself without justifying or explaining the changes relative to previous versions.

I see this differently. I find it very helpful when people explain what they are doing and why. I agree there should be a minimum of that in gist proper, but Im in favor of putting such details in gist-docs

2024-06-19 20:27 UTC, uscholdm commented on docs/AddressGuidance.md
> +However, in keeping with our self-imposed rules around the gistCore ontology, we do not supply member instances of those classes as part of the gist release. But fear not. This document will provide
@kchastain703 I'm assuming that you will commit these suggestions in due course as well as giving the thumbs up

2024-06-19 21:12 UTC, uscholdm commented on docs/AddressGuidance.md
> +- ex:\_PrecedenceType_non_primary
> Do you think we should add this in as `PrecedenceType` or as `AddressPrecedenceType`?

Hmm, good question.  Not sure. THere could be more than one variation of precendence type, address just being one. Lets leave it for now as PrecedenceType, since its generic, more appropriately for gist.

2024-06-19 21:56 UTC, kchastain703 commented on docs/AddressGuidance.md
> +However, in keeping with our self-imposed rules around the gistCore ontology, we do not supply member instances of those classes as part of the gist release. But fear not. This document will provide
Yes, sorry, I was using the thumbs-up as  as checklist for myself, too.

2024-06-24 13:58 UTC, rjyounes commented on docs/release_notes/pr1106.md
> +		- `gist:PhysicalAddressType`
```suggestion
- Major refactoring of Address representation. Issue [#1060].
  - The following classes and properties have been removed: 
    - `gist:ElectronicMessageAddress`
    - `gist:EmailAddress`
    - `gist:PostalAddress`
    - `gist:StreetAddress`
    - `gist:TelephoneNumber`
    - `gist:hasAddress`
    - `gist:hasCommunicationAddress`
  - Added the following classes: 
    - `gist:ElectronicAddress`
    - `gist:PhysicalAddress`
 - Added three subclasses of `gist:Category` for characterizing new addresses:
   - `gist:AddressUsageType`
   - `gist:ElectronicAddressType`
   - `gist:PhysicalAddressType`
 - Added the object property `gist:refersTo`.
```

2024-06-24 14:02 UTC, rjyounes requested changes

2024-06-24 14:02 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A category indicating local customary characterizations of physical addresses."^^xsd:string ;
This definition means nothing to me. Please clarify and add some clarifying examples.

2024-06-24 14:02 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "A brick-and-mortar store has a street address. A person can be reached electronically by their email address."^^xsd:string ;
```suggestion
	skos:example "A brick-and-mortar store has a street address. A person can be contacted electronically via an email address."^^xsd:string ;
```

2024-06-24 14:04 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "A path to a file in a file system, a website, an IP address."^^xsd:string ;
```suggestion
	skos:example "A path to a file in a file system, a website, an IP address, an email address."^^xsd:string ;
```

2024-06-24 14:05 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:prefLabel "Electronic Address Type"^^xsd:string ;
```suggestion
	skos:prefLabel "Electronic Address Type"^^xsd:string ;
	skos:example "A URL, file system path, email address."^^xsd:string ;
```

2024-06-24 14:06 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "An address that refers to a locatable place within the physical universe."^^xsd:string ;
```suggestion
	skos:definition "An address that refers to a locatable place within the physical universe."^^xsd:string ;
	skos:example "A street address, a PO box number."
```

2024-06-24 14:06 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:prefLabel "Physical Address Type"^^xsd:string ;
```suggestion
	skos:prefLabel "Physical Address Type"^^xsd:string ;
	skos:example "Street address, postal address."
```

2024-06-24 14:09 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A category indicating local customary characterizations of physical addresses."^^xsd:string ;
```suggestion
	skos:definition "A category indicating kinds of physical addresses."^^xsd:string ;
```

2024-06-24 14:12 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A reference to a place (real or virtual) that can be located by some routing algorithm, and where messages or things can be sent to or received from."^^xsd:string ;
```suggestion
	skos:definition "A reference to a place (real or virtual) that can be located by some routing algorithm and where messages or things can be sent to or received from."^^xsd:string ;
```

2024-06-24 14:14 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A category indicating a kind of virtual electronic address. Such a category is usually based on the technology that enables routing to the address referent."^^xsd:string ;
```suggestion
	skos:definition "A category indicating a kind of electronic address. Such a category is usually based on the technology that enables routing to the address referent."^^xsd:string ;
```

2024-06-24 16:00 UTC, uscholdm approved these changes

2024-06-24 20:16 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "Billing, business, personal, postal, residence."^^xsd:string ;
```suggestion
	skos:example "Billing, business, personal, postal, residence."^^xsd:string ;
	skos:scopeNote "If you are using temporal relations involving addresses, this category should be used on the temporal relation rather than directly on the address itself, since the same address may have different uses in different contexts."^^xsd:string ;
```

2024-06-24 21:18 UTC, rjyounes approved these changes

2024-06-24 21:29 UTC, merged

2024-06-25 21:16 UTC, uscholdm commented on docs/release_notes/pr1106.md
> +    - `gist:hasAddress`
@rjyounes The `hasAddress` property has NOT been removed.