narrative for new units of measure and magnitudes
semanticarts/gist pull request #1110
Opened 2024-06-25 21:31 UTC by philblackwood

Narrative describing new magnitudes and units of measure. Closes issue #1035

2024-06-26 14:21 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +The release includes scripts for converting data from gist 12 to gist 13, and Semantic Arts will also provide a rich set of reference data for units of measure that can be tapped going forward.
Please include something about what they are supposed to do in the meantime, given we have removed all of the units and conversion.

2024-06-26 14:28 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +- groups of units can be established, where all the units in the group measure the same aspect (for example bit, kilobit, and megabit all measure a quantity of data)
I sugguest using a more common unit in the example. E.g. 
REplace
- `(for example bit, kilobit, and megabit all measure a quantity of data)`
with 
- `(for example foot, meter and kilometer all measure distance)`

2024-06-26 14:31 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +- the units of measure in a group are all multiples of the same product of powers of base units, given as exponent of ampere, exponent of bit, exponent of candela, etc.
```suggestion
- the units of measure in a group are all multiples of the same product of powers of base units, given as exponent of meter, exponent of second, exponent of ampere, etc.

2024-06-26 14:38 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +- there is now one standard way to represent things that previously could be represented multiple ways
Different points:
- They still can be represented in multiple ways, what we are doing is providing an easier approach that allows use of a single way. 
- SA has gone to great lengths to illustrate this, and many of us understand it, but its not at all easy to grok.  Maybe a brief summary here will help with a pointer to the documentation in the migration scripts which spells out these differences.

2024-06-26 14:39 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +- there is now a simple way to validate that a unit of measure is applicable for measuring a given aspect
Can you give a hint as to what this is?

2024-06-26 14:40 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +- calculations can now be done in SPARQL that would be far more complex in gist 12
For example?

2024-06-26 14:42 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +Every member of a unit group containing watt-hour must be a multiple of kilogram meter squared per second squared. The unit group containing watt-hour would also contain kilowatt-hour, for example.
```suggestion
Every member of a unit group containing watt-hour must be a multiple of kilogram meter squared per second squared. The unit group containing watt-hour might also contain kilowatt-hour, for example.

2024-06-26 14:43 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +Reminder: calculations involving the exponents can be done as follows:
I don't think its a reminder

```suggestion
Calculations involving the exponents can be done as follows:

2024-06-26 15:40 UTC, kchastain703 commented on docs/release_notes/issue1035-uom-narrative.md
> +Every member of a unit group containing watt-hour must be a multiple of kilogram meter squared per second squared. The unit group containing watt-hour would also contain kilowatt-hour, for example.
I think "would" works here in the sense that, conceptually, kilowatt-hour would be in the same unit group whether the user is defining/using it or not. And if they are using kilowatt-hour, it's a definite, concrete example of the unit group it does belong to.

2024-06-26 17:31 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +The release includes scripts for converting data from gist 12 to gist 13, and Semantic Arts will also provide a rich set of reference data for units of measure that can be tapped going forward.
The description of the conversion process talks about how an Enterprise can get a standard set of units and aspects from the Semantic Arts reference data.

2024-06-26 17:33 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +## Simple example
The information I could find about this talks about creating a separate repository for images and then using relative path names. The discussions get pretty involved about pros and cons, so until we adopt a standard practice for doing this I am not confident I know the implications.

2024-06-26 17:33 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +- groups of units can be established, where all the units in the group measure the same aspect (for example bit, kilobit, and megabit all measure a quantity of data)
done

2024-06-26 17:33 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +- the units of measure in a group are all multiples of the same product of powers of base units, given as exponent of ampere, exponent of bit, exponent of candela, etc.
done

2024-06-26 17:34 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +- there is now one standard way to represent things that previously could be represented multiple ways
done

2024-06-26 17:34 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +- there is now a simple way to validate that a unit of measure is applicable for measuring a given aspect
done

2024-06-26 17:34 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +- calculations can now be done in SPARQL that would be far more complex in gist 12
the examples are in the following sections

2024-06-26 17:35 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +Every member of a unit group containing watt-hour must be a multiple of kilogram meter squared per second squared. The unit group containing watt-hour would also contain kilowatt-hour, for example.
omitted the reference to kilowatt-hours.

2024-06-26 17:35 UTC, philblackwood commented on docs/release_notes/issue1035-uom-narrative.md
> +Reminder: calculations involving the exponents can be done as follows:
removed "Reminder"

2024-06-26 18:40 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +The release includes scripts for converting data from gist 12 to gist 13, and Semantic Arts will also provide a rich set of reference data for units of measure that can be tapped going forward.
Yes, but noone has access to that data at this time. What do we recommend they do for the time being?

2024-06-26 18:42 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +## Simple example
Yeah, they way github does all that magic behind the scenes is remarkable. We'll drop this.

2024-06-26 18:43 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +- calculations can now be done in SPARQL that would be far more complex in gist 12
ok

2024-06-26 18:49 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +Every member of a unit group containing watt-hour must be a multiple of kilogram meter squared per second squared. The unit group containing watt-hour would also contain kilowatt-hour, for example.
ok

2024-06-26 18:51 UTC, uscholdm commented on docs/release_notes/issue1035-uom-narrative.md
> +- there is now a simple way to validate that a unit of measure is applicable for measuring a given aspect
I just looked at the commit changes and did not see an added hint. Can you point it out?

2024-07-02 22:49 UTC, rjyounes requested changes

2024-07-03 16:19 UTC, rjyounes approved these changes

2024-07-03 16:19 UTC, merged