Remove `actualStartDateTime` and `actualEndDateTime` restrictions from `TimeInterval`
semanticarts/gist pull request #1111
Opened 2024-06-27 01:28 UTC by dylan-sa

This PR reverts changes made in #1092, which included the addition of `actualStartDateTime` and `actualEndDateTime` restrictions on `TimeInterval`. 

While these restrictions initially seemed plausible after discussion in #925, the definitions of these predicates are phrased in the past tense, meaning they aren't a good fit for future time intervals. More discussion needed.

2024-06-27 01:28 UTC, dylan-sa commented on docs/release_notes/1046-TimeInterval-TemporalRelation.md
> +- Added `gist:Duration` restrictions to the formal definition of `gist:TimeInterval`. Issue [#925](https://github.com/semanticarts/gist/issues/925).
```suggestion
- Added `gist:Duration` restriction to the formal definition of `gist:TimeInterval`. Issue [#925](https://github.com/semanticarts/gist/issues/925).
```

2024-06-27 14:12 UTC, uscholdm approved these changes
Looks good.

2024-06-27 16:30 UTC, dylan-sa commented
@uscholdm @rjyounes -- I've updated this PR based on our discussion in the development team meeting today. Ready for another look when you get the chance.

2024-06-27 16:33 UTC, dylan-sa commented on ontologies/gistCore.ttl
>  		"We have looked at some extreme edge cases (e.g., did this meeting end before or after the trade was posted?) and we couldn't find any use case that required special processing. Those who have such
FWIW, I find this annotation about edge cases to be confusing. I wonder if there is a way we can clarify this while we are updating the annotations here?

2024-06-27 20:51 UTC, uscholdm requested changes
I made annotations simpler, two identical suggestions.

2024-06-27 20:51 UTC, uscholdm commented on ontologies/gistCore.ttl
> +		"This property is neutral along two dimensions: precision of time (e.g., day, second, millisecond) and perspective on actual vs. planned. For this reason, it is not expected to be asserted directly
```suggestion
		"This property is neutral along two dimensions: time precision (e.g., day, second, millisecond) and perspective on actual vs. planned. As such, it will generally not be asserted directly except in special cases (e.g. for time intervals)."^^xsd:string ,

2024-06-27 20:51 UTC, uscholdm commented on ontologies/gistCore.ttl
> +		"This property is neutral along two dimensions: precision of time (e.g., day, second, millisecond) and perspective on actual vs. planned. For this reason, it is not expected to be asserted directly
```suggestion
		"This property is neutral along two dimensions: time precision (e.g., day, second, millisecond) and perspective on actual vs. planned. As such, it will generally not be asserted directly except in special cases (e.g. for time intervals)."^^xsd:string ,

2024-06-28 20:18 UTC, rjyounes requested changes

2024-06-28 20:18 UTC, rjyounes commented on ontologies/gistCore.ttl
> +		"This property is neutral along two dimensions: precision of time (e.g., day, second, millisecond) and perspective on actual vs. planned. For this reason, it is not expected to be asserted directly
I like Michael's wording but would omit "perspective on." I think "actual vs. planned" makes the point. I would also omit "time" in front of precision - it's precision generally, both of date and time.

2024-06-28 20:18 UTC, rjyounes commented on ontologies/gistCore.ttl
> +		"Values with different precisions can be compared since they all have the same format."^^xsd:string ,
Does this work?

```suggestion
		"Values of predicates with different precisions can be compared since they are all formally xsd:datatimes."^^xsd:string ;
```

We should update it wherever it occurs, which I assume is in multiple places.

2024-06-28 20:18 UTC, rjyounes commented on ontologies/gistCore.ttl
> +		"This property is neutral along two dimensions: precision of time (e.g., day, second, millisecond) and perspective on actual vs. planned. For this reason, it is not expected to be asserted directly
Same comment as above.

2024-06-28 20:18 UTC, rjyounes commented on ontologies/gistCore.ttl
> +		"Values with different precisions can be compared since they all have the same format."^^xsd:string ,
Same proposal as above.

2024-06-28 20:40 UTC, dylan-sa commented on ontologies/gistCore.ttl
> +		"Values with different precisions can be compared since they all have the same format."^^xsd:string ,
Got it

2024-06-28 20:42 UTC, dylan-sa commented
@uscholdm @rjyounes -- Thank you for the reviews--I have incorporated your feedback and pushed the updates.

2024-07-01 15:03 UTC, rjyounes requested changes

2024-07-01 15:03 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "The date and time that something ends."^^xsd:string ;
I think we should leave this in the past tense, since most of the other planned and actual predicates are. As we are using the word "actual," it implies "past."

2024-07-01 15:21 UTC, uscholdm approved these changes
Make the change requested by Rebecca about actualEndMicrosecond 'ended' vs. 'ends'..

2024-07-01 21:05 UTC, dylan-sa commented on ontologies/gistCore.ttl
> +	skos:definition "The date and time that something ends."^^xsd:string ;
@rjyounes @uscholdm  -- There is some weirdness with the GitHub diffs here. This change is actually for `gist:endDateTime`, not `gist:actualEndMicrosecond`. 'Ends' in the case of `endDateTime` seems appropriate, given that it's neutral on actual vs. planned, right?

2024-07-01 21:31 UTC, uscholdm approved these changes

2024-07-02 14:47 UTC, rjyounes approved these changes

2024-07-02 14:47 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "The date and time that something ends."^^xsd:string ;
Yes, that's right.

2024-07-02 14:47 UTC, merged