Address guidance
semanticarts/gist pull request #1114
Opened 2024-06-27 23:14 UTC by kchastain703

Guidance documentation file for Addresses added back to this repo, resolves #1109

2024-07-01 15:09 UTC, uscholdm requested changes
One small change.

2024-07-01 15:09 UTC, uscholdm commented on docs/model_documentation/AddressGuidance.md
> +Rather than assigning an Address instance directly to a person or organization, it is almost certainly more correct to model addresses in a temporal relation with other things and assign the usage an
```suggestion
Rather than assigning an Address instance directly to a person or organization, it is often more useful to model addresses in a temporal relation with other things and assign the usage and precedence categories to the relationship instance. For example, a particular address might start out being used as _both_ a residence and a postal address. But at some point, the addressee decides to rent a PO Box to use for their postal address instead. In other cases, one single address may be used as a billing address by one person, and as a residence address for another person.

2024-07-01 17:43 UTC, rjyounes requested changes

2024-07-01 17:43 UTC, rjyounes commented on docs/model_documentation/AddressGuidance.md
> +Because `gist:Address` and its subclasses are subclasses of `gist:Content`, it does not make semantic sense to say that an address "is contained in a georegion". However, it does make sense to say th
```suggestion
Because `gist:Address` and its subclasses are subclasses of `gist:Content`, it does not make semantic sense to say that an address "is contained in a geo-region". However, it does make sense to say that the address "refers to something." That "something" can be a geo-point (with a specific latitude & longitude), a city, state, or country, a postal zone, or some custom-defined area. Hence, we do not assign a range to the `gist:refersTo` property (and it can be used outside the context of addresses as well).
```

2024-07-01 17:43 UTC, rjyounes commented on docs/model_documentation/AddressGuidance.md
> +In the case of some electronic address types (e.g., email addresses), one might choose not to use the `gist:refersTo property`, at all.
```suggestion
In the case of some electronic address types (e.g., email addresses), one might choose not to use the `gist:refersTo` property at all. And, of course, your use cases need not require the `gist:refersTo` assertions for physical ddresses, either.
```

2024-07-01 17:43 UTC, rjyounes commented on docs/model_documentation/AddressGuidance.md
> +An important point to bear in mind is that an address string might not _explicitly_ refer to a country (e.g., "1313 Mockingbird Ln, Munster, IN"). But it _implicitly_ refers to it. In the example, th
```suggestion
An important point to bear in mind is that an address string might not _explicitly_ refer to a country (e.g., "1313 Mockingbird Ln, Munster, IN"). But it _implicitly_ refers to it. In the example, the address implies the USA because Indiana is part of the US. So, it is perfectly acceptable to have a triple asserting that the address refers to the IRI for the country even when the address string lacks it.
```

2024-07-01 17:43 UTC, rjyounes commented on docs/model_documentation/AddressGuidance.md
> +There are arguments for and against treating typographical variants of an address (e.g., _"Street"_ vs _"St"_, _"Avenue"_ vs _"Ave"_) as different individuals and assigning them different IRIs, or pe
```suggestion
There are arguments for and against treating typographical variants of an address (e.g., _"Street"_ vs _"St"_, _"Avenue"_ vs _"Ave"_) as different individuals and assigning them different IRIs, or using the same `Address` object with multiple `containedText` values. This decision should be made based on your use cases. Semantic Arts makes no recommendation.
```

2024-07-01 20:57 UTC, uscholdm approved these changes

2024-07-01 20:59 UTC, uscholdm commented on docs/model_documentation/AddressGuidance.md
> +The `gist:ElectronicAddress` class has no formal restriction definition. But it does have a text definition: _"_ _Content referring to a locatable virtual place not physically existing, as such, but
I agree.  You could also remove the redundant: "one cannot touch it".

2024-07-01 21:00 UTC, uscholdm commented on docs/model_documentation/AddressGuidance.md
> +In gist v13.0.0, we introduced a new paradigm for modeling addresses. The new method is simpler and should result in more consistent instance data.
Good point, I wondered about that too. A change along the lines you suggest is a good idea.

2024-07-02 22:32 UTC, rjyounes requested changes

2024-07-02 22:32 UTC, rjyounes commented on docs/model_documentation/AddressGuidance.md
> +In gist v13.0.0, we introduced a new paradigm for modeling addresses. The new method is simpler and more accurate and expressive.
```suggestion
In gist v13.0.0, we introduced a new paradigm for modeling addresses. The new method is both more accurate and more expressive.
```

2024-07-02 22:32 UTC, rjyounes commented on docs/model_documentation/AddressGuidance.md
> +In the case of some electronic address types (e.g., email addresses), one might choose not to use the `gist:refersTo` property at all. And, of course, your use cases need not require the `gist:refers
```suggestion
In the case of some electronic address types (e.g., email addresses), one might choose not to use the `gist:refersTo` property at all. And, of course, your use cases need not require the `gist:refersTo` assertions for physical addresses either.
```

2024-07-02 22:33 UTC, rjyounes approved these changes

2024-07-02 22:33 UTC, merged