non-uom data conversion scripts
semanticarts/gist pull request #1116
Opened 2024-06-30 16:54 UTC by philblackwood

Data conversion scripts for non-uom changes. Closes issue #1091.

2024-07-01 11:10 UTC, sa-bpelakh commented
@philblackwood  I will add the bundle drivers directly into this PR, if that's OK. I don't think you need to do the named graph exclusion on the default graph queries because the pattern should already have been transformed there.

2024-07-01 15:13 UTC, rjyounes requested changes

2024-07-01 15:13 UTC, rjyounes commented on migration/v13.0/queries/replaceHasCommunicationAddress1.rq
> +# replace gist:hasCommunicationAddress in named graphs with gist:hasAddress
Phil, can't we include the `hasAddress/hasCommunicationAddress` replacement in the general `renameProperties` files and eliminate the two additional files?

2024-07-01 15:19 UTC, philblackwood commented on migration/v13.0/queries/replaceHasCommunicationAddress1.rq
> +# replace gist:hasCommunicationAddress in named graphs with gist:hasAddress
yes! I will update the renameProperties scripts to include the pair:

oldProperty: gist:hasCommunicationAddress

newProperty: gist:hasAddress.

2024-07-01 15:35 UTC, philblackwood commented
From Boris:  I don't think you need to do the named graph exclusion on the default graph queries because the pattern should already have been transformed there."

me: I think it's OK to leave it in. The scenario where it helps is:

   - user runs first script to make changes in named graph, then puts the data conversion aside for a while
   -  new changes are made in the named graph
   -  user returns to data conversion, runs second script which results in named graph triples removed and their replacement incorrectly gets added to the default graph.

I looked at making the change, and it is big enough (and my typing bad enough) to warrant a re-test, which I would prefer not to have to do.

Are you OK with leaving it in?

2024-07-01 15:37 UTC, philblackwood commented
@sa-bpelakh "I will add the bundle drivers directly into this PR, if that's OK."

phil: yes, certainly.

2024-07-02 18:39 UTC, philblackwood commented
Adding data conversion for deprecating hasSuperCategory and its sub properties.

2024-07-02 22:28 UTC, rjyounes commented
@philblackwood @sa-bpelakh Is this ready to go? It needs to be updated with `develop`.

2024-07-03 16:18 UTC, rjyounes requested changes

2024-07-03 16:18 UTC, rjyounes commented on migration/v13.0/non-uomDataConversion.md
> +The different types and uses of addresses can be modeled as categories.
```suggestion
The different types and uses of addresses can be modeled as categories; see [the address migration documentation(AddressMigration.md) as well as the [full documentation of the new address model](/docs/model_documentation/AddressGuidance.md).
```

2024-07-03 16:18 UTC, merged