Document manual steps in address migration
semanticarts/gist pull request #1117
Opened 2024-07-01 15:20 UTC by rjyounes

Closes #1109.

Note: Cannot be merged until PR #1114 is merged so links can be added from this document to that one.

2024-07-01 15:36 UTC, uscholdm requested changes
This is excellent! Some minor tweaks.

2024-07-01 15:36 UTC, uscholdm commented on migration/v13.0/AddressMigration.md
> +gist 13.0.0 introduces a new model of physical and electronic addresses (see [xxx] for full documentation of the model). Because the new model shifts a large part of the semantics from classes to use
Replace `xxx`. It also documents automated portion.

```suggestion
gist 13.0.0 introduces a new model of physical and electronic addresses (see [xxx] for full documentation of the model). Because the new model shifts a large part of the semantics from classes to user-defined categories, the migration can be only partially automated. This guide documents the steps required to migrate your data and ontology extensions into the new model without loss of meaning.

2024-07-01 16:43 UTC, rjyounes commented on migration/v13.0/AddressMigration.md
> +gist 13.0.0 introduces a new model of physical and electronic addresses (see [xxx] for full documentation of the model). Because the new model shifts a large part of the semantics from classes to use
Well, the automated steps are also mentioned.

2024-07-02 15:20 UTC, rjyounes commented
Waiting to merge till after #1114 is merged to check that links work.

2024-07-02 22:34 UTC, rjyounes commented on migration/v13.0/AddressMigration.md
> +gist 13.0.0 introduces a new model of physical and electronic addresses (see [full documentation of the model](docs/model_documentation/AddressGuidance.md)). Because the new model shifts a large part
```suggestion
gist 13.0.0 introduces a new model of physical and electronic addresses (see [full documentation of the model](/docs/model_documentation/AddressGuidance.md)). Because the new model shifts a large part of the semantics from classes to user-defined categories, the migration can be only partially automated. This guide documents the steps required to migrate your data and ontology extensions into the new model without loss of meaning.
```

2024-07-02 22:34 UTC, rjyounes commented on migration/v13.0/AddressMigration.md
> +The new model provides flexibility to express more nuanced types of address usage and communication preferences than has previously been available. Consult the [full documentation of the model](docs/
```suggestion
The new model provides flexibility to express more nuanced types of address usage and communication preferences than has previously been available. Consult the [full documentation of the model](/docs/model_documentation/AddressGuidance.md) to learn how to take advantage of these options.
```

2024-07-02 22:35 UTC, rjyounes commented on migration/v13.0/AddressMigration.md
> +The new model provides flexibility to express more nuanced types of address usage and communication preferences than has previously been available. Consult the [full documentation of the model](docs/
```suggestion
The new model provides flexibility to express more nuanced types of address usage and communication preferences than has previously been available. Consult the [full documentation of the model](/docs/model_documentation/AddressGuidance.md) to learn how to take advantage of these options.
```

2024-07-02 22:54 UTC, dylan-sa requested changes
One question about the links. Otherwise looks good to me.

2024-07-02 22:54 UTC, dylan-sa commented on migration/v13.0/AddressMigration.md
> +gist 13.0.0 introduces a new model of physical and electronic addresses (see [full documentation of the model](/docs/model_documentation/AddressGuidance.md)). Because the new model shifts a large par
@rjyounes -- This link did not work when I tried it -- is AddressGuidance.md located elsewhere?

2024-07-02 22:54 UTC, dylan-sa commented on migration/v13.0/AddressMigration.md
> +The new model provides flexibility to express more nuanced types of address usage and communication preferences than has previously been available. Consult the [full documentation of the model](/docs
Same question about link here

2024-07-02 22:55 UTC, dylan-sa approved these changes

2024-07-02 22:56 UTC, dylan-sa commented on migration/v13.0/AddressMigration.md
> +gist 13.0.0 introduces a new model of physical and electronic addresses (see [full documentation of the model](/docs/model_documentation/AddressGuidance.md)). Because the new model shifts a large par
Now I see it there--you can disregard this question

2024-07-02 22:59 UTC, rjyounes commented on migration/v13.0/AddressMigration.md
> +gist 13.0.0 introduces a new model of physical and electronic addresses (see [full documentation of the model](/docs/model_documentation/AddressGuidance.md)). Because the new model shifts a large par
Yeah, it didn't work until I merged develop into this branch.

2024-07-02 23:00 UTC, merged