issue1124-migrationREADME
semanticarts/gist pull request #1129
Opened 2024-07-11 21:52 UTC by philblackwood

Add README and associated files for gist 13 data conversion. Closes issue #1124

2024-07-12 13:16 UTC, sa-bpelakh requested changes
Need to test bundle changes.

2024-07-12 13:16 UTC, sa-bpelakh commented on bundle.yaml
> +- action: "move"
Was this tested, @philblackwood ? If the sources include `*.html`, and the rename is from `*.md`->`*.html`, I don't think you will get the desired result.

2024-07-12 13:16 UTC, sa-bpelakh commented on docs/ReleaseNotes.md
> +    | gist 12 | gist 13 |
When you test the build, please verify that the table is formatted properly. That HTML conversion can be iffy at times.

2024-07-12 13:16 UTC, sa-bpelakh commented on docs/models/UnitOfMeasureModel.md
> +# New Magnitudes and Units of Measure in gist 13
Is this awesome documentation going to replace the PowerPoint document in the `migration/13.0.0` folder? We would like to avoid large binary files that prevent change tracking in our git repo.

2024-07-12 13:17 UTC, sa-bpelakh commented
@philblackwood  Also, the target of this merge should be the release branch, not develop, right?

2024-07-15 13:39 UTC, rjyounes commented on docs/models/UnitOfMeasureModel.md
> +# New Magnitudes and Units of Measure in gist 13
@philblackwood We can put the powerpoint in gist-doc.

2024-07-15 13:41 UTC, rjyounes commented on bundle.yaml
> +- action: "move"
@sa-bpelakh This is work that Colton and I did. What case are you imagining won't work? We tested it on the existing repo.

2024-07-15 13:44 UTC, rjyounes requested changes
@philblackwood This PR should be made against the release branch, not develop. You can change it by clicking Edit at the top to the right of the title and changing the base branch.

2024-07-15 19:22 UTC, rjyounes requested changes
A couple of minor wording tweaks.

2024-07-15 19:22 UTC, rjyounes commented on migration/v13.0/README.md
> +> See also additional documentation in the file `docs/MajorVersionMigration.md`.
```suggestion
> See also additional documentation in the file `../../docs/MajorVersionMigration.md`.
```

2024-07-15 19:22 UTC, rjyounes commented on migration/v13.0/README.md
> +  > triples in the default graph, some will use all triples in all named graphs.
```suggestion
  > `*` the handling of these queries will be dependent upon which triplestore you are using and how it was configured. Some triplestores will only use
  > triples in the default graph, some will use all triples in all named graphs.
```

2024-07-16 01:49 UTC, sa-bpelakh commented on bundle.yaml
> +- action: "move"
I misread `replace` as `rename` and got confused. My apologies.

2024-07-16 15:20 UTC, philblackwood commented
Performed extensive cross-checks of yaml files vs. previous release and queries they use for typos.

As far as I know, this PR is completed and ready to merge (if no dependency on #1131).

2024-07-18 16:03 UTC, rjyounes commented
@philblackwood If you have addressed earlier comments from @sa-bpelakh and me, you need to re-request our review in order to get approvals. (The circular arrows icon next to our names on upper right.)

2024-07-19 17:13 UTC, rjyounes approved these changes

2024-07-19 17:13 UTC, merged