Add range to gist:description
semanticarts/gist pull request #1158
Opened 2024-09-12 20:22 UTC by kstudzin

Closes #1093

2024-09-16 14:56 UTC, rjyounes requested changes
Just need a release note.

2024-09-23 15:36 UTC, uscholdm reviewed
I suggest a scope note along these lines:

- Generally this property will only be used for data instances. Use `skos:defintion` for ontology concepts as well as categories that help to define the subject matter of the ontology.

2024-10-15 15:27 UTC, rjyounes requested changes

2024-10-15 15:27 UTC, rjyounes commented on docs/release_notes/issue1093-description-range.md
> +gist:description now has a range of xsd:string
Please see guidance on formatting release notes.

2024-10-15 15:27 UTC, rjyounes commented
I like Michael's suggestion above for a scope note.

2024-10-15 18:32 UTC, kstudzin commented
Okay - do you see this is as a replacement of the current scope note or an addition?

2024-10-17 15:38 UTC, rjyounes requested changes

2024-10-17 15:38 UTC, rjyounes commented on docs/release_notes/issue1093-description-range.md
> +gist:description now has a range of xsd:string
```suggestion
### Minor Updates

- Added range `xsd:string` to `gist:description`. Issue [#1093](https://github.com/semanticarts/gist/issues/1093).
```

2024-10-17 20:20 UTC, rjyounes approved these changes

2024-10-17 20:20 UTC, merged