Issue #1155 Annotations conform to style guide
semanticarts/gist pull request #1160
Opened 2024-09-17 14:31 UTC by kstudzin

This set of changes focuses on removing excess information from `skos:definition` and moving it to `skos:example` or `skos:scopeNote`. There is also some reformatting of all three annotations. However these changes do not attempt to make `skos:definition` full sentences where they are not. More changes will be added for this.

The definitions most significantly affected by removing examples are `gist:Behavior` and `gist:Content`. `gist:Behavior` maybe falls in the category "Occasionally a definition can hardly be understood at all without an example" of the style guide. My recommendation is that we try to make a more specific, full sentence definition, but we may determine that it is most clear to simply add the example back to the definition.

Our definition of `gist:Content`, in my opinion, was not a definition but rather a list of examples. I attempted to make a new definition, but would appreciate input on if this matches the existing usage. If there is other history on this definition and why we should include examples in the definition, that would also be helpful.

Closes #1155

2024-09-17 18:22 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "The object is a foundation for, a starting point for, gave rise to, or justifies the subject"^^xsd:string ;
```suggestion
	skos:definition "The object is a foundation for, a starting point for, gave rise to, or justifies the subject."^^xsd:string ;
```

2024-09-17 18:24 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "Date that something was posted, not necessarily the date it occurred. Must be after the date of occurrence, but could be before or after the planned date."^^xsd:string ;
```suggestion
	skos:definition "Date that something was posted (which is not necessarily the date it occurred). Must be after the date of occurrence, but could be before or after the planned date."^^xsd:string ;
```

2024-09-17 18:25 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "gist:connectedTo gist:isSupersededBy gist:isConnectedTo (renaming with no semantic change)"^^xsd:string ;
```suggestion
	skos:example "gist:connectedTo was superseded by gist:isConnectedTo (renaming with no semantic change)"^^xsd:string ;
```

2024-09-17 18:27 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:scopeNote "An offer offers a specific product at a particular price."^^xsd:string ;
This should stay as it is - it's an example, not a note about offers generally. The purpose of the example is to show that the predicate can have a `gist:Offer` as subject, as well as the thing making the offer.

2024-09-17 18:27 UTC, rjyounes commented on ontologies/gistCore.ttl
>  	skos:definition "Relates something to a thing that is being made available for acceptance or rejection."^^xsd:string ;
```suggestion
	skos:definition "Relates something to a thing it makes available for acceptance or rejection."^^xsd:string ;
```

2024-09-17 18:28 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "The intention prevents the behavior"^^xsd:string ;
```suggestion
	skos:definition "Relates an intention to behavior that it prevents or prohibits."^^xsd:string ;
```

2024-09-17 18:29 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "Possessing and controlling. Ultimate form of ownership is the right to destroy."^^xsd:string ;
```suggestion
	skos:definition "Relates something to a thing it possesses and controls."^^xsd:string ;
	skos:scopeNote "The ultimate form of ownership is the right to destroy."^^xsd:string ;
```

2024-09-17 19:23 UTC, rjyounes commented on docs/gistStyleGuide.md
> +| `skos:example` | May be either a full sentence, a list, or sample values. Full sentence or list examples should end with a period, e.g., "SSN, driver's license number, employee ID." or "NIH sponsor
I think I meant "single" rather than "sample," since they're all samples.

```suggestion
| `skos:example` | May be either a full sentence, a list, or a single value. Full sentence or list examples should end with a period, e.g., "SSN, driver's license number, employee ID." or "NIH sponsors a research project." Lists with short items, such as the first example, can be delimited by either commas (include Oxford commas) or semi-colons; full-sentence examples should be semi-colon-delimited. Single value examples include `"application/sparql-results+xml"` for `gist:MediaType` and datetime values such as `'2021-06-01T00:00:00-6:00'^^xsd:dateTime` for `gist:actualEndDate`. |
```

2024-09-18 14:42 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:example: "A saw behaves such that it cuts while a drill behaves such that it drills."^^xsd:string ;
I was wondering if we changed the definition, to something along the lines of "The way in which something works or functions," we could improve the definition and leave the example as a `skos:example`. The Oxford definition of behavior is "the way in which a natural phenomenon or a machine works or functions." But perhaps this changes the definition too much?

2024-09-18 15:07 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:example: "A saw behaves such that it cuts while a drill behaves such that it drills."^^xsd:string ;
This is very tricky. It's origin was in manufacturing, hence the drilling/cutting examples. I propose

- A category used to indicate the nature of what is happening during an event.

This can then be separated from the examples.

2024-09-18 15:32 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:definition "An individual point on the Earth's surface, identified by latitude, longitude and altitude. If altitude is missing, it is assumed to be at the Earth's surface. However, altitude is
I agree this definition could be improved because right now it says the point is on the Earth's surface and also if it has an altitude it might not be on the Earth's surface. 

Here is one re-writing attempt:
> An individual point in physical space identified by latitude, longitude and altitude. If altitude is missing, the point is assumed to be at the Earth's surface, and the altitude is the distance measured from sea level.

If we want to remove the word 'Earth' we could say something like:
> An individual point in physical space identified by latitude, longitude and altitude within a geographic coordinate system. If altitude is missing, the point is assumed to be at the planet's surface, and the altitude is the distance measured from the reference sphere.

There is a [NASA whitepaper](https://science.nasa.gov/wp-content/uploads/2024/01/luncoordwhitepaper-10-08.pdf) that discusses lunar coordinates and reference sphere. (Scope note: Earth's reference sphere is sea level.)

If we want to allow a geo point to be on any planet, we can no longer assume WGS 84 and may need an additional property to specify the coordinate system.

2024-09-18 17:00 UTC, kstudzin commented on docs/gistStyleGuide.md
> +| `skos:example` | May be either a full sentence, a list, or sample values. Full sentence or list examples should end with a period, e.g., "SSN, driver's license number, employee ID." or "NIH sponsor
I added sample because I think there is a difference between the following types of examples:
```
gist:actualStartYear skos:example "'2021-01-01T00:00:00-6:00'^^xsd:dateTime"^^xsd:string
gist:allows skos:example  "A grant allows egress."^^xsd:string .
```

The first statement is a sample because you might find a statement with that value in actual data:
```
:_SomeResource gist:actualStartYear '2021-01-01T00:00:00-6:00'^^xsd:dateTime .
```

The second statement is an example but not a sample because you would never find the following in actual data:
```
:_SomeResource gist:allows "A grant allows egress." .
```
 
The difference is that a sample can be used character for character in the data.

I wanted to make this distinction for two reasons:
1. Samples don't need to end in a final period
```
# prefer
gist:actualStartYear skos:example "'2021-01-01T00:00:00-6:00'^^xsd:dateTime"^^xsd:string

# over
gist:actualStartYear skos:example "'2021-01-01T00:00:00-6:00'^^xsd:dateTime."^^xsd:string
```
Because a sample can be used character for character in data, it should not have an addition period that would not be in real data. All other examples should end in a final period. 

2. Term with both examples and samples, should have separate statements for each
```
# prefer
gist:actualStartYear
	skos:example
		"'2021-01-01T00:00:00-6:00'^^xsd:dateTime"^^xsd:string ,
		"The tenure of the current chairman of the board began in 2021."^^xsd:string
		;
# over
gist:actualStartYear
	skos:example
		"'2021-01-01T00:00:00-6:00'^^xsd:dateTime; the tenure of the current chairman of the board began in 2021."^^xsd:string
		;
```
I think lists should maintain parallel structure to make them easy to read and understand. Putting examples and samples together felt hard to read and disorienting.

But perhaps this adds unnecessary complexity

2024-09-18 17:22 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:example "Measuring the sulphur content of crude oil; evaluating a loan application for approval; estimating the price of gas for the next three months; determining whether and by how much an in
It is a good example and I wouldn't necessarily think of it right away. I think I removed it because it's very general while the rest of the list is very specific. Could we add a more specific example about classification? Maybe something like "classifying a purchase into a budget category?" If not, I can add back as is

2024-09-18 18:13 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:scopeNote "An offer offers a specific product at a particular price."^^xsd:string ;
Sounds good. The reason I changed it was because we try to avoid ontology terms in annotations and there are other cases of describing what gist terms are connected in scope notes (but I think those are more definitive use cases than this). Should I restore the original wording or move the new wording back to example?

2024-09-20 23:30 UTC, uscholdm requested changes
Overall this is excellent, a big job and a painstaking one.  I did make a bunch of suggestions.  

Although this exercise was specifically to align definition style, I often gave in to the temptation to fix a bad definition, which might instead have been a separate issue warranting a group.

I made changes for properties to style starting with 'relates'. But there were too many to attempt a fix for all of them.

2024-09-20 23:30 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "Relates a network link to a network node that it connects to another node. Used when the connections are undirected, or the direction is not known."^^xsd:string ;
```suggestion
skos:definition "Relates a network link to one of the two network nodes that it connects. Used when the connections are undirected, or the direction is not known."^^xsd:string ;

2024-09-20 23:30 UTC, uscholdm commented on ontologies/gistCore.ttl
> +		;
Presumably only persons or parties can own something, is that the idea? Be clear about whether this is intended to be legal ownership, what other kind is there that a typical enterprise would care about? Perhaps change the definition to:
- `Relates a party to something that it possesses and controls.`

2024-09-23 19:40 UTC, dylan-sa requested changes
Agree with @uscholdm--this is great. A lot of much needed work. 👍

I've added some things that caught my eye.

2024-09-23 19:40 UTC, dylan-sa commented on ontologies/gistCore.ttl
> +	skos:definition "The parts of a system contribute to the goal/ function of the whole system."^^xsd:string ;
```suggestion
	skos:definition "The parts of a system contribute to the goal/function of the whole system."^^xsd:string ;
```

2024-09-23 20:32 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "A government organization which asserts both sovereignty (i.e., it is not governed by some other government organization) and governance over an entity generally recognized as a cou
Good idea.

2024-09-23 20:33 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "An individual point on the Earth's surface, identified by latitude, longitude, and altitude. If altitude is missing, it is assumed to be at the Earth's surface. However, altitude is
I agree.

2024-09-23 22:30 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:definition "Something that is currently, or at some point in time was or will be, alive."^^xsd:string ;
The `gist:birthDate` definition says that 'The date some living thing was or will be born' so I thought it only makes sense if there are living things that are not yet born

2024-09-24 14:08 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:example "A path to a file in a file system; a website URL; an IP address; an email address; a mobile or landline telephone number."^^xsd:string ;
The style guide says that short examples should use commas and long examples should use semi colons. I judged this to be long examples because 'A path to a file in a file system' and, to a lesser degree, 'a mobile or landline telephone number' are more complex than the short '<article> <optional adjective> <noun>' structure. I can change the first example to 'A filesystem path,' which is a better parallel to the other examples, and use commas

2024-09-24 14:56 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:definition "An annotation for providing the licensing on this or derivative ontologies."^^xsd:string ;
This seems related to #682 and #977 

Either way, we could change the definition to be more generic: "Relates something to its license." And we could add ontologies and software as examples. Are there other examples we should include?

2024-09-24 15:06 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:scopeNote "Assume coordinate system used by Google (WGS 84 Web Mercator using the GPS decimal lat/long)."^^xsd:string ;
I think too much was removed. Feel free to reorder the sentences or put into two separate scope notes. I cannot decide on a preference.

```suggestion
skos:scopeNote "If altitude is missing, it is assumed to be at the Earth's surface. However, altitude is measured from sea level. Assume coordinate system used by Google (WGS 84 Web Mercator using the GPS decimal lat/long)."^^xsd:string ;

If altitude is missing, it is assumed to be at the Earth's surface. However, altitude is measured from sea level.

2024-09-24 15:18 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "An annotation for providing the licensing on this or derivative ontologies."^^xsd:string ;
I like `Relates something to its license.` .Let's make that change for now and save other changes for the cited issues.

2024-09-24 17:13 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:definition "A work, invention or concept existing as tacit knowledge, know-how, or skill or expressed in text, audio, video, image, or live performance."^^xsd:string ;
I agree the idea that IP doesn't need to be expressed is important. I tried to keep that conceptually in the definition in two ways:

    Emphasizing that IP is often tacit knowledge, and therefore not expressed, by moving that phrase early in the definition
    Providing options, either A or B. In this definition, IP is independent of being expressed because it could only exist tacitly.

What are your thoughts on if this approach?

2024-09-24 17:55 UTC, kstudzin commented on ontologies/gistCore.ttl
> +		"Across the world there are a variety of types of subsections of a country and the governments thereof (as well as different terms, like 'province' and 'state,' which refer to essentially the same
MLA Handbook and Chicago Manual of Style both recommend commas inside quotation marks. MLA posted [this](https://style.mla.org/punctuation-and-quotation-marks/) summary of opinions. They note that British style uses single quotes with commas outside.

2024-09-24 18:37 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "A work, invention or concept existing as tacit knowledge, know-how, or skill or expressed in text, audio, video, image, or live performance."^^xsd:string ;
Now I get it, good explanation, we can go with this.

2024-09-24 18:40 UTC, uscholdm commented on ontologies/gistCore.ttl
> +		"Across the world there are a variety of types of subsections of a country and the governments thereof (as well as different terms, like 'province' and 'state,' which refer to essentially the same
What a shame, let's go to the UK! :-)

2024-09-24 20:51 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:definition "An individual point on the Earth's surface, identified by latitude, longitude and altitude. If altitude is missing, it is assumed to be at the Earth's surface. However, altitude is
@uscholdm Do you have thoughts on either of these definitions?

2024-09-24 20:53 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:scopeNote "Assume coordinate system used by Google (WGS 84 Web Mercator using the GPS decimal lat/long)."^^xsd:string ;
Yes it does look like too much was removed. There's a larger discussion [here](https://github.com/semanticarts/gist/pull/1160#discussion_r1774079970) that I also just tagged you in

2024-09-25 14:17 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:definition "An individual point on the Earth's surface, identified by latitude, longitude and altitude. If altitude is missing, it is assumed to be at the Earth's surface. However, altitude is
> An individual point in physical space identified by latitude, longitude and altitude. If altitude is missing, the point is assumed to be at the Earth's surface, and the altitude is the distance measured from sea level.

I like this definition. I don't think we need to worry about coordinate systems outside of earth.

2024-09-25 14:21 UTC, uscholdm commented on docs/gistStyleGuide.md
> +| `skos:example` | May be either a full sentence, a list, or sample values. Full sentence or list examples should end with a period, e.g., "SSN, driver's license number, employee ID." or "NIH sponsor
The distinction you make is real enough, but is nuanced - it might cause more confusion than clarity.

2024-09-26 14:48 UTC, rjyounes commented on ontologies/gistCore.ttl
> +		"Across the world there are a variety of types of subsections of a country and the governments thereof (as well as different terms, like 'province' and 'state,' which refer to essentially the same
@Jamie-SA I don't like it either, it doesn't make sense to me, but it's not a "rule," it's a rule. There is no controversy among grammarians about this.

2024-09-26 17:02 UTC, kstudzin commented on ontologies/gistCore.ttl
> +	skos:example "An amount of water, penicillin, sand, or gold."^^xsd:string ;
I'm confused about gold the element as a negative example. Is it a negative example because we can't purify it enough and therefore doesn't exist? In theory, if there were a hunk of elemental gold and it split into two hunks, they would be indistinguishable from one another

2024-09-27 21:21 UTC, uscholdm commented on ontologies/gistCore.ttl
> +	skos:example "An amount of water, penicillin, sand, or gold."^^xsd:string ;
> I initially removed it because I wasn't really sure what we meant by 'the concept of gold.' I'm also confused about gold the element as a negative example. Is it a negative example because we can't purify it enough and therefore doesn't exist? In theory, if there were a hunk of elemental gold and it split into two hunks, they would be indistinguishable from one another

No, it is a negative example because gold the concept is a type, a category, a kind of thing - it has no mass or volume.  Analogously, my physical iPhone SE2020 does in fact weigh 300g;  you can ask the question: what kind of phone do I have? All phones of that kind should weigh close to 300g, but the model itself is not a physical thing that has mass or volume.  The model has a spec saying each phone of that model should weigh 300g

2025-10-18 12:17 UTC, rjyounes commented
Thank you for all this work, @kstudzin! It looks great. Approved but need to resolve conflicts with base.

2025-10-18 12:35 UTC, rjyounes commented on docs/gistStyleGuide.md
> +| `skos:example` | May be either a full sentence, a list, or a single value. Full sentence or list examples should end with a period, e.g., "SSN, driver's license number, employee ID." or "NIH sponso
There are a couple of nuances I found after taking a look at our examples that don't end in periods: 
* an example that's just a datetime - looks odd with a final period
* examples included in terms pulled from gist reference data - we don't want to change those.

However, I think it gets way too detailed to add this to the style guide. What do you think?

2025-10-22 18:12 UTC, kstudzin commented on docs/gistStyleGuide.md
> +| `skos:example` | May be either a full sentence, a list, or a single value. Full sentence or list examples should end with a period, e.g., "SSN, driver's license number, employee ID." or "NIH sponso
Yes, it does seem a bit much. I'll remove

2025-10-24 20:41 UTC, rjyounes commented
@stevenchalem Can you please do a full review of this? You don't have to check the conflict resolution, just the changes as a whole. I've made a few wording changes and additions that should have another pair of eyes.

2025-10-25 18:51 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:scopeNote "Depending on implementation, every aspect should be related to a unit group either directly or through a broader aspect. For example, angle of incidence can be related to the broader
```suggestion
	skos:scopeNote "Depending on implementation, every aspect should be related to a unit group either directly or through a broader aspect. For example, angle of incidence could be related to the broader concept of angle, which in turn is related to a unit group, or it could be related directly to the unit group without the hierarchical relationship."^^xsd:string ;
```

2025-10-25 19:13 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:example "A machine, a router, a car."^^xsd:string ;
```suggestion
	skos:example "A machine, a router, a car, a chair, a necklace."^^xsd:string ;
```
Since the definition is broader that when we usually call "equipment," I think it's helpful to include examples that might not normally be thought of as "equipment."

2025-10-25 19:26 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:definition "An individual point in physical space identified by latitude, longitude, and altitude. If altitude is missing, the point is assumed to be at the Earth's surface, and the altitude is
```suggestion
	skos:definition "An individual point in physical space identified by latitude, longitude, and altitude. Altitude is the distance measured from sea level. If altitude is missing, the point is assumed to be at the Earth's surface."^^xsd:string ;
```
As written, this could be read as "If altitude is missing ... the altitude is the distance measured from sea level."

2025-10-25 19:33 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:scopeNote "A geographical region could be non-contiguous; e.g., the region governed by the US federal government is the contiguous area of the lower 48 states plus Alaska and Hawaii. Child clas
```suggestion
	skos:scopeNote "A geographical region could be non-contiguous; e.g., the region governed by the US federal government is the contiguous area of the lower 48 states plus Alaska, Hawaii, and overseas territories. Child classes in lower ontologies can make this distinction."^^xsd:string ;
```

2025-10-25 19:40 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:definition "A single portion of a geographical route which has been divided (i.e., segmented)."^^xsd:string ;
```suggestion
	skos:definition "A single portion of a GeoRoute consisting of a pair of consecutive GeoPoints which belong to it."^^xsd:string ;
```
Since this class is being removed in another PR, I think that leaving it unchanged here will avoid a merge conflict.

2025-10-25 19:55 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:example "Permission could be broad, such as free speech, but more often is very specific, such as the right of egress through a particular property."^^xsd:string ;
```suggestion
	skos:example "Permission could be broad, such as free speech, but more often is very specific, such as the right of passage through a particular property."^^xsd:string ;
```
"Egress" means exit; I don't think that's the intended meaning here. Alternatives: "right of transit," or the less formal "right to pass through" or "right to travel through."

2025-10-25 20:04 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:definition "A category indicating the real-world effects of an action."^^xsd:string ;
```suggestion
	skos:definition "A category of actions that have real-world effects."^^xsd:string ;
```
The examples don't describe the effects; they describe the actions themselves.

2025-10-25 20:21 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:example "1600 Pennsylvania Avenue NW, Washington, DC 20500; PO Box 7704, San Francisco, CA 94120-7704."^^xsd:string ;
```suggestion
	skos:example "1600 Pennsylvania Avenue NW, Washington, DC 20500; PO Box 7704, San Francisco, CA 94120-7704; Room 317 in the Louvre Museum."^^xsd:string ;
```
Just to make clear that this doesn't need to take the form of a standardized postal address.

2025-10-25 20:32 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:definition "The subject is consistent with or satisfies the requirements, rules, or expectations etablished by the object."^^xsd:string ;
```suggestion
	skos:definition "The subject is consistent with or satisfies the requirements, rules, or expectations established by the object."^^xsd:string ;
```

2025-10-25 20:36 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:example "Miles per hour has miles as a multiplier and hour as a divisor; speed has distance as a multiplier and duration as a divisor."^^xsd:string ;
```suggestion
	skos:example "Miles per hour has miles as a multiplier and hours as a divisor; speed has distance as a multiplier and duration as a divisor."^^xsd:string ;
```

2025-10-25 20:38 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:definition "Relates an event, agreement, or obligation to the participating people or organizations."^^xsd:string ;
```suggestion
	skos:definition "Relates an event, agreement, or obligation to a participating person or organization."^^xsd:string ;
```

2025-10-25 20:46 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:definition "Relates something to a taxonomy term or other less formally defined class."^^xsd:string ;
```suggestion
	skos:definition "Relates something to a taxonomy term or other less formally defined thing that classifies or characterizes it."^^xsd:string ;
```
Avoiding the potentially confusing "class." Also saying something about the nature of the relationship.

2025-10-25 21:31 UTC, stevenchalem submitted a review, later dismissed
On line 586, the skos:prefLabel for gist:DegreeOfCommitment is not in title case

2025-10-25 21:31 UTC, stevenchalem commented on ontologies/gistCore.ttl
>  	skos:scopeNote "This is used in conjunction with gist:isIdentifiedBy"^^xsd:string ;
```suggestion
	skos:scopeNote "This is used in conjunction with gist:isIdentifiedBy."^^xsd:string ;
```

2025-10-26 15:32 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "Permission could be broad, such as free speech, but more often is very specific, such as the right of egress through a particular property."^^xsd:string ;
I love "right [rite] of passage" but decided on "right to enter."

2025-10-26 15:36 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "A category indicating the real-world effects of an action."^^xsd:string ;
Not crazy about your suggestion because it doesn't indicate the categorization is in terms of its real-world effect. What do you think about "A category indicating the type of an action in terms of its effect in the physical world."?

2025-10-26 15:41 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:definition "Relates something to a taxonomy term or other less formally defined class."^^xsd:string ;
How about just "classification" rather than class?

2025-10-26 15:44 UTC, rjyounes commented
@stevenchalem Thank you for the very close reading. I've adopted most of your suggestions, but in a few cases I've addressed your comment in a slightly different way from what you suggested. Could you look at the unresolved comments to review those?

2025-10-26 17:02 UTC, stevenchalem commented on ontologies/gistCore.ttl
> +	skos:definition "Relates something to a taxonomy term or other less formally defined class."^^xsd:string ;
I like it.

2025-10-26 19:08 UTC, rjyounes commented on ontologies/gistCore.ttl
> +	skos:example "A machine, a router, a car."^^xsd:string ;
Hm, this is an odd one. I think the definition should be tightened up, rather than extending the examples. It should also say man-made; this used to be a subclass of `Artifact`, which was removed.

2025-10-26 19:19 UTC, merged