Feature/skos annotations
semanticarts/gist pull request #378
Opened 2020-09-26 01:03 UTC by uscholdm

Addressed issue https://github.com/semanticarts/gist/issues/351

2020-09-26 19:26 UTC, sa-bpelakh approved these changes
@ungricht I reviewed lines 1000-2000 (GeoPoint through ProductCategory), only one minor comment on capitalization. 
@uscholdm There are 7 terms that do not have a `skos:definition`:
- ControllerType
- universalTime
- universalDateTime
- universalDate
- localTime
- localDateTime
- localDate

We should address those as part of this effort.

2020-09-26 19:26 UTC, sa-bpelakh commented on gistCore.ttl
> +		"a computer, a book."^^xsd:string
```suggestion
		"A computer, a book."^^xsd:string
```

2020-09-28 18:12 UTC, uscholdm commented
> There are 7 terms that do not have a skos:definition:

I was not sure whether to do that now or in the next round. I'll add them now.

2020-09-28 21:50 UTC, rjyounes commented
@uscholdm I don't think you should do that now because the reviewers' task is not to evaluate the annotation values themselves, but to make sure they have been appropriately converted to SKOS. This makes it harder to know what to review. I believe we have one or more existing issues for rewriting annotations.

2020-09-28 22:08 UTC, uscholdm commented
In those few cases where there was an existing rdfs:comment that turned out to be nothing like a definition and the end results was no skos:definition, I added a few.  I drew the line at making changes to existing definitions. I could have gone either way. Don't think it matters much. I just made the change.

2020-10-01 13:57 UTC, rjyounes requested changes
I'm not doing a full review now, but a note needs to be added to the release notes file. Please remember to include the legacy file in the note.

2020-10-05 16:03 UTC, rjyounes requested changes
Nice job! A few very small changes requested.

2020-10-05 23:50 UTC, uscholdm commented on docs/ReleaseNotes.md
> +- Backward compatibility is retained because we also publish an auto-generated version of the skos annotations in the file: rdfsAnnotations.ttl.  The diffferent skos annotations are distinguished by
Good catch.

2020-10-05 23:54 UTC, uscholdm commented on gistCore.ttl
> +		"a simple unit: kilogram"^^xsd:string ,
I just made the few changes right here (TBC), but a broader automated check would be worth doing. Part of style checking to go into the onto-tools?

2020-10-06 00:04 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote
Leaving this alone. For classes the prefLabel should be capitalized start, but not necessarily for properties. Solution is to add automated style check to onto-tools.

2020-10-06 00:06 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "Time, but not on a timeline."^^xsd:string ;
Good catch.

2020-10-06 00:06 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "audio, still image, video, textual, physical (e.g., a statue), or performance (i.e. a play).  Or it could be oil or pastel for a painting."^^xsd:string ;
Fixed

2020-10-06 00:07 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "the vase is made up of clay"^^xsd:string ;
Fixed

2020-10-06 13:32 UTC, sa-bpelakh commented on gistCore.ttl
> +	skos:scopeNote
We can REGEX for capitalization either through SHACL or through query. If you want to write this up as an issue, we can address it between onto_tool and the bundle script.

2020-10-06 16:27 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition 'Comment: this is not the inverse of fromAgent. A message can be from someone. If we made it the inverse the person would be "to" the message'^^xsd:string ;
The original has a comment but no definition. I suggest the following:

```
skos:definition "The destination of a message or shipment" 
skos:scopeNote 'This is not the inverse of fromAgent. A message can be from someone. If we made it the inverse the person would be "to" the message."
```

The definition corresponds to that for from Agent.

2020-10-06 20:07 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition 'Comment: this is not the inverse of fromAgent. A message can be from someone. If we made it the inverse the person would be "to" the message'^^xsd:string ;
Good idea. I tweaked your suggestion for now, but it will be up for discussion later on.

2020-10-22 15:16 UTC, scotthenninger approved these changes
Performed some SPARQL queries to verify that rdfs labels comments, etc. do not exist and  and skos label, alt, definition equivalents exist.

2020-10-26 14:15 UTC, rjyounes requested changes
I requested a couple of tiny tweaks. You don't need to request a re-review.

2020-10-26 14:15 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote
This comment does not pertain to prefLabels - which I agree should be lowercase for properties, as per the convention we've agreed on - but about the other annotations where you stripped off the original prefix such as "NOTE: " or "EXAMPLE: " and are left with a scopeNote or example whose text begins with lowercase. I am recommending changing those from lower to upper.

2020-10-26 14:15 UTC, rjyounes commented on gistCore.ttl
>  	.
Missing space after "Negatvie example:fictional". You don't have to run this by me again for review.

2020-10-26 14:15 UTC, rjyounes commented on gistCore.ttl
There is no more gistTop or gistTime. This should have been fixed with demodularization but was not caught.

2020-10-26 14:15 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Most frequently apples to Event(s) and Offer(s). E.g. a conference or sale offer."^^xsd:string ;
Should we put the conference or sale offer in a skos:example?

2020-10-26 19:45 UTC, uscholdm commented on gistCore.ttl
>  	.
Done

2020-10-26 19:49 UTC, uscholdm commented on gistCore.ttl
@rjyounes That's outside the scope of this issue, but it was easy to do now, so I did.

2020-10-26 19:54 UTC, uscholdm commented on gistCore.ttl
>  	.
@rjyounes 

> This comment does not pertain to prefLabels - which I agree should be lowercase for properties, as per the convention we've agreed on - but about the other annotations where you stripped off the original prefix such as "NOTE: " or "EXAMPLE: " and are left with a scopeNote or example whose text begins with lowercase. I am recommending changing those from lower to upper.

The example scopeNote on line 343 (not shown above) starts with a capital C in Coherent. I am not sure what you are suggesting.

2020-10-26 20:02 UTC, uscholdm commented on gistCore.ttl
>  	.
@rjyounes 

> I requested a couple of tiny tweaks. You don't need to request a re-review.

I prefer that you formally approve the PR, so I requested a re-review.

2020-10-27 18:07 UTC, rjyounes requested changes

2020-10-27 18:07 UTC, rjyounes commented on docs/ReleaseNotes.md
> +*Converted rdfs annotations to skos annotations*
I made a couple of modifications to the release notes based on our new template. There should be a Rationale section, which I've inserted but leave to you to fill in.

2020-10-27 18:18 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "Most frequently apples to Event(s) and Offer(s). E.g. a conference or sale offer."^^xsd:string ;
I'll leave that to the judgment of those doing the annotations refresh.  If you want to make a quick change now, feel free.

2020-10-30 19:37 UTC, rjyounes approved these changes

2020-11-02 15:49 UTC, merged