Updates to documentation on contributing to gist. Fixes #382.
semanticarts/gist pull request #384
Opened 2020-10-04 17:11 UTC by rjyounes

2020-10-05 22:20 UTC, uscholdm commented on docs/Contributing.md
> +Note: The following instructions reference two git branches: the working branch, which is the one you create for your development work, and the main development branch, which is the branch that your
If there are two foobar things one is a plain foobar and the other is the main foobar, then noone will think that the main foobar is subordinate to the plain foobar.  

Thus, it's intuitively jarring that the 'main development branch' would be subordinate to a plain 'develop' branch.  Here is an alternative: 

However many levels deep into branching and sub-branching: 
1. Let's call any branch on which the main work is meant to take place a 'working branch'. 
2. Let's call any branch that a working branch branches off of and merges back into a 'develop branch'.

The develop branch that branches off the master can be called the 'main develop branch'. 
A develop branch that branches off of the main develop branch can be called a 'local develop branch'.

This is a perspective thing, not an absolute thing.  There is nothing to stop one from doing work on what someone else is treating as a local develop branch.  One man's develop branch can be another's working branch.

2020-10-05 22:28 UTC, uscholdm commented on docs/Contributing.md
> +- As you work, it is _essential_ that you merge regularly from the main development branch back into your working branch. This ensures that, when it comes time to merge your work into the main branch
> PR cannot be merged to the main branch

Do you mean 'master' branch here rather than main branch?

2020-10-05 22:30 UTC, uscholdm commented on docs/Contributing.md
> +- Once your work is ready to be merged into the main development branch, you will create a pull request (PR).
> Once your work is ready to be merged into the main development branch

I guess this means what I would call a local develop branch for the project, or 'project develop branch'.

2020-10-05 22:32 UTC, uscholdm commented on docs/Contributing.md
> +- A reviewer should assign the PR to the same release project as the issue it addresses if that has not been done when the PR was submitted.
Is there an assumption that on PR addresses exactly one issue?

2020-10-05 22:35 UTC, uscholdm requested changes
I found the terminology a bit confusing and after a bit of head-scratching came up with an alternative.

2020-10-06 14:39 UTC, rjyounes commented on docs/Contributing.md
> +Note: The following instructions reference two git branches: the working branch, which is the one you create for your development work, and the main development branch, which is the branch that your
I agree that the terminology I've used is confusing, though I don't think you've quite hit the mark in your proposal. For one thing, "develop branch" is bad grammar: don't form compounds with verb + noun, only adjective or noun + noun; e.g., we don't way "organize committee" but rather "organizing committe." "Develop" has become a conventional name for a particular branch in the repository that plays a particular function in the overall scheme. I'll reword this and run it by you again.

Actually, there may be branch rules in place that prevent others from developing on (committing to) a particular branch. Currently we have such rules in place for master and develop, but one could just as well create rules on a branch off of develop.

2020-10-06 14:40 UTC, rjyounes commented on docs/Contributing.md
> +- As you work, it is _essential_ that you merge regularly from the main development branch back into your working branch. This ensures that, when it comes time to merge your work into the main branch
No. Git will not allow you to merge one branch into another until merge conflicts have been resolved, unless the branch allows force commits, which is a _very_ bad idea.

2020-10-06 14:41 UTC, rjyounes commented on docs/Contributing.md
> +- A reviewer should assign the PR to the same release project as the issue it addresses if that has not been done when the PR was submitted.
No. Will fix.

2020-10-06 20:16 UTC, uscholdm commented on docs/Contributing.md
> +Note: The following instructions reference two git branches: the working branch, which is the one you create for your development work, and the main development branch, which is the branch that your
> For one thing, "develop branch" is bad grammar

If the branch called 'develop' was called 'developing' I would have used that.  A matter of taste, but to me, making a direct connection to what is super common thus adding clarity, trumps a grammatical nit that few would even notice (present company excepted :-)  I await a new proposal.

2020-10-06 20:18 UTC, uscholdm commented on docs/Contributing.md
> +Note: The following instructions reference two git branches: the working branch, which is the one you create for your development work, and the main development branch, which is the branch that your
> "Local" implies that the branch is not pushed to the remote

Good point, that won't work.

2020-10-06 20:20 UTC, uscholdm commented on docs/Contributing.md
> +- As you work, it is _essential_ that you merge regularly from the main development branch back into your working branch. This ensures that, when it comes time to merge your work into the main branch
OK so clarity is needed on the meaning of "main branch".  Is it shorthand for "man development branch"?

2020-10-07 15:54 UTC, rjyounes commented
@uscholdm I decided it was too confusing to describe the two cases at once (it seems my developer impulses were at work, assigning variables and using a recursive function), and at any rate the multi-developer scenario is something of an edge case, or at least not common in our practice. So I cordoned off that discussion to its own small section. See what you think.

2020-10-08 01:55 UTC, uscholdm commented on docs/Contributing.md
> +- As you work, it is _essential_ that you merge regularly from develop back into your working branch. This ensures that, when it comes time to merge your work into develop, you will have resolved any
I rarely do that because most of the changes I do are small and done over the course of a few hours. This is only important if plenty of other work is going on at the same time which is more likely if the work is taking place over a longerish period of time (such as now with skos-annotations).

Also, does it make it harder to see what the changes were for a particular branch?  If you do a big task over 2 weeks and merge develop into your branch 3 times for 3 other pieces of work, is there still an easy way for me to look at the work that was ONLY done on your branch?  Probably there is, just wondering.

2020-10-08 02:00 UTC, uscholdm commented on docs/Contributing.md
> +- Before submitting the PR, you should ensure that you have (a) run the serializer and (b) merged develop into your working branch, as above [during implementation](#commits-pushes-and-merges).
If following instructions, it should not be necessary to run serialzer AGAIN. So maybe reword this to emphasize that? Small point, feel free to ignore.

> Before submitting the PR, you should ensure that you have merged develop into your working branch, as above. Every commit should have the serializer fun, but just in case, makes double sure.

2020-10-08 02:02 UTC, uscholdm commented on docs/Contributing.md
> +- The serializer tool should be run before each commit in order to standardize formatting and eliminate noise in git diffs. See [_gist Style Guide_](gistStyleGuide.md) for details.
Not 'should', when is optional. The ontologist may choose to have this happen automatically as part of a commit if they done do it before the commit. That should be encourage, even enforced to the extent that we can. People (including me) often don't get around to this stuff.

Come to think of it, there is a good reason to a commit WITHOUT running serializer, and then follow with a commit immediately after running serializer. I often do this. Why?  Its far easier to look at file differences w/o the alpha sorting making a mess. This is a argument for not having the serializer auto-run (hook) or to have it be optionally turned off. Maybe too fiddly.

2020-10-08 02:07 UTC, uscholdm commented on docs/Contributing.md
> +- Submit the PR to develop.
> Submit the PR to develop

Reword to:
"Submit the PR to merge your working branch into develop"

2020-10-08 02:11 UTC, uscholdm requested changes
The language on the complicated project work is very clear now - better than either of our prior attempts.

A few suggested changes that you are free to disagree with...

2020-10-15 14:38 UTC, rjyounes commented on docs/Contributing.md
> +- Submit the PR to develop.
A PR is literally a "pull request" to pull the changes on one branch into another. So "pull request to merge" is redundant.

2020-10-15 14:41 UTC, rjyounes commented on docs/Contributing.md
> +- Before submitting the PR, you should ensure that you have (a) run the serializer and (b) merged develop into your working branch, as above [during implementation](#commits-pushes-and-merges).
Added something similar.

2020-10-15 14:44 UTC, rjyounes commented on docs/Contributing.md
> +- The serializer tool should be run before each commit in order to standardize formatting and eliminate noise in git diffs. See [_gist Style Guide_](gistStyleGuide.md) for details.
We talked about this in the review and I respectfully disagree. You may preview your changes without the serializer, but I still think the serializer should be run before each commit. If you were working on a serialized version, there should not be many alpha sort issues. The one you showed us was an edge case, IMO.

2020-10-15 14:57 UTC, rjyounes commented on docs/Contributing.md
> +- As you work, it is _essential_ that you merge regularly from develop back into your working branch. This ensures that, when it comes time to merge your work into develop, you will have resolved any
By "regularly" I didn't mean every 5 minutes :)  I've amended the instruction to suggest daily merges.

I guess to see only the work done on that branch you'd have to look at the commits before each merge. Admittedly somewhat inconvenient, but less so that the alternative. The alternative is to use rebase instead of merge, which keeps the history clean, but does so by rewriting the history. Rebase can be complicated and we (Boris, MarkW, and I) thought that it shouldn't be recommended practice.

2020-10-15 15:00 UTC, merged