Refactored giver, getter and hasParty
semanticarts/gist pull request #404
Opened 2020-11-19 21:21 UTC by uscholdm

- New property: `hasParticipant` replaces `hasParty`
  - Range: `Person` or `Organization`.
  - Domain: includes `Event`, `Agreement`, `Obligation`.
  - Has subproperties: `toAgent` and `fromAgent`

- Use `hasParticipant` wherever `hasParty` was used
- Use `toAgent` wherever `getter` was used
- Use `fromAgent` wherever `giver` was used
- Deprecate: `hasParty`, `getter` & `giver`.

2020-11-19 22:15 UTC, sa-bpelakh reviewed
Looks OK, but do we have an issue with consistency of property naming, i.e. `fromAgent`/`toAgent` vs `hasParticipant` (as opposed to `hasFromAgent`/`hasToAgent`). When do we prefix properties with `has`/`is`, and when do we not?

2020-11-20 02:21 UTC, uscholdm commented
> we have an issue with consistency of property naming, i.e. fromAgent/toAgent vs hasParticipant (as opposed to hasFromAgent/hasToAgent). When do we prefix properties with has/is, and when do we not?

This is true. There are a lot of inconsistencies like this. That is a separate issue (https://github.com/semanticarts/gist/issues/188). I think its best to not too too many things at once.

2020-11-23 17:27 UTC, marksem commented
I feel like hasParticipant -- as a general property -- can have a broader range.  Would not restrict domain to Person or Org.

2020-11-23 22:52 UTC, uscholdm commented
@marksem said:

> I feel like hasParticipant -- as a general property -- can have a broader range. Would not restrict domain to Person or Org.

Another discussion you missed. I agree with you on this, but the majority felt that  'participate' implied some active intent. So inanimate objects need not apply for this role.  There might still be time to file a law suit and overturn the vote result.

2020-12-02 19:18 UTC, marksem commented
Regarding active "intent", if I say a process participates in a larger process, I am not implying agency on the process.   A chemical participates in a chain reaction.  Assuming participatesIn would be the logical inverse of hasParticipant, I again feel that more than Persons and Orgs participate in things.        Your honor, I move that Person/Org restrictions be stricken from the record!

2020-12-02 19:26 UTC, uscholdm commented
I could not agree mere!!! Pity you were not there to make your case when it came up. @rjyounes I suggest we revisit this on a future Thursday session.

2020-12-02 19:34 UTC, rjyounes commented
OK, let's put this on hold. @uschold Do you remember the issue number so I can change the label to "in review"? 

Maybe @marksem's disagreement is only with the wording - that is, I at least still think that there is value to distinguishing the kind of participation agents do as opposed to things, but perhaps we don't have the right term.

2021-01-12 14:16 UTC, sa-bpelakh commented
> OK, let's put this on hold and move the issue back to in review.
> 
> Maybe @marksem's disagreement is only with the wording - that is, I at least still think that there is value to distinguishing the kind of participation agents do as opposed to things, but perhaps we don't have the right term.

@rjyounes @marksem @uscholdm The way I see it , `hasParticipant` is the generic property that does not imply a range, whereas `hasParty` is the property that implies agency (and thus is the super-property of `toAgent`/`fromAgent`). How would you link a non-agent entity into an `Agreement` - e.g. the property into a loan?

2021-01-12 14:17 UTC, sa-bpelakh approved these changes
Changes look clean, assuming we have resolved the issue of the range on `hasParticipant`.

2021-01-12 15:51 UTC, marksem requested changes
@uscholdm , I don't see where you addressed my concerns about the skos:definitions of toAgent and fromAgent.  Since we have enlarged their scope (now used in place of getter/giver), I think those textual definitions need to change.  You appear to have changed definitions on other properties instead?

2021-01-13 00:50 UTC, uscholdm commented on gistCore.ttl
>  	skos:definition "Indicates to whom (e.g. a message or shipment) is destined for."^^xsd:string ;
This is a good suggestion. On a separate note, Dave wants to use something for giver/getter that is NOT a Person or Org -- e.g. an account.  A variation being considered is this:

```
hasParticipant
  giver (no range)
    fromAgent
  getter (no range)
    toAgent
  hasParty (range: Person or Organization)
    fromAgent
    toAgent
```
This does two things:
1. Allows giver and getter to be used with more than just Person or Organization
2. Creates an abstract super-property to collect similar properties in one place

It does these things with minimal disruption:
- Keeps hasParty as originally conceived with range of Person or Org
- Keeps toAgent and fromAgent as originally conceived with range of Person or Org
- Keeps giver and getter 

Proposed release notes:
**Refactored `hasParty`, `giver` and `getter`**
- New property: `hasParticipant`
  - Domain: includes `Event`, `Agreement`, `Obligation`.
  - Range: none.
  - Has subproperties: `hasParty`, `giver` and `getter`
- `giver` and `getter` 
  - are no longer subproperties of `hasParty`
  - are direct subproperties of `hasParticipant`
- `toAgent` and `fromAgent` are now subproperties of `hasParty`

2021-01-14 16:35 UTC, marksem commented on gistCore.ttl
>  	skos:definition "Indicates to whom (e.g. a message or shipment) is destined for."^^xsd:string ;
Discussion results:

hasParticipant (no range)  (new)
  fromAgent  (range Person or Org)   DROP (Dep)
  toAgent  range Person or Org       DROP (Dep)
  giver (no range)   hasGiver (dep giver)
  getter (no range)  hasGetter  (dep getter)

hasParty (range: Person or Organization)
  pro: Useful for agreements

Update all refs to from/toAgent to be hasGiver/hasGetter

2021-01-16 01:04 UTC, uscholdm commented
LATEST CHANGE NOTES:
**Refactored `hasParty`, `giver` and `getter`**
- 'giver' and 'getter'
  - Rename to `hasGiver` and `hasGetter`
  - Deprecate
  - No longer subproperties of `hasParty`
- New property: `hasParticipant`
  - No domain or range
  - Has subproperties: `hasGiver`, `hasGetter`, `hasParty`, `fromAgent` and `toAgent`
- Added annotations on `fromAgent` and `hasParty`

2021-01-16 18:03 UTC, mkumba commented
Didn’t we decide to deprecate fromAgent and toAgent and redo message to be hasGiver and hasGetter?


On Jan 15, 2021, at 5:04 PM, Michael Uschold <notifications@github.com<mailto:notifications@github.com>> wrote:



LATEST CHANGE NOTES:
Refactored hasParty, giver and getter

  *   'giver' and 'getter'
     *   Rename to hasGiver and hasGetter
     *   Deprecate
     *   No longer subproperties of hasParty
  *   New property: hasParticipant
     *   No domain or range
     *   Has subproperties: hasGiver, hasGetter, hasParty, fromAgent and toAgent
  *   Added annotations on fromAgent and hasParty

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/semanticarts/gist/pull/404#issuecomment-761280150>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAAGJPWOMIDFFCXUAXNKGNTS2DQZLANCNFSM4T36AKMA>.

2021-01-18 01:34 UTC, uscholdm commented
> Didn’t we decide to deprecate fromAgent and toAgent and redo message to be hasGiver and hasGetter?

If we did, I don't specifically recall. It was not in the summary notes from @marksem MarkW, or if it was, I missed it. Can others chip in and confirm one way or the other?

2021-01-18 16:09 UTC, rjyounes commented
@uscholdm I don't recall that, but rethinking it, as Dave suggests, I don't know why we would need fromAgent and toAgent when we have hasGiver and hasGetter.

2021-01-18 17:44 UTC, uscholdm commented
> @rjyounes   I don't know why we would need fromAgent and toAgent when we have hasGiver and hasGetter.

Its tempting, but I'm not sure it is always correct.  Suppose I make a change to the beneficiary on my life insurance policy from person A to person B.  If there is an instance of a class called BeneficiaryChange the `fromAgent` is person A but they are not a giver.

In the case of a package or a message, the `fromAgent` is the sending agent or the originating agent which might not correspond to 'giving' anything.  The sender might be returning a borrowed item to its owner.  Both would nicely fit in a totally generic `gist:from` property, but I am the only proponent of that idea.

2021-01-18 18:36 UTC, rjyounes commented
@uscholdm  "Give" doesn't have to mean transfer of ownership; we can say "give back" for returning a borrowed item. Anyway, the same argument could be applied to putting money in someone's bank account, which is one of the uses cases for hasGiver; if that were borrowed money, then according to your limited sense of "give," that is not giving either. Even the original sense of giving an obligation is not a transfer of ownership. 

As for the first example, I think you are incorrectly exploiting the multi-faceted meaning of "from" (and most prepositions) to broaden the meaning of "fromAgent" beyond the agreed-upon sense. If "fromAgent" means "the source of something" - I believe we are keeping that part of the definition and simply broadening it to include a wider scope than message or shipment - person A is not the _source_ of the beneficiary change either: _you_ would be the fromAgent (the source of the beneficiary change) and person B would be the toAgent. I think the BeneficiaryChange is a three-way relationship, and we don't have a specific predicate for that happened to A.

2021-02-15 17:11 UTC, rjyounes requested changes
Requesting just a couple of tiny changes.

2021-02-15 17:11 UTC, rjyounes commented on docs/ReleaseNotes.md
> +  - Rename to `hasGiver` and `hasGetter`
We're using past tense in release notes.

2021-02-15 17:11 UTC, rjyounes commented on docs/ReleaseNotes.md
> +  - Deprecate
We're using past tense in release notes.

2021-02-15 17:11 UTC, rjyounes commented on docs/ReleaseNotes.md
> +- Added annotations on `fromAgent` and `hasParty`
A bit confusing, since when I look at the code I don't know what annotations have been added. Can we just leave this out - or if you want it there just a couple of words to indicate what's changed?

2021-02-15 17:28 UTC, rjyounes commented on gistDeprecated.ttl
> +	<http://www.w3.org/2004/02/skos/core#definition> "The active party, the one with the obligation or the one initiating the transfer"^^xsd:string ;
Could you add the skos prefix to the file header so we can use the prefixed form of the annotations here?

2021-02-15 17:32 UTC, rjyounes commented on docs/ReleaseNotes.md
> +**Refactored `hasParty`, `giver` and `getter`**
Please add issue number to the release note.

2021-02-15 23:33 UTC, uscholdm commented on gistCore.ttl
>  	rdfs:range [
We've had this conversation before.  Redundancy is generally to be avoided, but sometimes it reduces errors. For example, if someone changed the range of the super-property and forgot to change the range of the sub-properties, an error could result.  Another example is relying on transitivity of import. I don't have a horse in this race, so I could go either  way. I do think we should make the decision consciously, not just exclude redundancy as an absolute principle.

2021-02-15 23:33 UTC, uscholdm commented on gistCore.ttl
>  		owl:unionOf (
See above.

2021-02-15 23:47 UTC, uscholdm commented on docs/ReleaseNotes.md
> +**Refactored `hasParty`, `giver` and `getter`**
> Please add issue number to the release note.

Done.

2021-02-15 23:49 UTC, uscholdm commented on gistDeprecated.ttl
> +	<http://www.w3.org/2004/02/skos/core#definition> "The active party, the one with the obligation or the one initiating the transfer"^^xsd:string ;
> Could you add the skos prefix to the file header so we can use the prefixed form of the annotations here?

Good idea. Done.

2021-02-16 00:06 UTC, uscholdm commented on docs/ReleaseNotes.md
> +- Added annotations on `fromAgent` and `hasParty`
I purposely left out the gory details thinking it's easy enough for people to look to see for themselves.  At some point (maybe not this one) more detail detracts.  I added a scope note to one and an example on the other.  I also added one word to the `skos:defintion` which I  chose not to mention. Its a matter of taste, I suppose.  Do you prefer this level of detail:

- Added the word 'event' to the `skos:definition` of `fromAgent`
- Added a `skos:scopeNote` to `fromAgent` 
- Added a `skos:example` to `hasParty`

2021-02-16 00:15 UTC, uscholdm commented on docs/ReleaseNotes.md
> +  - Rename to `hasGiver` and `hasGetter`
OK

2021-02-16 00:15 UTC, uscholdm commented on docs/ReleaseNotes.md
> +  - Deprecate
OK

2021-02-25 15:58 UTC, rjyounes approved these changes

2021-02-25 15:58 UTC, rjyounes commented on gistCore.ttl
>  	rdfs:range [
I think this comment was made when fromAgent was a subproperty of hasParty. It's no longer relevant.

2021-02-25 15:58 UTC, rjyounes commented on gistCore.ttl
>  		owl:unionOf (
I think this comment was made when fromAgent was a subproperty of hasParty. It's no longer relevant.

2021-02-25 16:34 UTC, rjyounes commented
Michael will touch base with Mark to see if his comment has been addressed and the PR can be merged.

2021-02-25 21:23 UTC, marksem requested changes
All looks good except for the skos:definitions of fromAgent and toAgent.  I find them gramatically incorrect and/or too specific on implying a domain of shipment or message only.

Suggestions to correct this:

fromAgent:
     the party that is the source of something (e.g. a message, shipment, etc.)

toAgent:
     the party that is the recipient of something (e.g. a message, shipment, etc.)

2021-02-26 02:41 UTC, sa-bpelakh reviewed
Yay, compliant labels :) Are you running a build to verify before pushing?

2021-02-26 02:41 UTC, sa-bpelakh commented on .gitignore
> +docs/ReleaseNotes.md.orig
```suggestion
*.orig
```
will prevent more editing later.

2021-02-26 03:57 UTC, uscholdm commented
> Yay, compliant labels :) Are you running a build to verify before pushing?

No. I merged develop into the branch first. I also read the manual and acted accordingly.

2021-02-26 03:59 UTC, sa-bpelakh approved these changes

2021-02-26 15:57 UTC, rjyounes approved these changes

2021-02-26 15:57 UTC, rjyounes commented on docs/ReleaseNotes.md
> +**Refactored `hasParty`, `giver` and `getter`**
I pushed a small change to the release notes, moving patch updates below minor updates. I didn't want to bother you with it.

2021-02-26 16:04 UTC, merged