Label validation
semanticarts/gist pull request #428
Opened 2021-02-01 19:03 UTC by sa-bpelakh

Created rules for Title Case, Lower Case and Sentence Case, and associated with classes and properties. Also mandated at least one `skos:definition` for each ontology entity. You can run `onto_tool` to see how the validation outputs, and we can convert these to warnings for the time being so they don't abort the build, until we can actually change the labels. 

I think the regex work with the current labels, but we may need to augment to support numbers, dashes, etc, which are currently all excluded.

2021-02-02 16:30 UTC, rjyounes requested changes
Can you look at my title case proposal on #227 as of 11:15 this morning and incorporate it into your code? Then I can do a full review.

2021-02-03 20:46 UTC, sa-bpelakh commented
@rjyounes I updated the regex to be more flexible, support numbers + the list of prepositions, articles etc you listed. Here are the positive examples I tested:

```
One-Off
Seems OK
Single
Dangling And
Lower and More
Proper-Dash
With a 123 Number
Trailing Number 345
SSN 123-345-890
Various Articles a an the Conjunctions and but if for or nor so yet Prepositions as at by cum ere for in of off on out per pre pro qua re sub to up via Done
```
and here are some negative examples
```
With an Improper-dash
not capitalized
15 Leading Number
```

2021-02-15 16:47 UTC, rjyounes requested changes
Regarding capitalized proper nouns in sentence and lower case, I didn't check the regexes closely, but at a minimum the comments need to be updated.

2021-02-15 16:47 UTC, rjyounes commented on ontologyShapes.ttl
> +	sh:pattern "^([A-Z]([a-z]+|[A-Z]+)|[A-Z]([a-z]+|[A-Z]+)([- ]([A-Z]([a-z]+|[A-Z]+)|[0-9]+)| a[nst]?| the| and| but| i[fn]| [fn]?or| so| yet| by| cum| ere| o(ff?|n|ut)| p(re|er|ro)| qua| re| sub| to|
If I were writing this I'd opt for readability over conciseness and spell out each word separately, but it's a stylistic decision.

2021-02-15 16:47 UTC, rjyounes commented on ontologyShapes.ttl
> +	skos:definition "Enforces Lower Case, allowing for all-caps words for acronyms."^^xsd:string ;
Have you accounted for capitalized proper nouns?

2021-02-15 16:47 UTC, rjyounes commented on ontologyShapes.ttl
> +	skos:definition "Enforces Sentence Case, allowing for all-caps words for acronyms."^^xsd:string ;
Have you accounted for capitalized proper nouns?

2021-02-15 17:38 UTC, rjyounes commented on ontologyShapes.ttl
> +	sh:path skos:prefLabel ;
It occurs to me that we should include ```skos:altLabel``` as well.

2021-02-15 18:25 UTC, sa-bpelakh commented on ontologyShapes.ttl
> +	sh:pattern "^([A-Z]([a-z]+|[A-Z]+)|[A-Z]([a-z]+|[A-Z]+)([- ]([A-Z]([a-z]+|[A-Z]+)|[0-9]+)| a[nst]?| the| and| but| i[fn]| [fn]?or| so| yet| by| cum| ere| o(ff?|n|ut)| p(re|er|ro)| qua| re| sub| to|
This regex has reached levels of complexity where readability would always be a challenge. I felt that a concise form would make maintenance easier.

2021-02-15 18:27 UTC, sa-bpelakh commented on ontologyShapes.ttl
> +	skos:definition "Enforces Lower Case, allowing for all-caps words for acronyms."^^xsd:string ;
Not in the regex, as there is no way to recognize a proper noun. I will add a `skos:editorialNote` to indicate that `nonConformingLabel` should be used to handle exceptions.

2021-02-15 18:30 UTC, sa-bpelakh commented on ontologyShapes.ttl
> +	sh:path skos:prefLabel ;
Do we want any sort of governance for `altLabel`? It can be used for any purpose, and does not fall into the scope of the primary labels being standardized.

2021-02-15 21:33 UTC, rjyounes commented on ontologyShapes.ttl
> +	sh:path skos:prefLabel ;
Good question; I'm not sure. We did say that if we want implementation-specific labels such as for column headers, we should define specific annotations for that. I think of `altLabel` as something like "USA" for the entity with `prefLabel` "United States of America." 

SKOS defines `altLabel` as "Acronyms, abbreviations, spelling variants, and irregular plural/singular forms may be included among the alternative labels for a concept."

I guess we should merge this PR and then bring up `altLabel` as a separate issue.

2021-02-15 21:36 UTC, rjyounes commented on ontologyShapes.ttl
> +	skos:definition "Enforces Sentence Case, allowing for all-caps words for acronyms."^^xsd:string ;
Never mind, this and the other comment to this effect were momentary lapses on my part.

2021-02-15 21:37 UTC, rjyounes approved these changes

2021-02-16 14:50 UTC, merged