Add property gist:description. Fixes #425.
semanticarts/gist pull request #429
Opened 2021-02-15 17:26 UTC by rjyounes

Add datatype property ```gist:description```.

2021-02-16 00:26 UTC, uscholdm commented on docs/ReleaseNotes.md
> +Import URL: <https://ontologies.semanticarts.com/o/gistCoreX.x.x>. [ADD APPROPRIATE VERSION NUMBER FOR RELEASE]
Why is this here? There is non corresponding change in any files.

2021-02-16 00:31 UTC, uscholdm requested changes
Clarify meaning of `gist:description`.
Remove or explain redundant text in release notes.

2021-02-16 00:31 UTC, uscholdm commented on docs/ReleaseNotes.md
> +- Added datatype property `gist:description` for describing instance data. Issue [#425](https://github.com/semanticarts/gist/issues/425).
Here is says for instance data. There is no mention of this in the actual ontology. Hard to know what is intended. Maybe add a scope note about intended usage?

2021-02-25 15:49 UTC, rjyounes commented on docs/ReleaseNotes.md
> +Import URL: <https://ontologies.semanticarts.com/o/gistCoreX.x.x>. [ADD APPROPRIATE VERSION NUMBER FOR RELEASE]
This is the URL we provide for users to import gist. The bracketed note is addressed to the release manager and will be deleted in the final text.

2021-02-25 16:39 UTC, sa-bpelakh approved these changes
Perhaps a `skos:scopeNote` on the property to indicate that it is a description of an instance entity providing greater detail than a `prefLabel`? Otherwise, looks fine.

2021-02-25 19:33 UTC, rjyounes commented on docs/ReleaseNotes.md
> +- Added datatype property `gist:description` for describing instance data. Issue [#425](https://github.com/semanticarts/gist/issues/425).
Good idea, I added a scope note.

2021-02-26 17:46 UTC, merged