Modify README for public consumption, add release process details. Fixes #87, #141
semanticarts/gist pull request #453
Opened 2021-04-12 14:34 UTC by sa-bpelakh

2021-04-12 15:59 UTC, Jamie-SA approved these changes
Probably should include some info about getting it onto the website. Would you prefer creating a separate issue for that or would you like me to commit to your branch?

2021-04-12 20:35 UTC, sa-bpelakh commented
@Jamie-SA Feel free to to add to the branch, Rebecca hasn't even reviewed my grammar yet 😄 Since this is a public repo, not sure how detailed we want to be on internal server info, but general instructions are fine.

2021-04-13 14:02 UTC, rjyounes requested changes
I recommend removing the build and release information from the change and release management doc. Otherwise good, including grammar and punctuation :)

2021-04-13 14:02 UTC, rjyounes commented on README.md
> +# gist
Markdown rules require a space between the header and following text.

2021-04-13 15:30 UTC, sa-bpelakh commented on docs/ChangeAndReleaseManagement.md
> +
Where would you favor documenting this? Confluence? #141 requested the process to be documented.

2021-04-13 15:53 UTC, rjyounes commented on docs/ChangeAndReleaseManagement.md
> +
I guess I wasn't around for that one. We have documentation of the release processes, both for [developers](https://semarts.atlassian.net/wiki/spaces/OF/pages/49479787/gist+Release+Checklist+Developers) and [ontologists](https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists), on confluence. Does that work?

2021-04-14 14:00 UTC, sa-bpelakh commented on README.md
> +# gist
Done.

2021-04-14 14:01 UTC, sa-bpelakh commented on docs/ChangeAndReleaseManagement.md
> +
I added a note about attaching the artifact to the release to the [ontologists](https://semarts.atlassian.net/wiki/spaces/OF/pages/1126760539/gist+Release+Management+Ontologists) Confluence page, the rest of the info was already there. Removing it from this public document.

2021-04-14 14:53 UTC, rjyounes approved these changes
Looks good.

2021-04-14 14:54 UTC, merged