Rename MimeType to MediaType, create ontology to declare instances. Fixes #434, #463
semanticarts/gist pull request #477
Opened 2021-05-17 17:18 UTC by sa-bpelakh

@mkumba There was extensive debate about this issue, and your input was requested. I followed the approach @Jamie-SA and I favored, which was to create annotations for existing IANA media type pages by adding types and labels.

@rjyounes and some others said we should not be creating statements using entities we do not own as subjects, and suggested I follow this pattern instead:

```
gist:_MediaType_TextHtml 
    a gist:MediaType; 
    gist:uniqueText "text/html";
    owl:sameAs iana:text\/html .
```

Creating a duplicate instance in the `gist` namespace for each of the media types. Do you have strong feeling in either direction?

2021-05-17 18:09 UTC, Jamie-SA commented on gistMediaTypes.ttl
> +	a gist:MimeType ;
Should this be gist:MediaType?

2021-05-17 19:39 UTC, sa-bpelakh commented on gistMediaTypes.ttl
> +	a gist:MimeType ;
Whoops, copy-pasta 🤦 will fix.

2021-05-17 20:27 UTC, mkumba commented
I don’t think I’m qualified enough to make a call between mimeType and mediaType (as long as we keep GeneralMediaType, where we just distinguish video, from audio, image and text and one or two others)

And I never heard of iana, is that now the official place for these things.

In terms of adding statements to other peoples URIs I would have thought that as long as we don’t change the meaning we should be ok.  I think I can say that dbpedia:Lourve gist:geoLocatedIn geonames:Paris without violating depedia.  I think if I said dbpedia:Louvre rdf:type gist:Person that would be a bit over the line.

What is the use case for having mimeTypes / mediaTypes?  I was thinking for the few that we natively support (csv, excell, txt, word, ppt, pdf) that we would know how to process them.  Not sure what to do with the several thousand others

On May 17, 2021, at 11:18 AM, Boris Pelakh ***@***.******@***.***>> wrote:


@mkumba<https://github.com/mkumba> There was extensive debate about this issue, and your input was requested. I followed the approach @Jamie-SA<https://github.com/Jamie-SA> and I favored, which was to create annotations for existing IANA media type pages by adding types and labels.

@rjyounes<https://github.com/rjyounes> and some others said we should not be creating statements using entities we do not own as subjects, and suggested I follow this pattern instead:

gist:_MediaType_TextHtml
    a gist:MediaType;
    gist:uniqueText "text/html";
    owl:sameAs iana:text\/html .


Creating a duplicate instance in the gist namespace for each of the media types. Do you have strong feeling in either direction?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/semanticarts/gist/pull/477

Commit Summary

  *   Rename MimeType to MediaType, create ontology to declare instances.
  *   Clean up labels and namespaces.

File Changes

  *   M bundle.yaml<https://github.com/semanticarts/gist/pull/477/files#diff-73c670418fb192fb77d3a1c95ada8448ee256f1a6afa0e6ede380a7c63221184> (2)
  *   M docs/ReleaseNotes.md<https://github.com/semanticarts/gist/pull/477/files#diff-53d9d97604b51916cd0e08d61a4e86d6357b9a672ee28c624df8aca4ec50647d> (17)
  *   M gistCore.ttl<https://github.com/semanticarts/gist/pull/477/files#diff-39a54dbf6b089d1dd97252ccc000763b9f2d81a08fa49fa8403933b547d23b40> (19)
  *   A gistMediaTypes.ttl<https://github.com/semanticarts/gist/pull/477/files#diff-004dbdee8ec4ae7cad8aaae285da1f7fb245d391782264ff2c2aa0d621cde171> (93)

Patch Links:

  *   https://github.com/semanticarts/gist/pull/477.patch
  *   https://github.com/semanticarts/gist/pull/477.diff

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/semanticarts/gist/pull/477>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAAGJPVQ6DSAXYUVYQPXRVDTOFFYDANCNFSM45A34JOA>.

2021-05-17 20:33 UTC, sa-bpelakh commented
@mkumba IANA appears to be the master clearing house for registered media types, of which there are MANY. I picked a subset specifically relevant to any application that deals with semantic graphs (all RDF formats, all SPARQL result formats, and a few common text formats, such as `text/plain`), but any gist user would be free to follow the pattern and extend it to whichever media types are relevant to their use case - our unit list is not exhaustive either 😄 . And I absolutely agree that as long as the assertion is reasonable, asserting facts about external entities (such media types) is not wrong.

2021-05-17 20:35 UTC, sa-bpelakh commented on gistMediaTypes.ttl
> +	a gist:MimeType ;
Corrected, and expanded `ontologyShapes` to make sure this doesn't happen again. Prior to the fix, build validation reported the following:
```
ERROR:root:SHACL verification produced non-empty results:
Focus                                                                          Path     Value         Severity     Message
<https://www.iana.org/assignments/media-types/application/json>                rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/application/ld+json>             rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/application/n-quads>             rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/application/n-triples>           rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/application/rdf+xml>             rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/application/sparql-results+json> rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/application/sparql-results+xml>  rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/application/trig>                rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/text/csv>                        rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/text/html>                       rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/text/plain>                      rdf:type gist:MimeType sh:Violation Instance references undefined class.
<https://www.iana.org/assignments/media-types/text/turtle>                     rdf:type gist:MimeType sh:Violation Instance references undefined class.
```

2021-05-19 02:31 UTC, Jamie-SA approved these changes

2021-05-27 14:57 UTC, rjyounes requested changes
Requesting minor typographical changes.

2021-05-27 14:57 UTC, rjyounes commented on gistMediaTypes.ttl
> +	skos:prefLabel "gistMediaTypes"^^xsd:string ;
Our convention dictates that `prefLabel`s are human readable - I.e., in this case, "gist media types" or "gist Media Types" rather than "gistMediaTypes."

2021-05-27 14:57 UTC, rjyounes commented on ontologyShapes.ttl
> +	rdfs:label "Instance"^^xsd:string ;
Why are we using `rdfs:label` as well as `skos:prefLabel`? 

I would prefer a convention in which we use "Shape" in the label of a shape: I.e., in this case "Instance Shape" rather than "Instance." Thoughts?

2021-05-27 14:57 UTC, rjyounes commented on ontologyShapes.ttl
>  	skos:definition "Enforces Lower Case, allowing for all-caps words for acronyms, as well as numbers."^^xsd:string ;
As per convention: "Enforces lower case." That is, "Lower Case" should be lower case.

2021-05-27 15:18 UTC, sa-bpelakh commented on gistMediaTypes.ttl
> +	skos:prefLabel "gistMediaTypes"^^xsd:string ;
I just followed the pattern of `gistCore`, which has a label of (surprisingly) `gistCore`. Should both be adjusted?

2021-05-27 15:26 UTC, sa-bpelakh commented on gistMediaTypes.ttl
> +	skos:prefLabel "gistMediaTypes"^^xsd:string ;
As per issue review discussion, will modify both labels.

2021-06-01 16:37 UTC, rjyounes approved these changes

2021-06-01 17:49 UTC, merged