Domain range includes
semanticarts/gist pull request #479
Opened 2021-05-19 22:04 UTC by uscholdm

Addressing issue #389

2021-05-19 23:42 UTC, sa-bpelakh approved these changes
Changes look fine, that's actually very useful. Small suggestion on release notes.

2021-05-19 23:42 UTC, sa-bpelakh commented on docs/ReleaseNotes.md
> +- Added two annotation properties and uses: Issue [#389](https://github.com/semanticarts/gist/issues/389)
Consider expanding the description a little, something along the lines of 'Added annotation properties which provide usage guidance for properties without the constraints imposed by `rdfs:range` and `rdfs:domain`'

2021-05-20 01:46 UTC, uscholdm commented on docs/ReleaseNotes.md
> +- Added two annotation properties and uses: Issue [#389](https://github.com/semanticarts/gist/issues/389)
Good idea. I just made the change.

2021-05-25 19:47 UTC, rjyounes requested changes

2021-05-26 00:25 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "The domain for the property, gist:basedOn includes gist:Template."^^xsd:string ;
- There is a separate issue for deciding how we want to use these domain/rangeIncludes properties (https://github.com/semanticarts/gist/issues/480). 
- There is also a separate issue to improve annotations for basedOn and basisFor (https://github.com/semanticarts/gist/issues/139)

I removed the `rangeIncludes` triple for `basedOn` and added one for `parentOf`, as you suggested.

2021-05-26 00:28 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "The domain for the property, gist:basedOn includes gist:Template."^^xsd:string ;
That's a hell of a nit!

2021-05-26 00:51 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "This property means the same thing as the schema.org version which is not compliant with OWL-DL"^^xsd:string ;
> Are you mentioning Schema's non-compliance with OWL-DL as a way of explaining why we aren't using the Schema property? Since it's an annotation, does it matter?

Yes, its an `rdf:Property` in schema.org.  Here it is in all its splendor:

```
schema:rangeIncludes a rdf:Property ;
    rdfs:label "rangeIncludes" ;
    rdfs:comment "Relates a property to a class that constitutes (one of) the expected type(s) for values of the property." ;
    schema:domainIncludes schema:Property ;
    schema:isPartOf <https://meta.schema.org> ;
    schema:rangeIncludes schema:Class .

```

2021-05-26 00:52 UTC, uscholdm commented on docs/ReleaseNotes.md
> +### Minor Updates
Done.

2021-05-26 02:32 UTC, sa-bpelakh commented on docs/ReleaseNotes.md
> +### Minor Updates
Is that true, though, @rjyounes ? A patch update, per semver, is fixing an existing element. While Michael's change is only annotation properties which don't affect reasoning, they _are_ a new feature, and thus are a minor-level change.

2021-05-26 16:27 UTC, uscholdm commented on docs/ReleaseNotes.md
> +### Minor Updates
Good point. I changed it, but can change it back. What does @rjyounes have to say?

2021-05-26 21:15 UTC, rjyounes commented on docs/ReleaseNotes.md
> +### Minor Updates
Interesting. I see we do not explicitly cover this case in https://github.com/semanticarts/gist/blob/develop/docs/ChangeAndReleaseManagement.md, where we say "Minor: New, backward-compatible functionality." Depends on what you mean by "functionality."

@marksem What do you have to say?

2021-05-26 21:20 UTC, rjyounes requested changes
Two minor changes. I'd like to hear @marksem's take on the patch vs minor update issue, then once that's resolved we're good to go.

2021-05-26 21:20 UTC, rjyounes commented on gistCore.ttl
> +		"This property is used to guide the ontology user, like all annotation properties, it do not play a role in inference."^^xsd:string ,
Punctuation and a typo: the correct version is "This property is used to guide the ontology user; like all annotation properties, it does not play a role in inference."

2021-05-26 21:20 UTC, rjyounes commented on gistCore.ttl
> +		"This property is used to guide the ontology user, like all annotation properties, it do not play a role in inference."^^xsd:string ,
Same issue here: "This property is used to guide the ontology user; like all annotation properties, it does not play a role in inference."

2021-05-27 17:48 UTC, rjyounes approved these changes

2021-05-28 13:38 UTC, rjyounes commented
Closed by mistake: meant to merge and close.

2021-05-28 13:39 UTC, merged

2021-05-28 21:15 UTC, rjyounes commented
We concluded in the gist issue review meeting that addition of annotations is a minor change because it is an addition. Created new issue #488 to document this.