Refactor Ordered Collections. Fixes #112.
semanticarts/gist pull request #495
Opened 2021-06-24 16:55 UTC by daliadahleh

2021-06-25 00:47 UTC, uscholdm requested changes
A small fix and a couple of suggestions.

2021-06-25 00:47 UTC, uscholdm commented on gistCore.ttl
> +
How about adding the following:
```
	skos:scopeNote "Used to link members of ordered collections to the main item that can appeear in different places in different ordered collections."^^xsd:string ;
```

2021-06-25 00:47 UTC, uscholdm commented on gistDeprecated.ttl
> +gist:OrdinalCollection
Add the following to these newly deprecated terms, as in the others.
`owl:deprecated "true"^^xsd:boolean ;`

2021-06-25 00:47 UTC, uscholdm commented on gistCore.ttl
> +
Also, how about adding an examples file as I did when playing around on my own. See the branch: 
`feature\issue112-MFU-ordered-member-test` in the origin.

See the file `gistExamplesOrderedMembers.ttl` in the `examples` folder. BorisP and I started doing this at Platts. Very helpful, just communicating internally.

2021-06-25 15:35 UTC, daliadahleh commented on gistCore.ttl
> +
Examples are a good idea. Did we decide on a place for usage examples? I know it's been discussed but I don't know if we've reached a decision.

2021-06-25 19:01 UTC, rjyounes requested changes
I'm happy to discuss any of the proposed changes if you would like to.

2021-06-25 19:06 UTC, uscholdm commented on docs/ReleaseNotes.md
This is a good alternataive.

2021-06-25 19:39 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "The subject is used as a proxy, or substitute, for the object."^^xsd:string ;
> Need to state domain Ordered Member.

This reduces the use of isProxyFor for other things.  I prefer not to do that. 

Need to resolve as group before merge PR.

2021-06-25 19:43 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "An inverse functional version of hasMember to ensure that no OrderedMember can be in more than one OrderedCollection."^^xsd:string ;
> The range of `hasOrderedMember` should be stated as `OrderedMember`.

This breaks our policy of not including the range in the meaning of a property.  I suggest to say `hasOrderedItem` with no range and then locally have a range in the restriction for the definition of `OrderedCollection`.

2021-06-25 20:00 UTC, rjyounes commented
@daliadahleh: @uscholdm and I have been discussing the domain/range issue and we disagree. We think this should be brought to the group before the PR is merged. I will put it on the top of the agenda for the next meeting.

2021-06-28 00:32 UTC, sa-bpelakh requested changes
Just a few minor things, @uscholdm and @rjyounes got most of it.

2021-06-28 00:32 UTC, sa-bpelakh commented on gistCore.ttl
> +	] ;
@rjyounes @daliadahleh Should we not remove the `someValuesFrom`? The `allValueFrom` enforces the object type on the property, and removing `someValuesFrom` allows for an empty collection.

2021-06-28 00:32 UTC, sa-bpelakh commented on gistCore.ttl
> +	skos:definition "A member of an Ordered Collection. It either precedes or is preceded by another Ordered Member in the same collection, or it has a stated integer position in the collection."^^xsd:s
I would use 'linking a member of a collection to that collection' to bypass the 'real-world item' awkwardness.

2021-06-28 00:32 UTC, sa-bpelakh commented on gistCore.ttl
> +	skos:definition "The subject is used as a proxy, or substitute, for the object."^^xsd:string ;
I agree, leave the property general. Add  a `owl:cardinality 1` for `isProxyFor` on `OrderedMember`?

2021-07-01 13:48 UTC, daliadahleh commented on gistCore.ttl
> +	skos:definition "A member of an Ordered Collection. It either precedes or is preceded by another Ordered Member in the same collection, or it has a stated integer position in the collection."^^xsd:s
@sa-bpelakh that seems confusing because the class name (and the first sentence of the definition) suggests that the proxy is the 'member', while your definition suggests that the real-world item is the 'member'. I think 'real-world item' is clearer.

2021-07-01 14:38 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "An inverse functional version of hasMember to ensure that no OrderedMember can be in more than one OrderedCollection."^^xsd:string ;
While I agree with the general principle, I disagree in this particular case. This is a self-contained model, and this predicate is specifically used to link the collection to the proxy. Can you provide examples of other contexts where this predicate would be used _with the same meaning_?

2021-07-01 14:40 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "The subject is used as a proxy, or substitute, for the object."^^xsd:string ;
Same response as above: While I agree with the general principle, I disagree in this particular case. This is a self-contained model, and this predicate is specifically used to link the ordered member  to the thing it's a proxy for. Can you provide examples of other contexts where this predicate would be used _with the same meaning_? We don't really want people using it for, say, legal proxies, do we? That's not the same thing at all, despite using the same word "proxy." I don't think this principle of not overspecifying usage should lead to predicates that don't have a particular meaning at all.

2021-07-01 14:46 UTC, rjyounes commented on gistCore.ttl
> +	] ;
@uschold and I discussed the possibility of empty sets and opened a new issue to raise the question: https://github.com/semanticarts/gist/issues/498. In theory I'm in favor of allowing empty collections, but we noted that if we allow empty collections, then the restriction must also be removed from `Collection` (`gist:hasMember some owl:Thing`), which leaves it as a class without a formal definition.

2021-07-01 18:06 UTC, rjyounes requested changes
Fix one typo and consider another change to the `someValuesFrom` restriction.

2021-07-01 18:06 UTC, rjyounes commented on gistCore.ttl
> +				owl:someValuesFrom gist:OrderedMember ;
This is a bit nuanced: the `someValuesFrom` statement makes it appear that we are restricting the range for this class, which we are not, since the range is already defined on the predicate. There are two ways to do indicate the cardinality in a less misleading way:

`owl:someValuesFrom owl:Thing`

and
`owl:minCardinality "1"^^xsd:nonNegativeInteger`

I prefer the second way as more straightforward and find the first odd. @uscholdm  prefers the first way because he prefers `someValuesFrom` to `minCardinality` for reasons that I don't fully agree with. I'd say it's your choice. Maybe @uscholdm will have something to say here.

2021-07-01 18:06 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Empty collections are not supported at the time."^^xsd:string ;
"at this [not the] time"

2021-07-01 18:57 UTC, daliadahleh commented on gistCore.ttl
> +				owl:someValuesFrom gist:OrderedMember ;
I'll go with the second. When I see owl:Thing I assume it specifically shouldn't be restricted to one class.

2021-07-02 13:09 UTC, sa-bpelakh approved these changes
Looks good, thanks for steering this barge into the port 👏

2021-07-02 23:40 UTC, uscholdm requested changes

2021-07-02 23:40 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "A member of an ordered collection. This resource serves as a proxy linking a real-world item in the collection to that collection, allowing the expression of positional and other in
> linking a real-world item in the collection to that collection,

Confusing wording, it does not seem to be saying what we want it say. Why does an item that is already in a collection need to be linked to that same collection?

2021-07-07 13:52 UTC, daliadahleh commented on gistCore.ttl
> +	skos:definition "A member of an ordered collection. This resource serves as a proxy linking a real-world item in the collection to that collection, allowing the expression of positional and other in
How about 'This resource serves as a proxy that represents an item in the collection to allow the expression of positional and other information that applies to the item only in the context of the collection'?

2021-07-07 15:29 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "A member of an ordered collection. This resource serves as a proxy linking a real-world item in the collection to that collection, allowing the expression of positional and other in
I still think the phrase "an item in the collection" causes confusion, since it's technically only the proxy that's in the collection. 
How about "A member of an ordered collection. This resource links an item to a collection and allows the expression of positional and other information that applies to the item only in the context of the collection."?

2021-07-07 18:06 UTC, uscholdm requested changes
The fact that defining OrderedMember is so difficult to do well, is all the more reason to get it as good as we can.

2021-07-07 18:06 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "A member of an ordered collection. This resource serves as a proxy linking a real-world item in the collection to that collection, allowing the expression of positional and other in
This is annoyingly difficult to do well. Here is one more attempt. The example is from the IMF.

```
skos:definition "A member of an ordered collection. It is a proxy for a real world item that can appear in different orders in different collections. The ordered member appears in exactly one ordered collection."

skos:scopeNote "An ordered member points to the real world item via the providesOrderFor property and has ordering information either as a number in a sequence, or by preceding or following another ordered member."^^xsd:string ;  

skos:example "A document template may have parts such as table of contents, introduction, main body, appendix etc, but not all documents have all parts.  The appendix might be the third part of one document template, but the 5th part of another. This would correspond to one instance of DocumentPart for an appendix, and two instances of ordered member."^^xsd:string ; 
```

2021-07-07 19:30 UTC, rjyounes commented
I think Michael has mostly nailed it. I propose a couple of tweaks:

```
skos:definition "A member of an ordered collection that serves as a proxy for a real world item, which can appear in different orders in different collections. The ordered member appears in exactly one ordered collection."

skos:scopeNote "An ordered member points to the real world item via the providesOrderFor property and represents ordering information either as a number in a sequence, or by preceding or following another ordered member.  The ordered collection is linked to the ordered member via the property hasOrderedMember. The ordered member may also represent data about the real world item that applies to it only in the context of the ordered collection."

skos:example "A person may rank 12th in the Boston Marathon but 29th in the New York City Marathon."
```

Michael, I've provided a different example which I think is more straightforward and easier to understand. See what you think. We could of course include both.

2021-07-07 23:51 UTC, uscholdm commented
Yes, much better example. Below is a slightly revised version. I split a long sentence in the scope note into two. I also got rid of the last sentence. First, I found it confusing. When I realized what it says, it kind of goes without saying, once the idea is grasped, which is hard enough. If we insist on saying it, then we need to have a compelling example that somehow does not add more complexity and confusion.  Even if it was a good example, it still may not be worth saying.  Less is more.  See also the variation at the end.
```
skos:definition "A member of an ordered collection that serves as a proxy for a real world item, which can appear in different orders in different collections. The ordered member appears in exactly one ordered collection."

skos:scopeNote "An ordered member points to the real world item via the providesOrderFor property.  Ordering information is represented either as a number in a sequence, or by preceding or following another ordered member.  The ordered collection is linked to the ordered member via the property hasOrderedMember."

skos:example "A person may rank 12th in the Boston Marathon but 29th in the New York City Marathon."
```

**VARIATION**: I moved last sentence of definition to first sentence of scope note and replaced it with a new sentence, which I think captures the essence.  The scope note is rewriten to exactly echo the last sentence in the definition.

```
skos:definition "A member of an ordered collection that serves as a proxy for a real world item, which can appear in different orders in different collections. An ordered member exactly corresponds to a particular item in a particular order in a particular (ordered) collection."

skos:scopeNote "An ordered member points to the real world item via the providesOrderFor property. It is linked to exactly one ordered collection via the hasOrderedMember property.    Ordering information is represented either as a number in a sequence, or by preceding or following another ordered member."

skos:example "A person may rank 12th in the Boston Marathon but 29th in the New York City Marathon."
```

_Why was this so fricking hard to do well?_

2021-07-08 18:37 UTC, rjyounes approved these changes

2021-07-08 18:58 UTC, uscholdm commented
I saw that Dalia made changes to the annotations, but they were not the latest draft.  Can @rjyounes and @daliadahleh have a look to see what we want to go with?

2021-07-08 19:06 UTC, daliadahleh commented
@uscholdm, the annotations are from your latest draft. I used the first variation in [your latest comment ](https://github.com/semanticarts/gist/pull/495#issuecomment-876008994).

2021-07-08 19:10 UTC, rjyounes commented
I'm happy to go with this. @uscholdm please give the final go-ahead.

2021-07-08 20:43 UTC, uscholdm commented
> the annotations are from your latest draft. I used the first variation

I prefer the second variation. Can you say what you prefer about the first?

2021-07-08 21:10 UTC, daliadahleh commented
I thought 'An ordered member exactly corresponds to a particular item in a particular order in a particular (ordered) collection' is unnecessarily wordy. The point comes across just as clearly in the first variation. I'm not too picky though, happy to go with either.

2021-07-08 22:52 UTC, uscholdm commented
> I thought 'An ordered member exactly corresponds to a particular item in a particular order in a particular (ordered) collection' is unnecessarily wordy.

I think I agree, at least for the definition. We could just remove that sentence all together, or put it in the scope note.

Its Rebecca's call. I'm not too bothered either way.

2021-07-13 15:20 UTC, rjyounes commented
Let me look at it. It's not actually correct to say it corresponds to a particular item "in a particular order." It is linked to the same item regardless of the order. It will just change its properties (sequence or directlyPrecedes) accordingly.

2021-07-13 16:55 UTC, uscholdm commented
OK - maybe its just helpful to me as a way to think about it, but confusing otherwise.  Probably best to just leave that verbiage out.

2021-07-14 16:48 UTC, merged