Add Address as range for fromPlace/toPlace. Fixes #392
semanticarts/gist pull request #502
Opened 2021-06-30 12:44 UTC by sa-bpelakh

2021-06-30 18:49 UTC, uscholdm requested changes

2021-06-30 18:49 UTC, uscholdm commented on docs/ReleaseNotes.md
> +- Relaxed the range of `fromPlace`/`toPlace` to use an `gist:Address` in addition to `gist:Place`.
I would say "extended the range" rathe than relaxed.  More direct.

2021-07-14 19:32 UTC, uscholdm approved these changes

2021-07-14 19:33 UTC, rjyounes commented
@sa-bpelakh Need to resolve conflicts in release notes.

2021-07-14 20:19 UTC, merged