Addressing multiple issues for v10.0.0. Fixes #126, #136, #171, #174.
semanticarts/gist pull request #503
Opened 2021-07-02 15:53 UTC by sa-bpelakh

- Renamed `decimalValue` to `numericValue`
- Changes to `Person`, including `name` and `hasBirthDate`
- Refactored network connections, renaming properties and tightening up their definition
- Clarified definition of `ContemporaneousEvent`

Tagging @Jamie-SA for `numericValue`, the usual suspects for the rest.

2021-07-02 19:23 UTC, rjyounes requested changes
I've proposed some annotation changes, although they aren't included in the decisions made on the issues, because I always scan these and make corrections when I'm working on a term. I find the current network-related ones quite confusing; and in fact I believe were the source of our confusion about how these terms should be used.

Everything else looks good.

2021-07-02 19:23 UTC, rjyounes commented on gistCore.ttl
> +
As I recall, the lack of clarity in these definitions was part of the reason we had to puzzle out the meaning of all the network-related terms. How about something along these lines:

```
gist:links
skos:definition "Relates a NetworkLink to a NetworkNode that it connects to another node. Used when the connections are undirected, or the direction is not known."

gist:linksFrom
skos:definition "Relates a NetworkLink to the NetworkNode in which it originates. Unlike the superproperty, this represents a directed connection."


gist:linksTo 
skos:definition "Relates a NetworkLink to its destination node. Unlike the superproperty, this represents a directed connection."
```
These are rough and I'm sure you could improve them, but I think at least they convey they meaning better.

2021-07-03 23:39 UTC, Jamie-SA approved these changes
gist:numericValue looks good.
One comment below that can be ignored.

2021-07-03 23:39 UTC, Jamie-SA commented on gistCore.ttl
> +			owl:rational
It is interesting that the serialization tool does not order these items in the union.

2021-07-04 01:20 UTC, sa-bpelakh commented on gistCore.ttl
> +			owl:rational
Because an `rdf:List` is an ordered collection, it's not free to reorder. I will sort the list when I address Rebecca's comments.

2021-07-05 15:16 UTC, sa-bpelakh commented on gistCore.ttl
>  	skos:definition "A link in a network.  This is the abstraction of the network.  The physical instantiation couple be pipes, or wire  but may also be non physical such as wireless networks or organiz
I expanded the definitions and comments, using your text as a starting point. A wireless network is still definitely physical, so adjusted for that.

2021-07-05 15:17 UTC, sa-bpelakh commented on gistCore.ttl
>  	skos:scopeNote "All contemporaneous events eventually end and, due to the nature of the open world, we can never be sure that a contemporaneous event hasn't ended. As a result, this is really a cont
Removed

2021-07-05 15:18 UTC, sa-bpelakh commented on docs/ReleaseNotes.md
> +- Changes to and affecting `gist:Person` ([#136](https://github.com/semanticarts/gist/issues/136)):
It's a little problematic due to the sub-list that follows. Adjusted - see if it's clearer.

2021-07-05 17:16 UTC, sa-bpelakh commented on gistCore.ttl
> +				owl:qualifiedCardinality "2"^^xsd:integer ;
Added.

2021-07-05 17:16 UTC, sa-bpelakh commented on gistCore.ttl
>  	skos:definition "A node in a network.  Note the network is the abstract representation of the network.  It is physically instantiated with equipment, or in some cases People."^^xsd:string ;
Indeed, updated. I used valve as an example of a pipe network node.

2021-07-05 17:25 UTC, sa-bpelakh commented on gistCore.ttl
> +
Added w/ slight edits.

2021-07-07 13:41 UTC, rjyounes requested changes
Everything looks good except for one missing period. I do not need to re-review after it's added.

2021-07-07 13:41 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "A network is a set of nodes connected by links"^^xsd:string ;
I hate to be this nit-picky, but a period should be added at the end of the definition.

2021-07-08 00:29 UTC, uscholdm requested changes
The current versions (on github, but not showing up on this web page) look fine, but for one small thing. Replace `Unlike the superproperty, links,` with  `Unlike its superproperty, links, ` 

If you strongly object with having links mentioned, I won't be that bothered. I like it because it saves having to look at the code, which is kind of the point of a definition.

2021-07-08 18:35 UTC, rjyounes approved these changes

2021-07-14 14:50 UTC, sa-bpelakh commented on gistCore.ttl
> +	skos:definition "A network is a set of nodes connected by links"^^xsd:string ;
Done

2021-07-14 19:30 UTC, uscholdm approved these changes

2021-07-14 19:32 UTC, rjyounes commented
@sa-bpelakh Need to resolve conflicts in release notes.

2021-07-14 19:50 UTC, merged