Refactor physical addresses, Fixes #483
semanticarts/gist pull request #508
Opened 2021-07-14 14:46 UTC by sa-bpelakh

I also added validation that super/inverse properties have to be the same type as the source property (i.e. ObjectProperty can't have a DatatypeProperty as a super-property). I did _not_, however, mandate that the parent or inverse are defined, in case we are referencing a property defined elsewhere. Let me know if this is something we want to enforce - it would prevent referencing an unresolved URI due to a typo. Might want to also add referential integrity checks for classes at some point (e.g. `subClassOf` or `disjointWith`).

2021-07-14 17:57 UTC, rjyounes commented
@sa-bpelakh Can you please resolve the conflicts with the release notes before I review the PR? Thanks.

2021-07-14 20:24 UTC, sa-bpelakh commented
@rjyounes @uscholdm All merge conflicts have been resolved, and the PR is now ready for review.

2021-07-14 21:14 UTC, rjyounes requested changes
I've made a bunch of suggestions for better annotations. I'm also wondering if we should not define inverses of new predicates. In general we do not encourage defining inverses, so I don't see any reason to define ones we don't already have just for the sake of symmetry.

2021-07-14 21:14 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "A place that can be found on a map, has geo coordinates; you could live or work there."^^xsd:string ;
This isn't right. It's not a place, it's the _address_ of a place. The definition should also be verbal rather than nominal. Something along the lines of "Relates a physical place to a reference used to locate it."

2021-07-14 21:14 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "Whose address is this"^^xsd:string ;
Definition should be: "Relates an address to the thing it is used to locate."
Add an example to clarify along the lines of "A street address is the address of a building; an email address is the address of a person or organization."

2021-07-14 21:14 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "Whose communication address is this"^^xsd:string ;
Same objection to the wording of the definition as above for `isAddressOf`.

2021-07-14 21:14 UTC, rjyounes commented on gistCore.ttl
> +	skos:prefLabel "communication address of"^^xsd:string ;
prefLabel is "is communication address of"

2021-07-14 21:14 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "Whose physical address is this"^^xsd:string ;
Same comment about definition as for the others.

2021-07-14 21:47 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "Whose communication address is this"^^xsd:string ;
Its a bit fiddly to go look and apply the other change in the new situation. How about just spell it out.

2021-07-14 21:49 UTC, uscholdm commented
> In general we do not encourage defining inverses, so I don't see any reason to define ones we don't already have just for the sake of symmetry with the ones we already have.

I agree. No inverse properties unless there is a specific reason to have them. I was telling this to the Dupont folk at ontology training today!

2021-07-14 22:03 UTC, uscholdm commented on docs/ReleaseNotes.md
> +    - Defined super-property `hasAddress` (and inverse `isAddressOf`)
hasPhysicalAddress has range StreetAddress, which is in turn defined as an address found in the physical world, which pretty much just means PhysicalAddress.  I agre with @rjyounes that a PO box can be found in the physical world. It may be that the post office has a clear definition of 'street address' which if consistent with international practice, we should use. Not all addresses are on streets, Alaska has home only accessible by boat. We might just define PhysicalAddress and not StreetAddress.

2021-07-14 22:05 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "Unlike the superclass, this does not include pseudo-addresses such as PO Box or FPO code."^^xsd:string ;
> Then change the scope note to "Unlike the superclass, this does not include PO or FPO addresses."

Explicitly call out the superclass, i.e. PostalAddress

2021-07-14 22:20 UTC, uscholdm requested changes

2021-07-14 22:20 UTC, uscholdm commented on docs/ReleaseNotes.md
> +        - The newly named versions are no longer sub-properties of `hasParty`
Minor point: There is no need for the dash, 'subproperty' is commonly used and is in the Wiktionary. https://en.wiktionary.org/wiki/subproperty 

The dash version looks odd and will probably go the way of the dodo in time. The dashed version might be appropriate in real estate, but not OWL.

2021-07-14 22:20 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "A location where a person or organization can receive messages including postal addresses, fax numbers, phone numbers, email, web site, etc."^^xsd:string ;
The property represents a relationship, it is not a location. Reword more like: `relates a person organization to where they can receive messages ...`

2021-07-14 22:20 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "A place that can be found on a map, has geo coordinates; you could live or work there."^^xsd:string ;
Agree, it is not a place. But it might not be relating the location to its address. I am not a location, but I have a physical address (well maybe not, I live in a building which is a place which has  a physical address, so maybe @rjyounes 's suggestion is fine.

2021-07-14 22:20 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "Whose address is this"^^xsd:string ;
Moot, if we don't want inverses.

2021-07-14 22:20 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "Whose physical address is this"^^xsd:string ;
Its not clear where to go look unless I've already been there and have a good memory.  Maybe spell it out?

2021-07-15 13:11 UTC, rjyounes commented on docs/ReleaseNotes.md
> +    - Defined super-property `hasAddress` (and inverse `isAddressOf`)
There is a concept of a delivery address that excludes PO boxes etc. E.g., certain retailers will not ship to PO boxes. However, @uschold's example of addresses not on streets is a good one. I don't think we need to be in the business of defining who will deliver to what kind of address and what the postal service regards as what kind of address. Defining `PhysicalAddress` rather than `StreetAddress` is a good idea, IMO.

2021-07-15 13:12 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "A place that can be found on a map, has geo coordinates; you could live or work there."^^xsd:string ;
@uschold I think you're pointing at the distinction between `hasAddress` and `hasCommunicationAddress`. My building has an address. That address is my communication address.

2021-07-15 13:14 UTC, rjyounes commented on docs/ReleaseNotes.md
> +        - The newly named versions are no longer sub-properties of `hasParty`
If "subproperty" is in the dictionary I'd go with that.

2021-07-15 15:36 UTC, rjyounes commented
At gist issue review meeting, we agreed that removing "pseudo-address" from the scope note and specifying "fixed physical address" in the definition and scope note addresses the problems.

2021-07-15 15:38 UTC, sa-bpelakh commented
How about
```
	skos:definition "An address which can be found at a fixed location in the physical world."^^xsd:string ;
	skos:scopeNote "Unlike the superclass, this does not include postal address which are not associated with a fixed location, such as PO Box or FPO code."^^xsd:string ;
```

2021-07-15 15:51 UTC, rjyounes commented
Note that an address is a reference, not a place. Proposed 

DECISION:

1. Annotations for class `StreetAddress`:
```
skos:definition "An address which references a fixed location in the physical world."
skos:scopeNote "This excludes addresses not associated with a fixed location, such as a PO box or FPO code."
```
2. Remove `hasPhysicalAddress`. This will just be implied by the object of `hasAddress.` Note that `hasCommunicationAddress` should be defined independently, since it applies to a person or organization, not just physical places.

2021-07-19 14:24 UTC, rjyounes commented
@sa-bpelakh I found a couple of good examples of non-building  street addresses in related issue #301: cemeteries and campgrounds. You might include these in the `skos:example` of `StreetAddress`.

2021-07-23 14:22 UTC, sa-bpelakh commented on docs/ReleaseNotes.md
> +        - The newly named versions are no longer sub-properties of `hasParty`
sub-property is the commonly used from, while Wiktionary has `subproperty` because of its Computer Science uses, Merriam Webster does not have that form.

2021-07-23 16:27 UTC, rjyounes requested changes
Two minor typographical fixes, otherwise all good.

2021-07-23 16:27 UTC, rjyounes commented on docs/ReleaseNotes.md
> +    - Clarified the definition of `hasCommunicationAddress` (which is now a sub-property of `hasAddress`,
Missing right paren. Should be:

(which is now a sub-property of `hasAddress`), 

I believe we decided we would follow dictionary usage and use the unhyphenated version "subproperty," while retaining the hyphen in "super-property."

2021-07-24 02:33 UTC, uscholdm commented
> I did _not_, however, mandate that the parent or inverse are defined, in case we are referencing a property defined elsewhere. Let me know if this is something we want to enforce - it would prevent referencing an unresolved URI due to a typo.

It might be worth keeping as a warning, not an error, since much or most of the time it would not be intended.

2021-07-24 02:34 UTC, uscholdm commented
I closed the PR accidentally, then reopened immediately.

2021-07-24 02:55 UTC, uscholdm requested changes
Add two things to release notes. Otherwise looks good.

2021-07-24 02:55 UTC, uscholdm commented on docs/ReleaseNotes.md
> +- Modified classes and properties related to street addresses as per issue [#483](<https://github.com/semanticarts/gist/issues/483>):
We also 
- updated annotations for ContemporaneousEvent
- removed communicationAddressOf

2021-07-24 15:51 UTC, sa-bpelakh commented on docs/ReleaseNotes.md
> +    - Clarified the definition of `hasCommunicationAddress` (which is now a sub-property of `hasAddress`,
Done

2021-07-24 15:54 UTC, sa-bpelakh commented on docs/ReleaseNotes.md
> +- Modified classes and properties related to street addresses as per issue [#483](<https://github.com/semanticarts/gist/issues/483>):
ContemporaneousEvent is mentioned in the 'patch' section, since it was just an annotation change. Added a noted about communicationAddressOf.

2021-07-26 15:20 UTC, uscholdm approved these changes

2021-07-27 13:56 UTC, rjyounes approved these changes

2021-07-27 13:56 UTC, merged