Local and endpoint migration for renamed and removed entities.
semanticarts/gist pull request #554
Opened 2021-09-05 19:09 UTC by sa-bpelakh

This is in anticipation of #535, based on the most recent version.

In order to run these, you will need to make sure that [onto-tool](https://pypi.org/project/onto-tool/) is upgraded to v1.4.1.

I ran the local migration using the following command:
```bash
onto_tool bundle -v input test-migration -v output test-migration/migrated -v report test-migration/report migration/v10.0/migrate_local.yaml
```
which updates all `.ttl` and `.owl` files in the `input` directory (not recursively, is that an issue?) and places the updated RDF in the `output` directory. ValidationReport RDF is placed in the `report` directory.

To run the migration against a SPARQL endpoint:
```bash
onto_tool bundle -v user USER -v password PWD -v endpoint https://agraph.semanticarts.com/catalogs/demo-catalog/repositories/ci-test -v report test-migration/endpoint-report migration/v10.0/migrate_endpoint.yaml
```

For databases where the UPDATE endpoint is different, it can be provided via `-v update_endpoint URI` in addition to the query endpoint provided via `-v endpoint`.

Do we want to include detailed documentation for the migration in the release notes of each major release, since users will not have access to our Confluence pages?

2021-09-09 15:00 UTC, rjyounes commented on migration/v10.0/action_rename_classes_default.rq
> +}
Why do we have both `action_rename_classes.rq` and `action_rename_classes_default.rq` and similarly for properties?

2021-09-09 15:25 UTC, rjyounes commented on migration/v10.0/detect_removed.rq
> +                gist:TemmplateTask
Typo

2021-09-09 15:26 UTC, rjyounes commented on migration/v10.0/detect_removed.rq
> +                gist:hasA
duplicate

2021-09-09 17:45 UTC, sa-bpelakh commented on migration/v10.0/action_rename_classes_default.rq
> +}
We do renaming in two steps:
1. First rename everything that is in a named graph, retaining the modified triples in their original graphs, and then
2. Rename all that is remaining, which would be in the default graph
We do it in this manner because the default graph does not have a universally recognized reference URI, and in some triple stores it doesn't have a URI at all. Also, when processing local file data, there are no named graphs, so only the default queries (which don't specify a graph) are used.

2021-09-09 17:45 UTC, sa-bpelakh commented on migration/v10.0/detect_removed.rq
> +                gist:TemmplateTask
Done

2021-09-09 17:45 UTC, sa-bpelakh commented on migration/v10.0/detect_removed.rq
> +                gist:hasA
Good catch

2021-09-09 20:13 UTC, Jamie-SA commented on migration/v10.0/action_rename_classes_default.rq
> +}
A local .trig or N-quads file can have named graphs. I assume that works correctly for them as well.

2021-09-09 20:26 UTC, sa-bpelakh commented on migration/v10.0/action_rename_classes_default.rq
> +}
@Jamie-SA There is no current support in onto-tool for .trig or .nq inputs. Do you view this as a deal breaker for this functionality? There is no way I can code and test this before Monday

2021-09-10 16:29 UTC, Jamie-SA commented on migration/v10.0/action_rename_classes_default.rq
> +}
It is not a deal breaker for me, I had assumed the library you use to read/write would support all of the main formats. But if not, I wouldn't hold this up because of it.

I have switched almost entirely to .trig because of it's support for named graphs.

2021-09-10 19:00 UTC, sa-bpelakh commented on migration/v10.0/action_rename_classes_default.rq
> +}
The toolkit (`rdflib`) does support it, but I have not enabled it - and there is an existing issue (https://github.com/semanticarts/ontology-toolkit/issues/65), to which I will give some attention after this release.

2021-09-10 19:57 UTC, Jamie-SA commented on migration/v10.0/detect_removed.rq
> +    bind(<urn:deleted-entity-vaidation-report> as ?report)
Minor typo: 
```suggestion
    bind(<urn:deleted-entity-validation-report> as ?report)
```

2021-09-10 21:41 UTC, sa-bpelakh commented
@rjyounes Please read over my documentation. @bolerio Should be good to go as soon as @rjyounes approves the verbiage.

2021-09-13 14:04 UTC, rjyounes requested changes
Looks great except for one or two suggested rewordings in the documentation. Use at your own discretion.

2021-09-13 14:04 UTC, rjyounes commented on docs/MajorVersionMigration.md
> +where _INPUT-DIR_ is the directory in which your RDF data is located, _OUTPUT-DIR_ is the directory where
Can you indicate whether the directories have to exist in advance, or will they be created if they don't exist? Or is that too obvious to state?

2021-09-13 19:27 UTC, bolerio commented
Thanks @sa-bpelakh  and @rjyounes .

@rjyounes , waiting on your final approval to merge and seal the release.

2021-09-13 19:32 UTC, sa-bpelakh commented
@rjyounes Adjusted documentation as per your suggestions

2021-09-13 21:00 UTC, rjyounes approved these changes

2021-09-14 02:37 UTC, merged