Dylan + Jess attempt at renaming instances and adding the gistx namespace.
semanticarts/gist pull request #575
Opened 2021-09-23 21:36 UTC by JessSing

Please let us know if we did this correctly and if this was the correct process.

There is also the deprecated terms file that was added as well.

2021-09-24 04:23 UTC, uscholdm requested changes
Mostly right on the money. Suggested a few IRI changes based on de facto conventions that were never blessed by the gist dev team.  

I wonder if we want a separate taxo file like we usually do with the instances. Bring this to the group.
@rjyounes: what do you think?

2021-09-24 11:51 UTC, rjyounes commented
@uscholdm I don't like the use of `milli_second`. "Millisecond" is a word and should be used as such. Ditto for "kilogram" and others.

More importantly, I'd like to propose that we use the most specific and rigid class, _including inferred classes_, as the infix. That means, e.g., `gist:_USDollar` should become `gist:_CurrencyUnit_UsDollar` rather than `gist:_BaseUnit_UsDollar`. This seems to me more meaningful than using `BaseUnit` as the infix. But what do you think of the general proposal to include inferred classes in the mix?

2021-09-24 11:52 UTC, rjyounes commented on gistCore.ttl
>  			]
I like dropping "TimeZone" from the end, but why are we not using UTC? I.e., `gist:_TimeZoneStandard_UTC`.

2021-09-24 11:53 UTC, rjyounes commented on gistCore.ttl
> +			gistx:_BaseUnit_US_Dollar
+1 to `_dollar_US`.

2021-09-24 12:00 UTC, rjyounes commented
@uscholdm Re separate taxo file: This was raised in  [issue #474 ](https://github.com/semanticarts/gist/issues/305), and rejected for the reasons discussed there.

The `gistx` namespace is still under review (issue #305) so should not be implemented here.

2021-09-24 12:03 UTC, sa-bpelakh commented
@rjyounes I like the idea of using the more specific infix, but I am concerned of how it may get in the way of ETL where unit references are automatically generated.

2021-09-24 12:08 UTC, rjyounes commented on gistCore.ttl
> +gistx:_Duration_one_minute
My conclusion from reading these comments is that we have not yet settled on the names to use. Based on the comments above from @uscholdm and @sa-bpelakh, I proposed the following:

```
gist:_ElectricalCurrentUnit_ampere
gist:_DataSizeUnit_bit
gist:_LuminousIntensityUnit_candela
gist:_DurationUnit_day
gist:_CountingUnit_each
gist:_TimeZoneStandard_UTC (NB our instance naming conventions require standard capitalization)
gist:_TemperatureUnit_kelvin
gist:_MassUnit_kilogram
gist:_DistanceUnit_meter
gist:_DurationUnit_millisecond
gist:_DurationUnit_minute
gist:_MoleUnit_mole
gist:_Duration_day
gist:_Duration_millisecond
gist:_Duration_minute
gist:_DurationUnit_second
gist:_CurrencyUnit_dollar_US

2021-09-24 12:11 UTC, rjyounes commented
@sa-bpelakh Can you clarify how using more specific units would get in the way when ETL is used? Note that we already assert a specific unit class for the non-base units - e.g., `gist:_minute` is a DurationUnit.

If the crucial difference is between the inferred vs asserted type, I propose we assert all the specific types. Though logically redundant, it's much clearer when reading the ontology.

2021-09-24 12:16 UTC, sa-bpelakh commented
I was talking about automatic URI minting, e.g. 
```
BIND(tarql:expandPrefixedName(CONCAT('gistx:_BaseUnit_', ?unitFromCSV)) as ?unitRef)
```
though the mapping is rarely that simple.

2021-09-24 16:57 UTC, rjyounes commented on gistCore.ttl
> +gistx:_Duration_one_minute
@uschold and @rjyounes now propose using `_UnitOfMeasure_` as infixes on all, in order to avoid the ETL problems mentioned by Boris. We both think this is preferable to `_BaseUnit_`.

2021-09-24 16:59 UTC, rjyounes commented
Closing this PR because the issue (#556) needs further group review.

2021-09-24 16:59 UTC, closed without merging

2021-09-24 18:14 UTC, uscholdm commented on gistCore.ttl
>  			]
> I like dropping "TimeZone" from the end, but why are we not using UTC? I.e., `gist:_TimeZoneStandard_UTC`.

I like UTC also.

2021-09-24 18:20 UTC, uscholdm commented on gistCore.ttl
> +gistx:_Duration_one_minute
> It seems redundant that `gistx:_Duration_one_day`, `gistx:_Duration_one_millisecond` and `gistx:_Duration_one_minute` include the `one` in the URI.

The problem is that gist incorrectly takes the position that a unit of measure is NOT also a magnitude, as specified in the formal literature, as pointed out by Ted. So in order to distinguish millisecond the unit from millisecond the duration, a 'one' was inserted into the IRI.  This was discussed at length and we decided to leave it as it is, but I think it should be reconsidered, especially in light of Ted's information (see #443).

2021-09-24 18:47 UTC, rjyounes commented
@sa-bpelakh If there are potential ETL problems using the most specific unit type, why aren't there also problems using the `_BaseUnit_` infix rather than `_UnitOfMeasure_`? Seems like we might need to use the latter to completely avoid any problems.

2021-09-24 18:49 UTC, rjyounes commented on gistCore.ttl
> +gistx:_Duration_one_minute
@uscholdm Now that we are adding the infix, "one" is not needed to make the distinction.

I am with you on the false distinction between units of measure and magnitude, but this may be a losing battle.

2021-09-27 17:38 UTC, uscholdm commented on gistCore.ttl
> +gistx:_Duration_one_minute
> I am with you on the false distinction between units of measure and magnitude, but this may be a losing battle.

Interestingly, we may get this back. Dave indicated an openness to it at one point, if I understood correctly.  Mike Poole agrees with it too (i think).

2021-09-27 17:43 UTC, uscholdm commented on gistCore.ttl
> +gistx:_Duration_one_minute
> @uschold and @rjyounes now propose using `_UnitOfMeasure_` as infixes on all, in order to avoid the ETL problems mentioned by Boris. We both think this is preferable to `_BaseUnit_`.

The more specific unit can often (always?) be inferred from the axioms.  If we want, we could directly assert those `rdf:type` statements.  e.g. 
`gist:_UnitOfMeasure_mile rdf:type gist:DurationUnit`

2021-09-27 18:04 UTC, uscholdm commented on gistCore.ttl
> +gistx:_Duration_one_minute
> @uscholdm Now that we are adding the infix, "one" is not needed to make the distinction.

Excellent point! Had not thought of that.