Improving definitions for 'navigational' predicates. Fixes #523.
semanticarts/gist pull request #611
Opened 2022-01-04 20:49 UTC by dylan-sa

2022-01-04 22:48 UTC, rjyounes requested changes
The wording of these annotations, and a better distinction between definitions and scope notes, needs to be thought through more carefully.

2022-01-04 22:48 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "Used in cases where the child category is not necessarily an instance of the parent category but it is useful to represent the relationship hierarchically. Supports polyhierarchies.
* A scope note could start with "Used in..." but a definition should not. 
* I don't see a need to mention poly-hierarchies here. 
* Can we make explicit mention of facets?

2022-01-04 22:48 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "Refrigerator handles are not refrigerators, but it may be useful in some contexts (e.g., within a user interface) them to fall under the refrigerators category."^^xsd:string ;
* You're missing "for" before "them."
* Can we say something like "in faceted UI filters"?

2022-01-04 22:48 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "Refrigerator handles are not refrigerators, but it may be useful in some contexts (e.g., within a user interface) them to fall under the refrigerators category."^^xsd:string ;
Same as above.

2022-01-04 22:48 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "Used in cases where the child category has a unique parent that it is not necessarily an instance of but it is useful to represent the relationship hierarchically."^^xsd:string ;
Awkward wording. This needs to be smoothed out to be comprehensible.

2022-01-05 19:28 UTC, dylan-sa commented
@rjyounes All good points. I am pushing some changes to address. I have re-worked the `skos:definition`s so that they are now closer to proper distinctionary definitions. The definitions are now unique to each property and indicate directionality. (@wslooney gets credit for some of the improvement here.)

2022-01-14 17:31 UTC, rjyounes approved these changes

2022-01-14 17:31 UTC, merged