Clean up annotations and local names in Dave's new time model
semanticarts/gist pull request #619
Opened 2022-01-26 23:05 UTC by rjyounes

2022-01-27 17:19 UTC, rjyounes commented
Anyone who wants to review in addition to the assigned reviewers, please do!

I've added a few `skos:editorialNotes` to weigh in on.

2022-01-28 00:42 UTC, mkumba approved these changes
I'm having a heck of a time figuring out how and where to put comments, hope this is it.

I'm good with changes.  In terms of the editorial notes that were in the presentation and didn't make the file, yeah I think that's a good idea.  

Also on the question of atDateTime being just gist:dateTime I'm ok with that.

2022-01-28 13:17 UTC, rjyounes commented
@mkumba @marksem @DanCarey404: @uscholdm and I both think `CurrentEvent` is preferable to and clearer than `ContemporaryEvent`, and I've made that update to the file. Please comment if you don't like it.

2022-01-28 15:30 UTC, uscholdm commented
I suggest using "OngoingEvent" because a very recent event will generally be regarded a current. The term 'current event' refers to a general time period not whether the event is still happening.  E.g. a trial that was just completed, its over but it's in the news and is regarded as a current event.

2022-01-28 15:41 UTC, rjyounes commented
@uscholdm I think I agree with you. However, does "ongoing" lend a sense of continuing over some significant period of time? E.g., I am currently stopped at a red light, but I wouldn't call that an ongoing event. Is this too much of a quibble?

2022-01-28 16:10 UTC, rjyounes commented
I think the advantage of Contemporary is it contrasts more naturally with Historical. But I'm OK with Contemporary, Ongoing, or Current, whatever others prefer.

2022-01-28 17:44 UTC, uscholdm commented
Let's hope the event of discussing this is not ongoing for too much longer :-)

2022-02-02 13:06 UTC, rjyounes commented
Question: If the date predicates have precision +/- 12 hours, shouldn't the minute predicates have precision +/- 30 seconds rather than 1 minute?

2022-02-03 15:14 UTC, bpelakh commented
Just a voice from the peanut gallery, but it's about time (heh) that this change was made. 👍

2022-02-03 15:46 UTC, rjyounes commented
@bpelakh Since this is a public repository, you would have been welcome to submit a PR!

2022-02-04 15:13 UTC, DanCarey404 commented
I went with the term "contemporary" because I had an essentially boolean category :Contemporaneity.  And I had that because there was no real word for "currentness".  I prefer contemporary or current, but not ongoing.

2022-02-04 15:16 UTC, DanCarey404 commented
I used :atDateTime versus just :dateTime because the latter looks too much like a datatype, in my opinion.  Also, the subproperties I have created in my projects feel more natural with the "at" included.  :startAtDateTime, validateAtDateTime, changeAtDateTime, etc.

2022-02-04 15:38 UTC, rjyounes commented
@DanCarey404 Regarding the property names, datatype property names are nouns by convention, and `startDateTime` is a noun, whereas `startAtDateTime` is verbal. It's also less awkward, IMO. I had the same thought about `gist:dateTime` but Dave thought it was fine, and I wanted to keep the names parallel. I'd be OK with `gist:atDateTime` and `gist:startDateTime`, though.

2022-02-07 13:41 UTC, DanCarey404 commented
This property name is definitely not a hill to die on.  I just wanted to explain the origin in case anyone found it persuasive.

2022-02-10 18:54 UTC, uscholdm requested changes
See inline.  A few key things.
- there is some stuff in this PR that belongs elsewhere - how did it get here?
- need more details in release notes

2022-02-10 18:54 UTC, uscholdm commented on gistDeprecated.ttl
> +
ContemporaneousEvent should be deprecated.

2022-02-10 18:54 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "Square meter, an area unit."^^xsd:string ;
Why is this showing up in this PR?  Makes it  harder to review.

2022-02-10 18:54 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "Humans require air; solar power requires sunshine."^^xsd:string ;
Why this PR?

2022-02-10 18:54 UTC, uscholdm commented on docs/ReleaseNotes.md
> +- Implemented new time model based on datatype properties rather than `TimeInstant`, which has been deleted. Issue [#499](https://github.com/semanticarts/gist/issues/499).
Suggest adding something like this:

- Changed the way to refer to dates and times by moving precision information from subclasses of `TimeInstant` to a new set of subproperties of a generic `atDateTime` datatype property.
  - Previously, we used the class `TimeInstant` and its subclasses to refer to points in time with different precisions, e.g. day, minute microsecond.  We used object properties to connect things to points in time.  
  - We have removed the class `TimeInstant` and converted the time properties to datatype properties.  We added versions of the time properties for different precisions: date, minute, and microsecond. We retained properties that distinguish start vs. end, and planned vs. actual.    
  - We reationalized the naming of the properties and the annotations describing them.
  - We renamed ContemporaneousEvent to ContemporaryEvent

2022-02-11 15:36 UTC, rjyounes commented on docs/ReleaseNotes.md
> +- Implemented new time model based on datatype properties rather than `TimeInstant`, which has been deleted. Issue [#499](https://github.com/semanticarts/gist/issues/499).
Good, thanks. I've adopted with adaptations.

2022-02-11 15:37 UTC, rjyounes commented on gistDeprecated.ttl
> +
We do not deprecate in a major release. In fact, all existing deprecations are removed.

2022-02-11 15:39 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "Square meter, an area unit."^^xsd:string ;
Something weird happened in the merge from develop and I had to recreate some changes from earlier PRs.

2022-02-11 17:23 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "Humans require air; solar power requires sunshine."^^xsd:string ;
Between develop not having been merged into Dave's branch, and some rebase problems, a number of changes from previous merges got into this PR. Unfortunate, but it would be too difficult to fix now.

2022-02-14 18:01 UTC, rjyounes commented
Closing this PR because history has gotten screwed up. Have re-opened as PR #629 with a clean history.

2022-02-14 18:01 UTC, closed without merging