Removing min cardinality of zero restriction on ProductUnit. Fixes #582.
semanticarts/gist pull request #621
Opened 2022-01-27 21:04 UTC by JessSing

Added scopeNote to use SHACL if needed.

Also updated release notes.

2022-01-27 23:07 UTC, rjyounes requested changes
Jess, please also add a note to the release notes. This is a patch fix.

2022-01-27 23:07 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Base conversion factor must be a nonzero value; use SHACL for data validation as needed."^^xsd:string ;
That's not the meaning of the minQualifiedCardinality restriction. It is a hint that `ProductUnit` should have a value for `baseConversionFactor`. What we want to say in the scope note is:

It is intended that a ProductUnit will have a value for baseConversionFactor.

2022-02-02 19:59 UTC, JessSing commented
Updated scope note and release notes.

2022-02-03 13:37 UTC, rjyounes requested changes

2022-02-03 13:37 UTC, rjyounes commented on docs/ReleaseNotes.md
> +- Removed min cardinality of zero restriction on ProductUnit and added scopeNote, per issue [#582](https://github.com/semanticarts/gist/issues/582).
Sorry to be picky, but you can put `gist:ProductUnit` in backticks as you see in other notes. No need to mention the scope note, as it's not significant enough to call out on its own.

2022-02-03 13:37 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "A ProductUnit is intended have a (nonzero) value for baseConversionFactor."^^xsd:string ;
You need to remove the "(nonzero)" part here. What the min cardinality restriction is hinting at is that  a product unit is expected to have _a value_, without any indication of what that value should be. I.e., the 0 refers to the number of assertions, not the values asserted. Never mind that a `baseConversionFactor` of 0 makes no sense - that doesn't need to be stated here but is a general fact about the meaning of that predicate.

2022-02-03 18:49 UTC, JessSing commented on docs/ReleaseNotes.md
> +- Removed min cardinality of zero restriction on ProductUnit and added scopeNote, per issue [#582](https://github.com/semanticarts/gist/issues/582).
No I should have matched the formatting, sorry about that.

2022-02-08 16:20 UTC, rjyounes approved these changes

2022-02-08 16:21 UTC, merged