Change hasJurisdictionOver back to hasJurisdiction. Fixes #623.
semanticarts/gist pull request #640
Opened 2022-03-15 19:04 UTC by rjyounes

2022-03-16 02:08 UTC, uscholdm requested changes
The reason for the confusion is that 'hasJurisdiction' sounds like it means has jurisdiction over. Perhaps a better name would be along the lines of isGovernedByJurisdiction. Consider an alternative.

2022-03-16 02:08 UTC, uscholdm commented on gistCore.ttl
> +	skos:prefLabel "has jurisdiction"^^xsd:string ;
The reason for the confusion is that 'hasJurisdiction' sounds like it means has jurisdiction over. Perhaps a better name would be along the lines of isGovernedByJurisdiction

2022-03-16 23:03 UTC, rjyounes commented on gistCore.ttl
> +	skos:prefLabel "has jurisdiction"^^xsd:string ;
Good idea. I'll use that alternative since it seems pretty good and I can't think of a better one.

2022-03-17 14:58 UTC, rjyounes commented on gistCore.ttl
> +	skos:prefLabel "has jurisdiction"^^xsd:string ;
@uscholdm Changed name to `isUnderJurisdiction`. Not sure if it should be `isUnderJurisdictionOf`.

2022-03-20 16:31 UTC, merged