Modifications to biological parent/child predicates and related restrictions. Fixes #638.
semanticarts/gist pull request #641
Opened 2022-03-15 19:16 UTC by rjyounes

2022-03-16 02:22 UTC, uscholdm requested changes

2022-03-16 02:22 UTC, uscholdm commented on gistCore.ttl
> +				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
Do you have in mind a non-living thing that might be a parent? I prefer leave the restriction unchanged.

If you really think that is possible, then its best to use someValuesFrom owl:Thing rather than a min 1, which reduces flexibility and can cause inference problems in some cases, the ones you least expect to getcha :-)

2022-03-16 02:22 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "Not all life forms have exactly 2 parents, so the restriction only specifies a minimum of one."^^xsd:string ;
BUT: all biological parents surely are (or were) living.

2022-03-16 02:22 UTC, uscholdm commented on gistCore.ttl
> +				owl:cardinality "2"^^xsd:nonNegativeInteger ;
Is says **2** parents, but you said 1.

2022-03-16 22:55 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Not all life forms have exactly 2 parents, so the restriction only specifies a minimum of one."^^xsd:string ;
How is this relevant?

2022-03-16 22:56 UTC, rjyounes commented on gistCore.ttl
> +				owl:cardinality "2"^^xsd:nonNegativeInteger ;
A Person has two parents, but not all LivingThings do (e.g., asexual reproduction).

2022-03-16 22:58 UTC, rjyounes commented on gistCore.ttl
> +				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
I can go with `someValuesFrom` for a minCardinality, but in that case I prefer `owl:someValuesFrom owl:Thing`, since the range of the predicate is `LivingThing`. I know, we've had that discussion many times and I don't think either of us will be convinced.

2022-03-30 15:10 UTC, daliadahleh requested changes

2022-03-30 15:10 UTC, daliadahleh commented on gistCore.ttl
> +				owl:minCardinality "1"^^xsd:nonNegativeInteger ;
I agree owl:someValuesFrom owl:Thing makes sense here so that there's no redundancy.

2022-03-30 15:10 UTC, daliadahleh commented on gistCore.ttl
> +	skos:scopeNote "Not all life forms have exactly 2 parents, so the restriction only specifies a minimum of one."^^xsd:string ;
That's already taken care of with the domain and range of hasBiologicalParents. I don't think it's relevant here.

2022-04-01 14:58 UTC, merged