WIP: Scripts for local file migrations
semanticarts/gist pull request #648
Opened 2022-03-25 05:53 UTC by Jamie-SA

This is a draft PR so anyone can comment on my README or queries now if they want.

Closes #642.

I think I covered what we can in the queries
I think it is working for local files.
I wrote a very simple test file in `./input/` to be able to do some testing.

I still need to update, test, and add the endpoint yaml config file.

2022-04-01 17:47 UTC, rjyounes commented on migration/v11.0/README.md
> +by the gist team to help migrate from the previous version of gist. These
"...previous version of gist, specifically 10.0.0."

2022-04-01 17:50 UTC, rjyounes commented on migration/v11.0/input/test.ttl
> +ex:_X_4 rdf:type gist:HumanInstant ;
In gist 10, the object of `hasActualStart` is a `TimeInstant` object, not a datetime literal.

2022-04-01 17:54 UTC, rjyounes commented on migration/v11.0/detect_renamed.rq
> +        REPLACE(STR(?renamed), '^.*[/#]', ''), " was changed to gist:isUnderJurisdiction. ",
renamed to `gist:isUnderJurisdictionOf`.

2022-04-01 17:57 UTC, rjyounes commented on migration/v11.0/detect_renamed_default.rq
> +        REPLACE(STR(?renamed), '^.*[/#]', ''), " was changed to gist:isUnderJurisdiction. ",
isUnderJurisdictionOf

2022-04-01 18:04 UTC, rjyounes reviewed
You can also do an action_rename on:

hasOrderedMember -> hasMember.

It might be worth adding in the detect_removed error message that we will be providing sample triples to illustrate the model changes and how they will need to change their data.

Otherwise looks good to me.

2022-04-04 12:56 UTC, rjyounes commented
@Jamie-SA Since you wrote this we have all deleted `baseConversionFactor` and `standardConversionFactor` and use `conversionFactor` for both. Even though we have a convergence of two predicates, we can include the transformations in the migration scripts. Could you please add this?

2022-04-04 15:17 UTC, Jamie-SA commented on migration/v11.0/input/test.ttl
> +ex:_X_4 rdf:type gist:HumanInstant ;
I wasn't trying to write correct triples, I just wanted a file that had the terms that needed to be tested.

2022-04-04 15:23 UTC, Jamie-SA commented on migration/v11.0/detect_renamed_default.rq
> +        REPLACE(STR(?renamed), '^.*[/#]', ''), " was changed to gist:isUnderJurisdiction. ",
Fixed.

2022-04-04 16:03 UTC, Jamie-SA commented
I've still got a couple more things to do on this PR, but have to switch gears right now and come back to it later.

2022-04-04 19:05 UTC, rjyounes commented on migration/v11.0/README.md
> +by the gist team to help migrate from the previous version of gist. These
Either way, I don't have strong feelings.

2022-04-05 02:16 UTC, Jamie-SA commented on migration/v11.0/input/test.ttl
> +ex:_X_4 rdf:type gist:HumanInstant ;
Removed datetime literal.

2022-04-05 04:13 UTC, Jamie-SA commented
> It might be worth adding in the detect_removed error message that we will be providing sample triples to illustrate the model changes and how they will need to change their data.

I'm not sure what specifically you were referencing. Try to make suggestions for everything that changed?
That sounds like something that should be in the release notes.

2022-04-05 13:20 UTC, rjyounes commented
Yeah, never mind that last comment.

2022-04-05 14:35 UTC, rjyounes requested changes
Did you add the renaming of the conversion factor predicates I mentioned? I don't see it. Both `standardConversionFactor` and `baseConversionFactor` are renamed to `conversionFactor`.

Once that's done, I think these are good to go unless you want to do anything else.

2022-04-05 19:13 UTC, Jamie-SA commented
Sorry, missed the conversion factor renaming. I've pushed another change to include that.

2022-04-05 19:44 UTC, Jamie-SA commented
I think I am done now. Please review.

2022-04-06 17:52 UTC, rjyounes reviewed
This looks good to me. The only thing I would add to the readme is that the migrations scripts are not cumulative - I.e. someone on v9 must upgrade to v10 first and then v11. (That's what I was trying to get at when I suggested mentioning v10, but this is a more generic way to say it.)

2022-04-06 18:55 UTC, Jamie-SA commented
I made a couple more changes to address RY's last comment.

2022-04-06 19:39 UTC, rjyounes approved these changes

2022-04-06 19:51 UTC, pwin commented on migration/v11.0/detect_renamed.rq
> +        "The previous name did not match the defintion. We won't autmatically update it ",
typo - "autmatically"

2022-04-06 19:51 UTC, pwin commented on migration/v11.0/detect_renamed_default.rq
> +        "The previous name did not match the defintion. We won't autmatically update it ",
typo - "autmatically"

2022-04-06 19:55 UTC, Jamie-SA commented on migration/v11.0/detect_renamed_default.rq
> +        "The previous name did not match the defintion. We won't autmatically update it ",
Fixed.

2022-04-06 19:55 UTC, Jamie-SA commented on migration/v11.0/detect_renamed.rq
> +        "The previous name did not match the defintion. We won't autmatically update it ",
Fixed

2022-04-06 20:05 UTC, pwin approved these changes
Looks good

2022-04-06 21:00 UTC, merged