Combine standard and base conversion factor predicates into a single `conversionFactor` predicate. Fixes #624.
semanticarts/gist pull request #649
Opened 2022-03-28 14:02 UTC by wslooney

Eliminated :standardConversionFactor and :baseConversionFactor. Created :conversionFactor instead with cleaned up annotations.

Added cardinality restrictions of 1 to :UnitOfMeasure for :conversionFactor and :hasStandardUnit

Removed cardinality restriction on :hasBaseUnit in :SimpleUnitOfMeasure

2022-03-28 17:41 UTC, uscholdm reviewed
I looked at the related issue and found no mention of removing the property `baseConverstionFactor`.   I don't know if I agree with this. What as the rational for this? Was it agreed among several parties after a discussion? It so, it should be documented in the issue.

2022-03-28 17:50 UTC, wslooney commented
> 

Sorry, I thought it was documented in the Issue page (I know it's _somewhere_ maybe it was on a different page). We decided in the gist meeting on 3/24/22 that there was no need distinguish between :baseConversionFactor and :standardConversaionFactor . A unit of measure still bears the :hasStandardUnit or :hasBaseUnit property to its standard unit or base unit. It was agreed that there was nothing gained by also making that distinction in the conversionFactor to the unit.

2022-03-28 18:49 UTC, rjyounes requested changes
A couple of minor comments on wording.

2022-03-28 18:49 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "Inches should have a conversionFactor of 0.0254 in order to go from inches to meters."^^xsd:string ;
This is awkward. Something more like "The unit of measure inch is multiplied by 0.0254 to convert to the base unit meter."

The definition should mention both base and standard units, something like "The conversion factor used to convert the unit to its standard or base unit."

2022-03-28 19:08 UTC, wslooney commented on gistCore.ttl
> +	skos:example "Inches should have a conversionFactor of 0.0254 in order to go from inches to meters."^^xsd:string ;
I left the base unit part out of the definition because a BaseUnit is a StandardUnit, but I'm happy to add it in if it makes things clearer/easier to use.

2022-03-28 19:59 UTC, wslooney commented
I adopted the suggestions from @rjyounes. I also changed the `skos:prefLabel` for `gist:conversionFactor` because I had forgotten to change it earlier from "base conversion factor."

2022-03-28 20:40 UTC, wslooney commented on gistCore.ttl
> +	skos:example "Inches should have a conversionFactor of 0.0254 in order to go from inches to meters."^^xsd:string ;
I adopted the suggestions from @rjyounes. I also changed the `skos:prefLabel` for `gist:conversionFactor` because I had forgotten to change it earlier from "base conversion factor."

2022-03-29 14:00 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "Inches should have a conversionFactor of 0.0254 in order to go from inches to meters."^^xsd:string ;
I realize it's redundant but it helps to clarify things.

2022-03-29 14:10 UTC, rjyounes requested changes
Still some wording changes, and I forgot to ask you to add a line to the release notes; just follow the patterns used there. For now we'll assume this is going into 11.0.0, but we need to get approval from Michael and Dan before we can merge it, because it's a major change. (I'm not sure why the title of the PR says "minor." This is complicated. If it goes into a minor version then it's a minor change, because we keep it but deprecate it. In major versions we remove all deprecations, so then it's a major change.)

2022-03-29 14:10 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "The unit of git measure inch is multiplied by a conversion factor of 0.0254 to convert to its base unit meter."^^xsd:string ;
typo - gist not git. But it's not gist-specific, so let's leave that word out. There's still something odd about this sentence. Let's try something like this:

"A value expressed in inches is multiplied by a conversion factor of 0.0254 to express the value in the base unit, meters."

2022-03-29 14:10 UTC, rjyounes commented on gistCore.ttl
> -				owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
What got changed here?

2022-03-29 14:28 UTC, wslooney commented on gistCore.ttl
> -				owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
`:UnitOfMeasure` now how as cardinality restriction of 1 on `:hasStandardUnit` and `:SimpleUnitOfMeasure` is a subclass of `:UnitOfMeasure`. I left the restriction that `:SimpleUnitOfMeasure` `:hasBaseUnit`  `:BaseUnit` but removed the cardinality restriction because `:hasBaseUnit` is a subproperty of `:hasStandardUnit`. So the cardinality is already entailed.

2022-03-29 14:35 UTC, wslooney commented on gistCore.ttl
> +	skos:example "The unit of git measure inch is multiplied by a conversion factor of 0.0254 to convert to its base unit meter."^^xsd:string ;
What I was aiming for with the skos:example is to make sure it's clear in the example that conversionFactor is linking the unit of measure (inch) to the specific xsd:double (0.0254). I didn't want the example to wrongly suggest that the conversion factor links the magnitude to the conversion factor.

2022-03-29 14:41 UTC, wslooney commented
Sorry. Misunderstanding on my part what counts as minor/major. I'll change the subject too, to reflect that.

2022-03-29 15:23 UTC, wslooney commented on gistCore.ttl
> +	skos:example "The unit of git measure inch is multiplied by a conversion factor of 0.0254 to convert to its base unit meter."^^xsd:string ;
Adopted @rjyounes suggestion for commit 2051d3fb1ad5815727a5b5eafdc3363893986963

2022-03-31 21:14 UTC, pwin commented on gistCore.ttl
> +	skos:definition "The conversion factor used to get to the standard unit (SI unit when applicable)."^^xsd:string ;
I'm wondering if this needs a little more in the definition - e.g. that to go to the standard unit there is a multiplication of the inches value with this conversion factor.  Also, should we mention that it is reversible through division, or otherwise reversing the process of forward conversion (e.g. with the Fahrenheit to Kelvin)?

2022-04-01 03:11 UTC, wslooney commented on gistCore.ttl
> +	skos:definition "The conversion factor used to get to the standard unit (SI unit when applicable)."^^xsd:string ;
The skos:definition on the most recent commit is: "The conversion factor used to convert a unit to its standard or base unit."

This is very laconic, but, I think, sufficient. I think what's most important is that it's clear what the direction the conversion factor goes (from some unit **to** its standard unit and only to the standard unit). The word "factor" already indicates that it has to be multiplied, and the skos:example makes that clearer if needed.

I also don't think anything is gained by indicating that "x * y = z" is equivalent to "z / y = x. " But maybe there's a case where that needs to be explained that I'm not imagining. Does anyone else have thoughts?

2022-04-01 15:24 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "The conversion factor used to get to the standard unit (SI unit when applicable)."^^xsd:string ;
I don't think we need to explain that a multiplication can be reversed by division. We're not teaching 5th grade arithmetic, after all. :)

2022-04-01 15:27 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "The conversion factor used to get to the standard unit (SI unit when applicable)."^^xsd:string ;
What I do think should be made explicit is to add base - even though this is technically redundant - and not everyone knows what SI is. So along the lines of

"The conversion factor used to get to the standard unit (which could be a base unit) in the International System of Units (SI)."

2022-04-01 15:31 UTC, rjyounes requested changes
Still a couple of small questions. We can talk through them if you want.

2022-04-01 15:31 UTC, rjyounes commented on gistCore.ttl
> -				owl:qualifiedCardinality "1"^^xsd:nonNegativeInteger ;
It's also redundant to include the object in the SimpleUnitOfMeasure restriction. You can use `owl:Thing` instead.

2022-04-01 15:40 UTC, wslooney commented on gistCore.ttl
> +	skos:definition "The conversion factor used to get to the standard unit (SI unit when applicable)."^^xsd:string ;
The most recent commit does include that the conversion factor converts to standard or base unit.

2022-04-01 16:55 UTC, wslooney commented
@rjyounes OK, I see. Does this look right? The restriction should be:

```
			[
				a owl:Restriction ;
				owl:onProperty gist:hasBaseUnit ;
				owl:someValuesFrom owl:Thing ;
			]
```
What I had before was (a) semantically wrong because I used `owl:onClass` and (b) redundant for the reason you gave.

2022-04-01 17:04 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "The conversion factor used to get to the standard unit (SI unit when applicable)."^^xsd:string ;
> The conversion factor used to get to the standard unit (which could be a base unit) in the International System of Units (SI).

BTW, "Standard unit" is not a standard term for what we mean. That would be "coherent unit". We might add a scopeNote to that effect.

2022-04-01 17:13 UTC, wslooney commented on gistCore.ttl
> +	skos:definition "The conversion factor used to get to the standard unit (SI unit when applicable)."^^xsd:string ;
It is funny that gist uses the property `hasStandardUnit `with a range of `CoherentUnit`

2022-04-01 17:40 UTC, rjyounes commented
@wslooney That's what I meant, but I've changed my mind.

Now I'm looking at the full file and I see what you proposed is incorrect:

```
			[
				a owl:Restriction ;
				owl:onProperty gist:hasBaseUnit ;
				owl:onClass gist:BaseUnit ;
			]
```

You have to have a cardinality or values assertion here. This by itself is not a valid restriction.

Now I'm seeing that the definition of `hasStandardUnit` must be changed. First, given that `hasBaseUnit` is a subproperty of `hasStandardUnit`, the latter should no longer refer only to complex units. 

But it seems to be more complicated. Since I'm no expert in this area, I've done a bit of research. I had thought - and apparently the gist authors did as well - that a base unit was for a simple unit of measure and a standard unit can apply to either simple or complex units.  But from what I am reading, standard unit is a generic concept not related to any particular system of units, while base units are standard units defined by SI. SI defines _derived_ units that complex units can be reduced to, but I don't see any mention of standard units. If this is correct (which I'm not sure of), the cardinality restriction on UnitOfMeasure.hasStandardUnit is incorrect - if there are different systems of standard units, a unit of measure could in theory have different standard units.

My recommendation is that this MR include only the reduction of `baseConversionFactor` and `standardConversionFactor` to `conversionFactor` - this is uncontroversial, I think - and that we leave the other issue to our future overhaul of units and magnitudes.  [Phil Blackwood](https://github.com/philblackwood) is very knowledgeable in this area and will surely have some insight. Since we are trying to get the release out next week, we don't have time to fully sort out the issues around base and standard units.

2022-04-01 18:14 UTC, wslooney commented
I realized my initial restriction was not valid hence my comment that it was semantically wrong above.

So just to make sure I understand what to do:

1) Leave the restrictions on UnitOfMeasure and its subclasses as they were EXCEPT change restrictions on `baseConversionFactor` to `conversionFactor`
2) Reduce `baseConversionFactor` and `standardConversionFactor` to `conversionFactor`
3) Replace mentions of `baseConversionFactor` and `standardConversionFactor` that appear in some annotations.

2022-04-01 19:37 UTC, rjyounes approved these changes
Looks good!

2022-04-02 23:44 UTC, uscholdm requested changes
This is nearly good to go. A couple minor suggestions to change annotations and a suggestion which can wait till another time, if we wish.

2022-04-02 23:44 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "A ProductUnit is intended have a value for conversionFactor."^^xsd:string ;
We might want to skip this for now -- it is tangential to this PR. If we skip it, it should be added as an issue.

2022-04-02 23:44 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "The conversion factor used to convert a unit to its standard (i.e., coherent) or base unit."^^xsd:string ;
Suggest slight variation to be one of the following:
1. "The conversion factor used to convert a unit to its standard (i.e., coherent) unit."
2. "The conversion factor used to convert a unit to its standard (i.e., coherent) unit (which could be a base unit.)"

2022-04-02 23:44 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "A value expressed in inches is multiplied by a conversion factor of 0.0254 to express the value in the base unit, meter."^^xsd:string ;
Add a non-base unit example such as:
`skos:example "The area expressed as 7 square kilometers is multiplied by a conversion factor of one million which results in 7 million square-meters."^^xsd:string ;`

2022-04-03 00:56 UTC, wslooney commented on gistCore.ttl
> +	skos:scopeNote "A ProductUnit is intended have a value for conversionFactor."^^xsd:string ;
Thanks for raising this. I agree this should be changed, but I think it gets us back into stuff that I changed then changed back, i.e., the two restrictions that should just be on `UnitOfMeasure`. For some both restrictions are in `SimpleUnitOfMeasure`. Here one of the restrictions (but not the one on `hasStandardUnit`) in `ProductUnit` is just noted in an annotation rather than being semantically encoded. In `RatioUnit` it's not even annotated. It's kind of a mess.

I think a new issue should be raised that was originally part of the one this addressed for fixing the restrictions on `ProductUnit`.

2022-04-03 00:59 UTC, wslooney commented on gistCore.ttl
> +	skos:example "A value expressed in inches is multiplied by a conversion factor of 0.0254 to express the value in the base unit, meter."^^xsd:string ;
Is the suggestion to add a second skos:example or to replace the one already here? I'm reading you as requesting to add a second skos:example. I just wanted to make sure.

2022-04-03 17:04 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "A value expressed in inches is multiplied by a conversion factor of 0.0254 to express the value in the base unit, meter."^^xsd:string ;
Yes. Add a second example to show two cases: base unit and non-base unit.  It could be a second skos:example annotation, or it could be rolled into one. I don't know if we have a convention on that yet. Look for other uses of skos:example to see if we are doing anything consistent there.  If not, then ontologist's choice!

2022-04-03 17:06 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "A ProductUnit is intended have a value for conversionFactor."^^xsd:string ;
Yes, it should be a new issue.

2022-04-04 13:00 UTC, rjyounes requested changes
We are still missing a release note.

2022-04-04 13:08 UTC, wslooney commented
@rjyounes It seemed like the only way I could edit the release notes was to create a branch. I had done that, but just gave that branch a more conspicuous name. Not sure what the procedures are for editing the notes (do I create a PR and assign people?)

https://github.com/semanticarts/gist/tree/Release-Note-Edit-ConversionFactor

2022-04-04 13:13 UTC, wslooney commented
Sorry, new to github. Dylan told me I should just edit the release notes on **this branch**. Which in hindsight is obvious.

2022-04-04 13:32 UTC, wslooney commented on gistCore.ttl
> +	skos:example "A value expressed in inches is multiplied by a conversion factor of 0.0254 to express the value in the base unit, meter."^^xsd:string ;
I have made the changes @uscholdm quested but without the hyphen in square meter.

I don't love the way the skos:examples are phrased because both examples are phrased in a way that makes it sound like the conversion factor is applied to a specific magnitude rather than a unit, but my previous attempts to make a skos:example that didn't sound that way ended up with fairly tortured English.

2022-04-04 13:47 UTC, rjyounes commented
@wslooney The conversion factor is _defined on_ a unit but _applied to_ a magnitude, wouldn't you say?

2022-04-04 14:08 UTC, wslooney commented
@rjyounes It's a very minor point and I trust yours and Michael's instincts on what is or isn't misleading in an annotation. Given what you've said, I think what we have is good.

It's an interesting question whether or not you can multiply an inch. _Prima facie_ I would have thought you could because units like quarter-inches or inches squared suggest we do, but it's above my proverbial paygrade.

2022-04-04 14:24 UTC, rjyounes commented
Interesting point. Nevertheless, in the case of conversion factor we are not multiplying the unit, but the magnitude of _n_ inches.

2022-04-04 15:27 UTC, merged