Develop carey
semanticarts/gist pull request #654
Opened 2022-04-06 21:37 UTC by DanCarey404

Added TimeRelatedChanges_v11.md

2022-04-06 22:19 UTC, uscholdm requested changes
This is very good material. I did not have a chance to read it in detail.  I hope to get to that soon.
One initial thought is to simplify the presentation of the example. It's a bit confusing explaining all the decisions to be made. I suggest to start with one straightforward conversion. Then say, by the way, this assumes that you want X. But if you want Y, you would need to do it this other way.  Do that for each of the decisions. then summarize at the end.

2022-04-06 22:19 UTC, uscholdm commented on migration/v11.0/TimeRelatedChanges_v11.md
> +Second, the new sub-properties give you the semantic distinctions between atart and end date-times, and planned vs actual.
Typo: 'atart' --> 'start'

Second is really second and third, they are quite different things.

2022-04-07 12:36 UTC, rjyounes approved these changes

2022-04-07 12:40 UTC, rjyounes commented
I fixed the typo. The review came in too late to make substantive changes, as the PR had to be ready for merge by EOD yesterday.

2022-04-07 12:40 UTC, merged

2022-04-07 13:10 UTC, uscholdm commented
That makes sense.

2022-04-07 15:04 UTC, rjyounes commented
@uschold We can consider substantive changes in the next release. You could enter an issue if you want to pursue those.