Adding new property `hasFirstMember`. Resolves #549.
semanticarts/gist pull request #667
Opened 2022-05-06 16:12 UTC by dylan-sa

2022-05-06 21:18 UTC, rjyounes commented on gistCore.ttl
> +
This looks nearly perfect. We didn't mention this at the meeting, but it occurs to me you could also add a restriction on `OrderedCollection` to the effect that it is either empty or has a first member. (Note that due to OWA the first member doesn't have to be stated.)

A little nitpicky, but most commonly I see the OWA spelled "Open World Assumption" rather than the hyphenated lowercase version, though I know this is also used.

2022-05-13 19:55 UTC, dylan-sa commented on gistCore.ttl
> +
For `OrderedCollection`, maybe something like the following would work? If so, should I go ahead and include in this PR?

```
gist:OrderedCollection
	a owl:Class ;
	owl:equivalentClass [
		a owl:Class ;
		owl:intersectionOf (
			gist:Collection
			[
				a owl:Restriction ;
				owl:onProperty gist:hasMember ;
				owl:allValuesFrom gist:OrderedMember ;
			]
			[
				owl:unionOf (
					[
						owl:complementOf [
							a owl:Restriction ;
							owl:onProperty gist:hasMember ;
							owl:someValuesFrom gist:OrderedMember ;
						] ;
					]
					[
						a owl:Restriction ;
						owl:onProperty gist:hasFirstMember ;
						owl:someValuesFrom gist:OrderedMember ;
					]
				) ;
			]
		) ;
	] ;
```

2022-05-13 19:55 UTC, uscholdm approved these changes

2022-05-13 19:58 UTC, rjyounes commented
The complement is not correct: you need to use owl:Thing instead of gist:OrderedMember to say that the set has no members. Otherwise the complement includes things which have objects other than OrderedMembers as members.

2022-05-13 19:58 UTC, rjyounes requested changes
See comments.

2022-05-13 20:03 UTC, dylan-sa commented
@rjyounes Ah, that's right! I will go ahead and work the correct version into the PR.

2022-05-13 20:16 UTC, uscholdm commented on gistCore.ttl
> +
I'm not sure I follow; it looks like it is literally saying the following:
```
skos:definition "A collection that only has ordered members and either has a first member that is an ordered member or has no members that are ordered members."^^xsd:string ; 
```

Is this your intention? A slightly simpler alternative to complement would be to use max cardinality of 0

2022-05-13 20:20 UTC, uscholdm commented
> Which makes me realize that `hasFirstMember` should be declared a functional property.

good point.

2022-05-13 20:57 UTC, dylan-sa commented
I have no objection to going the functional route, but in #549 it looks like we wanted to allow for "first-place ties," so to speak.

2022-05-14 13:54 UTC, rjyounes commented
Good point, you're right, we do want first place ties, so not functional.

2022-05-14 20:24 UTC, rjyounes commented
But it now occurs to me that it's an _inverse_ functional property, since each OrderedMember belongs to a unique OrderedCollection and points to a unique object.

2022-05-16 18:55 UTC, uscholdm commented
I think that's right, given an ordered member is just the proxy for the real thing.

2022-05-17 22:06 UTC, dylan-sa commented
OK, I think the latest two commits get it right. `hasFirstMember` is now inverse functional, and I've tweaked the restriction for `OrderedMember` in line with discussion above. (Namely, I went with the 'cardinality 0' construction over the clunky 'complement' construction.) If this looks good, I will rebase to catch up with the latest changes to develop.

2022-05-26 11:50 UTC, rjyounes requested changes
Everything you've done is perfect. Can you add one sentence to the scope note along the lines of "Since ordered collections may not be strictly ordered, there can be more than one first member." 

After that it's good to go.

2022-05-26 17:07 UTC, merged