Update definition of gist:Building. Fixes #482.
semanticarts/gist pull request #673
Opened 2022-05-13 14:33 UTC by rjyounes

2022-05-13 19:35 UTC, uscholdm requested changes

2022-05-13 19:35 UTC, uscholdm commented on gistCore.ttl
> +	skos:example
Maybe add yurt, which is a nice example of relatively permanant. Some are put up and taken down seasonally - but that still counts as relatively permanent, to me.

2022-05-13 19:36 UTC, rjyounes commented
I'm not sure why these other changes are showing up...

2022-05-13 19:38 UTC, rjyounes commented on gistCore.ttl
> +	skos:example
I think yurt may be a controversial case, so I'm going to leave it out as subject to user interpretation.

2022-05-13 19:39 UTC, merged

2022-05-13 20:08 UTC, rjyounes commented
I made a bad mistake - I submitted a PR to merge into master rather than develop. This is the result of working with another client that doesn't use a develop branch and merges directly to master, so I'm in the habit of doing that. I need to undo the merge to master and fix things again.

I also forgot release notes...

2022-05-14 20:28 UTC, rjyounes commented
The merge to master has been undone.