Issue 590 tasks and templates
semanticarts/gist pull request #691
Opened 2022-06-26 14:31 UTC by uscholdm

2022-06-26 17:45 UTC, rjyounes requested changes

2022-06-26 17:45 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Note that this definition differs from the ordinary sense of a project which is something to do. Project here, means the event of doing the work."^^xsd:string ;
...ordinary sense of 'project', which is something to do. Here, project means...

2022-06-26 17:45 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "The event of a task that has already been planned to occur at a given time. When it was scheduled, it would have been in the future, but now might be in the past."^^xsd:string ;
I don't know what 'event of a task' means. How about 'the event of executing a task..' or 'the execution of a task'?

2022-06-26 17:45 UTC, rjyounes commented on gistCore.ttl
> -	skos:scopeNote "Note that this differs from the ordinary sense of 'task,' which is not an event (e.g., 'A piece of work to be done or undertaken.')."^^xsd:string ;
You could also add for increased clarity that the other meaning is captured by TaskTemplate.

2022-06-26 17:45 UTC, rjyounes commented on gistCore.ttl
>  gist:TaskTemplate
In TaskTemplate, we could add a scope note to the effect that the actual execution of the TaskTemplate (which is an event) is captured in Task and its subclasses.

2022-06-27 00:29 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "The event of a task that has already been planned to occur at a given time. When it was scheduled, it would have been in the future, but now might be in the past."^^xsd:string ;
I thought about that, but that is a different sense of 'task'. I'I think best to just keep it simple and say: `A task that has already...` in the skos:definition, and let the scope note clarify.

2022-06-27 00:35 UTC, uscholdm commented on gistCore.ttl
> -	skos:scopeNote "Note that this differs from the ordinary sense of 'task,' which is not an event (e.g., 'A piece of work to be done or undertaken.')."^^xsd:string ;
good idea, I did that

2022-06-27 00:37 UTC, uscholdm commented on gistCore.ttl
>  gist:TaskTemplate
agreed

2022-08-26 12:37 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "The event of a task that has already been planned to occur at a given time. When it was scheduled, it would have been in the future, but now might be in the past."^^xsd:string ;
Fixed

2022-09-08 14:52 UTC, Jamie-SA commented on gistCore.ttl
> +	skos:altLabel "Scheduled Task Execution"^^xsd:string ;
This looks identical to the prefLabel. Is it needed?
```suggestion
```

2022-09-25 20:45 UTC, rjyounes requested changes
In addition to my inline comments, this needs a release note.

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Note that this definition differs from the ordinary sense of 'project', which is something to do. Here, project execution means the event of doing the work."^^xsd:string ;
I don't think the `scopeNote` is relevant any longer. It was used when the name of the class was `Project`.

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Note that this differs from the ordinary sense of 'task' which is something to do. Here task refers to the event of doing the work."^^xsd:string ;
I don't think the `scopeNote` is relevant any longer. It was used when the name of the class was `ScheduledTask`.

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Note that, task execution refers to the event of doing the work which differs from the ordinary sense of 'Task,' as 'something to to'.  For the latter, consider using the class: Task
I don't think the `scopeNote` is relevant any longer. It was used when the name of the class was `Task`. In any case, the comma after "Note that" should be removed.

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "An outline of a task of a particular type which is the basis for executing such tasks."^^xsd:string ;
Need comma before "which."

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +		"God"^^xsd:string
WHAT?? I don't get it. Plus, is this going to be controversial/offensive?

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Use gist:isBasedOn to link the object made from the template back to the template."^^xsd:string ;
"Object" doesn't seem right because, as in `TaskTemplate`, the execution is not an object in the ordinary sense. I don't have a suggestion off the top of my head.

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +	rdfs:domain gist:TaskExecution ;
Now the property name is off. I've proposed in issue #733 what we eliminate the property and just use `hasDirectPart`, given that the object is a `TaskExecution`. Not sure if we want something as bulky as `hasDirectSubTaskExecution`, but possibly confusing otherwise. What do you think?

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +	gist:domainIncludes
Did this get here from another PR? It's OK, I'm not going to worry about fixing it now.

2022-09-25 20:45 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "A task execution that has already been planned to occur at a given time. When it was scheduled, it would have been in the future, but now might be in the past."^^xsd:string ;
In the definition, I would prefer the more idiomatic "the execution of a task..." Your choice ultimately.

2022-09-28 19:03 UTC, uscholdm reviewed
I accidentally started a review when I only meant to respond to comments.

2022-09-29 16:53 UTC, rjyounes commented
@rjyounes Make sure #408 is also addressed in this PR.

2022-09-30 00:58 UTC, uscholdm commented
> @rjyounes Make sure #408 is also addressed in this PR.

I did add words about made in the image, per #408. I don't know what more needs to be done. There is no DECISION specifying what is to be done.

2022-10-01 20:27 UTC, rjyounes requested changes
In addition to one remaining inline comment, you need to add a release note.

2022-10-01 20:27 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "The execution of a task that has already been planned to occur at a given time. When it was scheduled, it would have been in the future, but now might be in the past."^^xsd:string ;
I find "already" odd here, and I also think "was" works better than "has been."

2022-10-05 16:41 UTC, rjyounes requested changes
Everything looks great except for one piddly change to the release notes.

You have conflicts with the develop branch that you will need to resolve. Probably the release notes again. Also make sure that gistDeprecated gets merged properly: in addition to the duration instances from your previous PR, gist:Group should also be in there.

2022-10-05 16:41 UTC, rjyounes commented on docs/ReleaseNotes.md
> +  - Renamed Task, ScheduledTask and Project to TaskExecution, ScheduledTaskExecution and ProjectExecution, respectively.
Could you put backticks around the class names?

2022-10-05 19:18 UTC, rjyounes commented
Everything looks good.

2022-10-05 19:18 UTC, rjyounes approved these changes

2022-10-05 19:18 UTC, merged