Make `gist:isConnectedTo` symmetric. Fixes #699.
semanticarts/gist pull request #710
Opened 2022-08-29 22:49 UTC by dylan-sa

While adding the triple to indicate that `isConnectedTo` is symmetric, I received a SHACL validation error that `owl:SymmetricProperty` is an undefined class. To address this, I have added `owl:SymmetricProperty` to the list of classes in InstanceShape within ontologyShapes.ttl.

2022-08-30 17:06 UTC, uscholdm requested changes
Add a change to the release notes, it might be a major change. Deja vu here, I thought I just sait this, but could not find a way to change my review.

2022-08-30 20:30 UTC, dylan-sa commented on ontologyShapes.ttl
> +					owl:SymmetricProperty
> Add a change to the release notes, it might be a major change. Deja vu here, I thought I just sait this, but could not find a way to change my review.

I've added the release note as a placeholder, but the question of major vs. minor in this case is a good one. While this change would affect inference in some sense, this seems like a backward-compatible change. For any triple of the form `?x gist:isConnectedTo ?y`, we will get a new triple `?y gist:isConnectedTo ?x` by inference, but these additional triples shouldn't generate inconsistencies in the way that a domain/range addition could.

2022-09-08 14:03 UTC, rjyounes approved these changes

2022-09-08 14:03 UTC, rjyounes commented on ontologyShapes.ttl
> +					owl:SymmetricProperty
Yes, that seems fine.

2022-09-08 14:10 UTC, rjyounes requested changes

2022-09-08 14:10 UTC, rjyounes commented on ontologyShapes.ttl
> +					owl:SymmetricProperty
@dylan-sa As part of this PR, could you please create a top-level `validation` folder, two subfolders, `validation_queries` and `validation_shapes`? Or some variant thereof, `queries` and `shapes`, `SPARQL_queries` and `SHACL_shapes` - whatever seems best to you. We should keep the validation together. Unless I'm missing something.

2022-09-08 14:13 UTC, rjyounes approved these changes

2022-09-08 14:13 UTC, rjyounes commented on ontologyShapes.ttl
> +					owl:SymmetricProperty
You will also need to change the paths in `bundle.yaml`.

2022-09-08 14:13 UTC, rjyounes commented on ontologyShapes.ttl
> +					owl:SymmetricProperty
Never mind, this should be a separate PR.

2022-09-08 14:13 UTC, merged