Deprecated group and added Decprecated ttl file
semanticarts/gist pull request #742
Opened 2022-09-29 11:48 UTC by wslooney

2022-10-01 20:13 UTC, rjyounes requested changes
In addition to the inline comment, you need to add a release note. This is a minor change.

2022-10-01 20:13 UTC, rjyounes commented on gistCore.ttl
> +	owl:deprecated "true"^^xsd:boolean ;
@wslooney The class needs to be removed from gistCore. The `owl:deprecated` assertion should be added to the definition in gistDeprecated.

2022-10-03 16:04 UTC, rjyounes requested changes
It probably wasn't clear, the `gistDeprecated.ttl` file goes at the top level of the directlry, along with `gistCore.ttl. The Deprecated folder is created only by the release bundle.

Otherwise, your latest changes are good, and you still need a release note.

2022-10-04 15:11 UTC, wslooney commented
@rjyounes Thanks. I believe I have made the appropriate changes. Please check when you get the chance.

2022-10-04 18:42 UTC, rjyounes approved these changes

2022-10-04 18:49 UTC, merged