Rework names and annotations of Event and Task classes. Fixes #760.
semanticarts/gist pull request #777
Opened 2022-11-21 22:19 UTC by rjyounes

2022-11-28 16:20 UTC, dylan-sa commented on gistCore.ttl
> +		"Roughly equivalent to the Basic Formal Ontology (BFO) Process class."^^xsd:string
FWIW, I think `Event` is even closer to `Process` w/ the start and end date restrictions included. But even w/ the restrictions removed, it's still a very closely related concept. So this statement remains true.

2022-11-28 20:44 UTC, philblackwood commented
I reviewed and did not see any errors. 

Not entirely convinced ScheduledEvent is needed. Anyone needing to know if the event is scheduled can look for dates. It seems like including it just makes things more complex with no added value.

2022-11-28 22:15 UTC, rjyounes commented
@philblackwood That's a reasonable point. I would like to hang on to `ScheduledTask`, though, so that we can easily make that important distinction between proposed or planned events and those actually scheduled.

Let's see what @uscholdm thinks.

2022-11-30 15:45 UTC, rjyounes commented on gistCore.ttl
> +	rdfs:subClassOf [
Good point. I'll also use minCardinality instead of someValuesFrom.

2022-11-30 15:52 UTC, rjyounes commented on gistCore.ttl
> +	rdfs:subClassOf [
On second thought, I'm going to leave this as a subclass assertion. It seems odd to have just one object of an equivalence; we are probably going to remove `isCharacterizedAs` anyway (issue #770), and if not the domain and range need to be reconsidered.

2022-12-01 02:43 UTC, uscholdm requested changes

2022-12-01 02:43 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "A thing that could potentially be executed which is merely described but not proposed in any specific way, such as a guidebook providing instructions for following hiking trails, is
REplace 
> such as a guidebook providing instructions for following hiking trails

with 

- such as a business process for onboarding a new employee or the steps in a recipe for making a batch of Head and Shoulders shampoo or Coco Cola.

HiIlight the fact that this is a negative example.  Maybe replace outright with:

```
skos:scopeNote "Negative examples include:  a business process for onboarding a new employee,  the steps in a recipe for making a batch of Coco Cola or Head and Shoulders shampoo.  These are not events. Instead, they prescribe how events should unfold to produce intended results.  It is important to distinguish is between the thing to be done (TaskTemplate) vs. the doing of the thing (Task/Event). "^^xsd:string ;

```

I wonder what we would call DNA replication. It just happens, like the grand canyon getting carved. We can only make up and backfill an imaginary goal/intention. Like Dawkin's selfish genes that 'want' to stay around.  If there was a conscious being intending of if there was not, there is a set of 'instructions' wound be identical in every case.

2022-12-01 02:43 UTC, uscholdm commented on gistCore.ttl
> +	skos:example "A recipe for making a cake."^^xsd:string ;
Not a cake, how about shampoo or coca cola or a business process.

2022-12-01 02:43 UTC, uscholdm commented on gistCore.ttl
> +		"A task template may define a single task or a series of tasks. For example, a recipe for baking a particular type of chocolate cake may consist of sub-templates such as cracking eggs, turning on t
The juxtapositon of 'sugar' and 'granularity' is amusing.

2022-12-01 02:43 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "Relates a contingency, such as an event or obligation, to the event that gives rise to it."^^xsd:string ;
This does not sound right - what exactly is a contingent event?

2022-12-01 02:43 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "For obligations, this property describes what must happen to trigger the contingent obligation.  In most cases, before the contingent obligation becomes an actual obligation, the tri
> the triggering event is scheduled to occur in the future

Not true in the case of car theft insurance, or a house that burned down from lightnings strike. Those are triggering events for insurance obligations that are never scheduled (well maybe the crook planned to steal her neighbor's car, but that's not really a concern here.)

2022-12-01 02:43 UTC, uscholdm commented on gistDeprecated.ttl
> +				owl:cardinality "1"^^xsd:nonNegativeInteger ;
End date not necessary something to be plan

2022-12-01 02:43 UTC, uscholdm commented on gistDeprecated.ttl
> +gist:PlannedEvent
WHy is this here? The version of gistCore.ttl for this branch has no such class. Something is amiss.

2022-12-01 21:58 UTC, uscholdm commented on gistCore.ttl
>  gist:TaskTemplate
It is important to distinguish is between the thing to be done (TaskTemplate) vs. the doing of the thing (Task/Event).  So a recipe is a task template, it has many steps. But eventually the steps bottom out into atomic steps that are not templates in any common-sense sense.  In the cake example, that might be 'sift flour'. Is 'sift flour' a task template?  There are countless process modeling formalisms out there that have names for these things. A common one  for 'the thing to do' is 'activity' (E.g. BPMN). An atomic activity in BPMN is called a Task (just to be confusing). A Business PRocess is a set/network of linked activities, each of which decomposes finally into Tasks. 

I do not yet have a good alternative term or concept to address my concern. A sleight of hand way to proceed is to simply say that an atomic template that no one would call a template is just the degenerate template, just like a point is a degenerate circle with radius = 0. Noone would call a point a circle, but it can be correctly viewed as one. So maybe 'sift flour' can be correctly viewed as a task template?

We already have something in gist that closely resembles this: `gist:Behavior`

2022-12-02 03:06 UTC, mkumba commented
To me it isn't any slight of hand, sifting flour is a template for the ten times I do it including last week during 1/2 cup of King Arthur and next week sifting 3/4 cup of Bob's red Mill. First one took me 2 minutes, second one 4.

Sifting is a behaviour





Sent from my iPhone

On Dec 1, 2022, at 11:58, Michael Uschold ***@***.***> wrote:

﻿

@uscholdm commented on this pull request.

________________________________

In gistCore.ttl<https://github.com/semanticarts/gist/pull/777#discussion_r1037597121>:

> @@ -2274,8 +2266,9 @@ gist:TaskExecution
                        ]
                ) ;
        ] ;
-       skos:definition "An event characterized by a defined piece of work that is either scheduled, accomplished, or both."^^xsd:string ;
-       skos:prefLabel "Task Execution"^^xsd:string ;
+       skos:definition "An event characterized by a defined piece of work that is either proposed, planned, scheduled, underway, or completed."^^xsd:string ;
+       skos:prefLabel "Task"^^xsd:string ;
+       skos:scopeNote "A thing that could potentially be executed which is merely described but not proposed in any specific way, such as a guidebook providing instructions for following hiking trails, is not a task but rather a task template."^^xsd:string ;
        .

 gist:TaskTemplate


It is important to distinguish is between the thing to be done (TaskTemplate) vs. the doing of the thing (Task/Event). So a recipe is a task template, it has many steps. But eventually the steps bottom out into atomic steps that are not templates in any common-sense sense. In the cake example, that might be 'sift flour'. Is 'sift flour' a task template? There are countless process modeling formalisms out there that have names for these things. A common one for 'the thing to do' is 'activity' (E.g. BPMN). An atomic activity in BPMN is called a Task (just to be confusing). A Business PRocess is a set/network of linked activities, each of which decomposes finally into Tasks.

I do not yet have a good alternative term or concept to address my concern. A sleight of hand way to proceed is to simply say that an atomic template that no one would call a template is just the degenerate template, just like a point is a degenerate circle with radius = 0. Noone would call a point a circle, but it can be correctly viewed as one. So maybe 'sift flour' can be correctly viewed as a task template?

We already have something in gist that closely resembles this: gist:Behavior

—
Reply to this email directly, view it on GitHub<https://github.com/semanticarts/gist/pull/777#pullrequestreview-1201717091>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAAGJPVRKQRZJWVWVDT43Y3WLENQ7ANCNFSM6AAAAAASHDXMFY>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2022-12-02 14:16 UTC, rjyounes commented
Yes, echoing @mkumba, my thought was that "sifting flour" is a task template. There is no constraint on `TaskTemplate` regarding the level of granularity of the defined activity.

2022-12-05 13:46 UTC, uscholdm commented
> Yes, echoing @mkumba, my thought was that "sifting flour" is a task template. There is no constraint on `TaskTemplate` regarding the level of granularity of the defined activity.

Ok, that makes logical sense, just like it makes logical sense that a point is a circle of 0 radius - let's go with that for the moment.   I accept that 'sleight of hand' is not quite accurate.  Ignoring the possibility that it might cause confusion, there is still a question of what the difference is between an atomic `TaskTemplate` and a `Behavior`.  'Sifting' could be an instance of either or both.

2023-03-23 17:49 UTC, rjyounes commented on gistCore.ttl
> +		"Roughly equivalent to the Basic Formal Ontology (BFO) Process class."^^xsd:string
Removed.

2023-03-23 17:50 UTC, rjyounes commented on gistCore.ttl
> +				owl:onProperty gist:plannedEndDateTime ;
Agreed.

2023-03-23 17:56 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "Relates a contingency, such as an event or obligation, to the event that gives rise to it."^^xsd:string ;
The only thing I did here was break up the definition into definition + scope note. If you want to revise them, you can add another issue.

2023-03-23 17:56 UTC, rjyounes commented on gistDeprecated.ttl
> +				owl:cardinality "1"^^xsd:nonNegativeInteger ;
Right, but when deprecating we don't change the definition of the term.

2023-03-23 18:03 UTC, rjyounes commented on gistCore.ttl
>  gist:TaskTemplate
I've made a small modification which I think addresses this.

2023-03-23 18:05 UTC, rjyounes commented on gistDeprecated.ttl
> +gist:PlannedEvent
We've replaced `PlannedEvent` with `ScheduledEvent`.

2023-03-23 18:39 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "Renovating a kitchen, writing a book, building an ontology."^^xsd:string ;
Done.

2023-03-23 18:41 UTC, rjyounes commented on gistCore.ttl
> +				owl:cardinality "1"^^xsd:nonNegativeInteger ;
When there is an exact cardinality, we lose precision with someValuesFrom. I agree in the case of minCardinality.

2023-03-23 18:42 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Not all planned events are scheduled events. For example, a wedding can be in an early planning phase without any dates yet selected."^^xsd:string ;
Replaced with conference.

2023-03-23 18:54 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "For obligations, this property describes what must happen to trigger the contingent obligation.  In most cases, before the contingent obligation becomes an actual obligation, the tri
The only thing I did here was break up the definition into definition + scope note. If you want to revise them, you can add another issue.

2023-03-28 20:49 UTC, rjyounes commented
This PR has gone back into draft stage pending a decision about the next release.

2023-05-09 03:41 UTC, uscholdm requested changes

2023-05-09 03:41 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "Relates a contingency, such as an event or obligation, to the event that gives rise to it."^^xsd:string ;
Confusing. Suggest:
```
skos:definition "Relates something that is contingent on an event happening to that event. ^^xsd:string ;
```

2023-05-09 03:41 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "For obligations, this property describes what must happen to trigger the contingent obligation.  In most cases, before the contingent obligation becomes an actual obligation, the tri
> the triggering event is scheduled to occur in the future

Does not make sense to say the house burning down is a scheduled event, or even a planned event. It's really a specification of a hypothetical event. SKiip all the future stuff and replace with:
```
skos:scopeNote "For obligations, this property describes what must happen to trigger the contingent obligation. Other uses include controls, processes, etc."^^xsd:string ;
skos:example "A contingent obligation such as a fire insurance payout is triggered by one's house burning down."^^xsd:string ;  
```

2023-05-09 03:41 UTC, uscholdm commented on gistCore.ttl
> +	skos:scopeNote "An event does not necessarily have either planned or actual start or end dates. For example, a conference can be in the planning phase without any dates selected, but is nevertheless
This also means that the restrictions on ContingentEvent are wrong.

2023-05-09 13:05 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "An event does not necessarily have either planned or actual start or end dates. For example, a conference can be in the planning phase without any dates selected, but is nevertheless
Agree with the first proposal.

The `ContingentEvent` restrictions have been fixed in another PR: https://github.com/semanticarts/gist/pull/826/.

2023-05-09 13:07 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "An event which, at the time it is created, is to occur in the future. It remains a scheduled event after it has started or ended, but then is also either a historical or contemporar
I like this. Adopted.

2023-05-09 13:10 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "A task that was or is planned to occur at a given time. When it was scheduled, it would have been in the future, but might now be in the past."^^xsd:string ;
I liked your language for `ScheduledEvent` so have adapted it for this term. See what you think.

2023-05-09 13:19 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "For obligations, this property describes what must happen to trigger the contingent obligation.  In most cases, before the contingent obligation becomes an actual obligation, the tri
I agree that this is awkward. I've used the examples for `ContingentEvent`.

2023-05-10 15:36 UTC, dylan-sa requested changes

2023-05-10 15:36 UTC, dylan-sa commented on docs/release_notes/PR777.md
> +  - Renamed `gist:TaskExecution`, `gist:ScheduledTaskExecution`, and `gist:ProjectExecution` and renamed to `gist:Task`, `gist:ScheduledTask`, and `gist:Project`, respectively.
Should the first 'renamed' at the beginning of the sentence be 'removed'? Alternatively, could omit 'and renamed' from the middle of the sentence.

2023-05-10 15:42 UTC, rjyounes commented on docs/release_notes/PR777.md
> +  - Renamed `gist:TaskExecution`, `gist:ScheduledTaskExecution`, and `gist:ProjectExecution` and renamed to `gist:Task`, `gist:ScheduledTask`, and `gist:Project`, respectively.
Yes, thanks for catching that!

2023-05-12 14:49 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "Relates a contingency, such as an event or obligation, to the event that gives rise to it."^^xsd:string ;
I spend a lot of time on a good wording, not easy. Keep it as it is for now, make sure there is a good example, e.g. house burning down triggers insurance payout.

2023-05-15 20:12 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "Not all planned events are scheduled events. For example, a conference can be in an early planning phase without any dates yet selected."^^xsd:string ;
We had `PlannedEvent`, but based on the fact that events are no longer required to have dates, and that, as in the examples, something can be planned but not yet scheduled, we changed it to `ScheduledEvent`. I don't think planned would be the right name for such an event, because  it is too easily confused with scheduled event. We have a [new issue to add `HypotheticalEvent`](https://github.com/semanticarts/gist/issues/831), which is an event that cannot have dates.

2023-05-15 20:19 UTC, merged