Change prefLabel; add skos example and gist domainIncludes to gist:is…
semanticarts/gist pull request #811
Opened 2023-03-29 20:55 UTC by wslooney

…AllocatedBy

2023-03-29 21:26 UTC, dylan-sa approved these changes
One suggestion for the `domainIncludes` statement, but looks good even if you decide against it. Can add 'Fixes #n' to the title to ensure automated closing of the issue.

2023-03-29 21:26 UTC, dylan-sa commented on gistCore.ttl
> +	gist:domainIncludes gist:ID ;
Worth adding `gist:Category` here? Seems similar to`gist:ID`--another gist term that has `isAllocatedBy` in its formal def.

2023-03-30 14:13 UTC, rjyounes requested changes

2023-03-30 14:13 UTC, rjyounes commented on gistCore.ttl
> +	gist:domainIncludes gist:ID ;
Dylan's suggestion makes sense to me.

For the ID example, let's think of something more specific, else it's not much of an example. E.g., a student ID, an SSN, etc. An example for Category would also be good. In this case it's allocated by the body governing the taxonomy.

2023-04-26 13:05 UTC, dylan-sa requested changes
@wslooney - Just noticed we need a release note for this one too, following our new process of creating a separate release note file for each PR.

2023-05-08 19:43 UTC, rjyounes requested changes

2023-05-08 19:43 UTC, rjyounes commented on gistCore.ttl
> +skos:scopeNote
@DanielHadad  These are Protege artifacts that need to be removed from the file before commit.

2023-05-08 19:43 UTC, rjyounes commented on docs/release_notes/pr811.md
> +* Updated `gist:isAllocatedBy`, as per issue [#530](https://github.com/semanticarts/gist/issues/530).
I don't think these items are worth calling out separately. You could say, "Broadened definition of `gist:isAllocatedBy` to include entities other than IDs, and updated other annotations."

2023-05-08 19:43 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "A U.S. Social Security number is allocated by the U.S. Social Security Administration. The gist:MediaType 'CVS' is allocated by the gist Development Team."^^xsd:string ;
The csv example isn't good because, as you can see from the namespaces, these are IANA terms, which we have simply assigned a type `gist:MediaType`. How about  "The media type https://www.iana.org/assignments/media-types/text/csv" is allocated by the Internet Assigned Numbers Authority (IANA)."?

2023-05-09 13:29 UTC, rjyounes approved these changes

2023-05-09 15:13 UTC, merged