Remove inverses. Fixes #506.
semanticarts/gist pull request #813
Opened 2023-03-30 18:41 UTC by dylan-sa

Fixes #506.

This PR includes changes related to the removal of inverse properties from gist:

- All inverses removed. (Inverse working group has proposed which directions to keep in gist.)
- Relevant class axioms have been tweaked to include only the properties that will remain in gist. A common change was to switch out a property restriction with its inverse. For example:
```
a owl:Restriction ;
owl:onProperty gist:hasMember ;
owl:someValuesFrom gist:Category ;
```

becomes

```
a owl:Restriction ;
owl:onProperty [ owl:inverseOf gist:isMemberOf ] ;
owl:someValuesFrom gist:Category ;
```
- `hasSuperCategory` has been changed to `isSubCategoryOf`. Likewise, `hasUniqueSuperCategory` becomes `isUniqueSubCategoryOf` and `hasDirectSuperCategory` becomes `isDirectSubCategoryOf`.

Breakdown:

| Property Kept     | Inverse Property Removed 
| ----------- | ----------- | 
gist:isGeographicallyContainedIn | gist:containsGeographically
gist:occupiesGeographically | gist:isGeographicallyOccupiedBy
gist:occupiesGeographicallyPermanently | gist:isGeographicallyPermanentlyOccupiedBy
gist:isBasedOn | gist:isBasisFor
gist:precedes | gist:follows
gist:precedesDirectly | gist:followsDirectly
gist:isAbout | gist:isDescribedIn
gist:affects | gist:isAffectedBy
gist:governs | gist:isGovernedBy
gist:isRecognizedBy | gist:recognizes
gist:isIdentifiedBy | gist:identifies
gist:hasNavigationalParent | gist:hasNavigationalChild
gist:isDirectPartOf | gist:hasDirectPart
gist:isDirectSubTaskOf | gist:hasDirectSubTask
gist:isMemberOf | gist:hasMember
gist:isPartOf | gist:hasPart
gist:isSubCategoryOf  (new) | gist:hasSubCategory and gist:hasSuperCategory
gist:isSubTaskOf | gist:hasSubTask

2023-04-03 21:15 UTC, rjyounes commented
@marksem  @uscholdm @dylan-sa  On further thought, `describes` is the proper inverse of `isDescribedBy`; `isAbout` means something a bit different. Consider: the anatomy of my foot is described by _Gray's Anatomy_. We can say that the book _describes_ the bone structure of my foot, but not that it is _about_ my foot. One solution is to replace `isDescribedBy` with `describes` (for brevity) and keep `isAbout` as well.

2023-04-04 01:25 UTC, uscholdm commented
> @marksem @uscholdm @dylan-sa On further thought, `describes` is the proper inverse of `isDescribedBy`; `isAbout` means something a bit different. Consider: the anatomy of my foot is described by _Gray's Anatomy_. We can say that the book _describes_ the bone structure of my foot, but not that it is _about_ my foot. One solution is to replace `isDescribedBy` with `describes` (for brevity) and keep `isAbout` as well.

This is a vaid distinction, but let's treat that as a separate issue "Do we add a gist:descibes property". If there was a demonstrated need for both, maybe.  But I'd need some convincing. Is about seems fine for most purposes.

2023-04-04 12:09 UTC, rjyounes commented
@uscholdm

> This is a valid distinction, but let's treat that as a separate issue "Do we add a gist:descibes property". 

Normally I like to keep these issues atomic, but this one is different. If they are not true inverses, and we remove one of them, we are removing a concept that is no longer expressible in gist. The short-term solution is to keep both and remove the inverse axiom.

2023-04-04 12:12 UTC, uscholdm commented
> we are removing a concept that is no longer expressible in gist

I do not that is what is happening. We are removing a property whose only meaning ever was to be the inverse of isAbout. It was poorly named.

2023-04-04 12:13 UTC, rjyounes commented
> I do not that is what is happening. We are removing a property whose only meaning ever was to be the inverse of isAbout. It was poorly named.

OK, valid point. I withdraw my proposal.

2023-04-04 12:47 UTC, rjyounes requested changes
It looks like the serializer has not run on these commits. @dylan-sa You should check your setup. Did you run `tools/setup.cmd` after you pulled the latest from develop?

2023-04-04 13:36 UTC, dylan-sa commented
> It looks like the serializer has not run on these commits. @dylan-sa You should check your setup. Did you run `tools/setup.cmd` after you pulled the latest from develop?

You're right--this wasn't set up correctly. Fixed with latest commit.

2023-04-04 13:42 UTC, dylan-sa commented
> It would be super nice for this table to be alpha sorted so one can look things up.

Good idea--I have tweaked the ordering. 👍

2023-04-04 14:19 UTC, dylan-sa commented
> I looked at the spreadsheet posted by Dylan on 3/28/2023 and I'm unclear on what the column names really mean (the Group Consensus column contradicts the Recommend Keeping column).

Sorry for confusion on the spreadsheet--Group Consensus indicates what the working group settled on keeping, whereas Recommend Keeping is from an earlier version of the spreadsheet. The table at the top of the PR is a better source for the working group proposal.

2023-04-04 14:32 UTC, rjyounes commented
@Jamie-SA We brought other considerations to bear on the decision. In this case, due to the verbosity of isGovernedBy, we opted for governs. It's more a matter of balancing criteria than having hard-and-fast rules. In this particular case I could personally go either way.

2023-04-07 19:39 UTC, dylan-sa commented
@rjyounes @Jamie-SA @hmoore-sa - After some more adjustments, this one is ready for review. Would appreciate everyone's thoughts when you get a chance to look.

2023-04-14 18:49 UTC, rjyounes approved these changes
Good work - it looks like you caught everything.

2023-04-26 19:24 UTC, rjyounes commented
I can get on board with @Jamie-SA's proposal. Looking at our numbers analysis, `containsGeographically` is used on one restriction in gistCore.ttl, `isGeographicallyContainedIn` in none, so it's a wash. I think in this case we opted for the simpler name, but I agree with Jamie that the cardinality consideration in this particular case should trump that.

2023-04-26 21:25 UTC, hmoore-sa approved these changes
Hi Dylan, everything checks out against the sheet, everything is fully formed, and looks like you caught everything.
I'm also aligned with Jamie's recommendation, but since everything is fully formed and could ship now, I'm approving. Happy to review again if you make his change. Great work!

2023-04-27 03:06 UTC, uscholdm commented
> While looking at this I see that the choice was made to keep `containsGeographically` and remove `isGeographicallyContainedIn`. I would like to suggest a couple of reasons why the opposite choice might makes sense.

 `containsGeographically` means the same thing as hasPart between georegions and may be short lived. For now, we don't want have `isGeographicallyContainedIn` which means `isPartOf`. So Im in favor of having it as it is for now.
 THere was a special reason for `occupiesGeographically` going the other way, I do not recall.

2023-04-27 03:08 UTC, uscholdm commented
> > While looking at this I see that the choice was made to keep `containsGeographically` and remove `isGeographicallyContainedIn`. I would like to suggest a couple of reasons why the opposite choice might makes sense.
> 
> `containsGeographically` means the same thing as hasPart between georegions and may be short lived because it is not adding anything much. In any event, we don't want to have `isGeographicallyContainedIn` which means `isPartOf`. So Im in favor of having it as it is for now. THere was a special reason for `occupiesGeographically` going the other way, I do not recall.

2023-04-27 16:42 UTC, Jamie-SA approved these changes
Approved, but with comments.

2023-04-27 16:42 UTC, Jamie-SA commented on gistCore.ttl
> -	a owl:ObjectProperty ;
I don't see the removal of `hasDirectSubCategory` in the table in the issue or PR discussions. It's removal should be documented.

2023-04-27 20:23 UTC, uscholdm commented on docs/release_notes/pr813.md
> +  - For each pair of inverses, the property deemed clearest, simplest, and/or most useful was retained.
> Wondering if this should list the removed properties? Yes, there is a link to the issue, but if someone just scans the release notes it might be nice for them to be here.

Yes, I strongly agree

2023-04-27 22:13 UTC, rjyounes commented on docs/release_notes/pr813.md
> +  - For each pair of inverses, the property deemed clearest, simplest, and/or most useful was retained.
Agreed.

2023-04-27 22:14 UTC, rjyounes requested changes
Just follow Jamie's suggestion of adding the list to the release note. Then it's good to go.

2023-04-27 23:12 UTC, dylan-sa commented
I can get behind Jamie's suggestion to go with `isGeographicallyContainedIn`.  

Michael does make a fair point that it's similar in meaning to `isPartOf`, which we are dropping; but relating regions using the smaller-to-larger direction has proved useful for regions hierarchies.

2023-04-28 01:40 UTC, uscholdm commented
> I can get behind Jamie's suggestion to go with `isGeographicallyContainedIn`.
> 
> Michael does make a fair point that it's similar in meaning to `isPartOf`, which we are dropping; but relating regions using the smaller-to-larger direction has proved useful for regions hierarchies.

I think we should get consensus before making yet another flip/flop.

M.

2023-04-28 15:27 UTC, rjyounes commented
I agree. I’d like to reconvene our small group. It’s important to get these right so we don’t regret it later. Is that OK with everyone?

From: Michael Uschold ***@***.***>
Date: Thursday, April 27, 2023 at 9:40 PM
To: semanticarts/gist ***@***.***>
Cc: Rebecca Younes ***@***.***>, Mention ***@***.***>
Subject: Re: [semanticarts/gist] Remove inverses. Fixes #506. (PR #813)

I can get behind Jamie's suggestion to go with isGeographicallyContainedIn.

Michael does make a fair point that it's similar in meaning to isPartOf, which we are dropping; but relating regions using the smaller-to-larger direction has proved useful for regions hierarchies.

I think we should get consensus before making yet another flip/flop.

M.

—
Reply to this email directly, view it on GitHub<https://github.com/semanticarts/gist/pull/813#issuecomment-1526859401>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAM5PZGRSHKWGGJVAQL5SQDXDMNXVANCNFSM6AAAAAAWNVYA5Q>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-01 19:48 UTC, dylan-sa commented
Decision after 5/1 working group meeting is to go w/ `isGeographicallyContainedIn` over `containsGeographically`, for reasons Jamie has described. I've pushed a commit to make the switch. If I could get one last look at the latest commit from @hmoore-sa , @Jamie-SA, or @rjyounes, I believe this one is ready to go.

2023-05-01 21:54 UTC, hmoore-sa commented
Hi Dylan, Took a look, mostly focusing on the isGeographicallyContainedIn changes, and looks like you got everything as far as I can see. Continuing to be signed off!

2023-05-02 19:59 UTC, rjyounes approved these changes

2023-05-03 19:33 UTC, merged