Remove TimeZone & etc. Fixes #650
semanticarts/gist pull request #815
Opened 2023-04-13 16:50 UTC by Jamie-SA

See #650

Removes
- gist:TimeZone
- gist:TimeZoneStandard
- gist:hasOffsetToUniversal
- gist:usesTimeZoneStandard

2023-04-14 14:36 UTC, dylan-sa requested changes
Just a couple minor things on the release notes; otherwise looking good to me.

2023-04-14 14:36 UTC, dylan-sa commented on docs/release_notes/issue650.md
> +Addresses issue #650.
Could add the link here. https://github.com/semanticarts/gist/issues/650

2023-04-14 18:44 UTC, rjyounes requested changes

2023-04-14 18:44 UTC, rjyounes commented on docs/release_notes/issue650.md
> +Addresses issue #650.
I would like to see some descriptive text here, as we typically do with our release notes. For example:  

- Renamed `gist:Task`, `gist:ScheduledTask` and `gist:Project` to `gist:TaskExecution`, `gist:ScheduledTaskExecution` and  `gist:ProjectExecution`, respectively. Issue [#590](https://github.com/semanticarts/gist/issues/590).

This includes the link and backticks that Dylan has suggested.

2023-04-14 18:44 UTC, rjyounes commented on gistCore.ttl
> +Time zone offset, such as -6:00 (of which there are a few dozen) is recognized in the date itself, as shown. The actual time zone standard (of which there are 131) may optionally be attached to the e
I would like to get rid of the second sentence about time zone standard, since we couldn't agree yesterday about what a time zone standard is. Since we deleted the property the comment isn't very relevant anyway - I.e., we are not providing a way to attach the standard to the event.

2023-04-17 14:31 UTC, Jamie-SA commented on docs/release_notes/issue650.md
> +Addresses issue #650.
@rjyounes I'm not sure what more information you would like to see. Your example shows saying those things were renamed. Below I've already said what things were removed. I think what I have is similar to your example.

2023-04-18 11:52 UTC, rjyounes requested changes
One requested change, otherwise looks good.

2023-04-18 11:52 UTC, rjyounes commented on gistCore.ttl
> +A time zone offset, such as -6:00, can be included as part of the datetime itself, as shown. The offset is not the same as a time zone. There are roughly a few dozen time zone offsets and around 130
> If needed, a time zone may be recorded by attaching it to the event or other object.

Since we are removing the classes, this should also be removed.

2023-04-18 16:17 UTC, rjyounes approved these changes

2023-04-18 16:23 UTC, rjyounes commented
@dylan-sa Can you review Jamie's changes in response to your review comments, and approve it or submit a new request for changes? This is close to being ready to merge to develop.

2023-04-18 17:02 UTC, dylan-sa approved these changes
Looks good.

2023-04-18 17:05 UTC, merged