Modify setup script to make pre-commit hooks executable (needed on Mac). Fixes #823
semanticarts/gist pull request #824
Opened 2023-04-24 14:54 UTC by rjyounes

Fixes #823.

2023-04-26 04:06 UTC, Jamie-SA requested changes

2023-04-26 04:06 UTC, Jamie-SA commented on .github/workflows/validate.yaml
> +          pip install --upgrade pip
This has a merge conflict. Probably best to remove the change in the validate.yaml file, and leave the changes that I made in the logo PR.
```suggestion
```

2023-05-03 16:09 UTC, Jamie-SA commented on tools/pre-commit
> -
General good practice is that files should end with a newline.

2023-05-04 18:34 UTC, Jamie-SA approved these changes

2023-05-04 19:49 UTC, Jamie-SA commented
@rjyounes is there a reason this PR is marked as a draft? I think it is ready to merge.

2023-05-04 21:19 UTC, rjyounes commented
I had some trouble with it and put it in draft state. I'll have another look at it.

2023-05-08 19:54 UTC, merged