Feature/issue 776 intergovernmental treaty
semanticarts/gist pull request #825
Opened 2023-04-25 22:10 UTC by hmoore-sa

Hi Rebecca, Dylan, 

This is a small PR that deprecates the TreatyOrganization class in favor of IntergovernmentalOrganization, adjusts the definition and example of the latter, and makes a pref-label fix to remove a '-'. It also adds the relevant information to the release notes.

Let me know if you don't have time and I can switch reviewers. Aiming for the end of the month.

Thanks,
Heather

2023-04-26 13:21 UTC, dylan-sa requested changes
Just a couple comments on the release note and deprecation file. Otherwise looking good to me.

2023-04-26 13:21 UTC, dylan-sa commented on docs/ReleaseNotes.md
> +- Deprecated `gist:TreatyOrganization` in favor of its parent `gist:IntergovernmentalOrganization` and updated definitions and labels. Issues [#766](https://github.com/semanticarts/gist/issues/766) a
For the release note, we should create a separate file containing just the changes related to this PR. Check out what Michael did here, for example: https://github.com/semanticarts/gist/pull/784.

Can go ahead and delete this line from `ReleaseNotes.md`.

2023-04-26 13:21 UTC, dylan-sa commented on gistDeprecated.ttl
Now that the next release will be major and won't contain a deprecation file, no need to add.

2023-04-26 15:41 UTC, rjyounes requested changes
Everything looks good except the items Dylan flagged. I'll approve once these are fixed.

2023-04-26 15:41 UTC, rjyounes commented on docs/ReleaseNotes.md
> +- Deprecated `gist:TreatyOrganization` in favor of its parent `gist:IntergovernmentalOrganization` and updated definitions and labels. Issues [#766](https://github.com/semanticarts/gist/issues/766) a
Agreed. And replace "deprecated" with "removed."

2023-04-26 15:44 UTC, rjyounes requested changes

2023-04-26 15:44 UTC, rjyounes commented on docs/ReleaseNotes.md
> +- Deprecated `gist:TreatyOrganization` in favor of its parent `gist:IntergovernmentalOrganization` and updated definitions and labels. Issues [#766](https://github.com/semanticarts/gist/issues/766) a
I also find the wording "in favor of its parent" a bit strange and would leave it off. This could be broken into two separate items, deprecating one term and fixing the label and definition of the other.

2023-04-27 07:57 UTC, hmoore-sa commented on docs/ReleaseNotes.md
> +- Deprecated `gist:TreatyOrganization` in favor of its parent `gist:IntergovernmentalOrganization` and updated definitions and labels. Issues [#766](https://github.com/semanticarts/gist/issues/766) a
Thank you both. All suggestions followed. I did not realize about the new file method.

2023-04-27 07:59 UTC, hmoore-sa commented on gistDeprecated.ttl
Removed! Thank you, Dylan, and for confiriming that this was -really- ok even though it's in the documentation. :)

2023-04-27 14:52 UTC, rjyounes approved these changes
Looks good!

2023-04-28 00:25 UTC, dylan-sa approved these changes

2023-04-28 16:45 UTC, merged