Bugfix/776 contingent event
semanticarts/gist pull request #826
Opened 2023-04-27 14:51 UTC by coltonglasgow

This PR removed dateTime restrictions from `gist:ContingentEvent` and adds a `skos:example`. 

See the issue here: https://github.com/semanticarts/gist/issues/776

2023-04-27 14:56 UTC, rjyounes requested changes
The gist changes look good. You will need to add a release note. The process has changed from what's in Contributing.md (I'm updating that on another branch): you put the note in a separate file. You'll see how this is done by looking at some of the other PRs. Let me know if you have questions.

2023-05-04 12:13 UTC, rjyounes requested changes
Hi Colton - just a couple modifications needed to the release note and we're good to go.

2023-05-04 12:56 UTC, rjyounes commented
@coltonglasgow I just saw Dave's comment: I think the canonical example and what ought to be in the definition is the event that triggers some indemnity. The death benefit payout on a life insurance policy is the death of a very specific person. Fire insurance is contingent on a particular building burning down.

Please incorporate this into the definition.

2023-05-05 07:22 UTC, coltonglasgow commented on gistCore.ttl
> +		"The death benefit payout on a life insurance policy following the death of a very specific person."^^xsd:string
@rjyounes, I changed `is` to `following` in this example. Let me know if you want me to change it.

2023-05-05 07:22 UTC, coltonglasgow commented on gistCore.ttl
> +		"Sell 20 shares of stock in a given company when the price drops below $200/share."^^xsd:string ,
@rjyounes, I kept this example, I believe it is still relevant.

2023-05-08 19:32 UTC, rjyounes requested changes
Just one more small tweak.

2023-05-08 19:32 UTC, rjyounes requested changes
Just one more small tweak.

2023-05-08 20:35 UTC, rjyounes approved these changes
Yay!

2023-05-08 20:35 UTC, merged