Feature/816 migration scripts
semanticarts/gist pull request #866
Opened 2023-05-26 07:19 UTC by coltonglasgow

2023-05-26 07:22 UTC, coltonglasgow commented on migration/v12.0/migrate_endpoint.yaml
> +        - "detect_old_namespace_graph.rq"
I have been unable to test the validation against an endpoint. I am getting an error back that appears to be from the endpoint, I may have the wrong URL. I have tries several databases with no luck. @Jamie-SA, could you provide me with the endpoint URL for AGraph or GraphDB please.

2023-06-08 18:03 UTC, Jamie-SA requested changes
I noticed a few items and/or questions.

2023-06-08 18:39 UTC, Jamie-SA commented
Colton is out for a couple of weeks so I'm going to work on addressing some of the issues I found during my review.

2023-06-08 19:36 UTC, Jamie-SA approved these changes
I fixed the issues I saw.

2023-06-08 19:37 UTC, merged