removed TreatyOrganization
semanticarts/gist pull request #877
Opened 2023-06-16 23:08 UTC by stevenchalem

Peter found at the last minute that TreatyOrganization was still present in gistCore.ttl. This PR is to remove it consistent with the intention of issue #766 and pr #825

2023-06-16 23:08 UTC, stevenchalem commented
@dylan-sa does this look right?

2023-06-16 23:38 UTC, dylan-sa commented
Getting close to what we need, but looks like Heather's changes to the annotations for `IntergovernmentalOrganization` didn't make it in, either: https://github.com/semanticarts/gist/pull/825/files

If you change the prefLable, definition, and example for `IntergovernmentalOrganization`, I think we'll have what we need.

2023-06-16 23:40 UTC, dylan-sa requested changes
Just need to change the annotations for `IntergovernmentalOrganization`

2023-06-17 22:15 UTC, stevenchalem reviewed
requested changes are complete

2023-06-18 16:48 UTC, dylan-sa commented
I did some more digging here and believe I found the root of the issue.

It looks like one of my [commits](https://github.com/semanticarts/gist/commit/b492805ada640d9169b7be4dbe15344585a036cb) on the inverses branch was not caught up with some of the work that came right before it. (Surprising to me since I had made a point to merge the develop branch into my inverses branch, but it appears that not everything was updated as expected.) So, I've looked to see what exactly got lost, and I believe this is what we need to get caught up:

- [x] Remove `TreatyOrganization` (@stevenchalem has addressed in this PR)
- [x] Update annotations for `IntergovernmentalOrganization` (already addressed in this PR)
- [ ] Remove `TimeZone`, `TimeZoneStandard`, `hasOffsetToUniversal`, and `usesTimeZoneStandard` (per #815)
- [ ] Update annotation on `atDateTime` as done in #815
- [ ] Add `TimeInterval` class as done in #828 

As best I can tell, this would fill in the gaps, but I would appreciate some more eyes on this just to make sure I've got it right. (@stevenchalem @rjyounes @Jamie-SA, if you could please take a look.) If this is looking right, I can make the remaining changes since my branch appears to be the culprit.

2023-06-19 15:22 UTC, Jamie-SA commented
I retract my last statement... do to something I was working on, I was not looking at the correct version of gistCore.ttl.

2023-06-19 15:42 UTC, stevenchalem commented
@dylan-sa I think you've caught everything.

2023-06-19 16:20 UTC, Jamie-SA commented
I submitted PR #879 to re-apply the TimeZone changes. Steven approved, and I merged it.
I have submitted PR #880 to re-apply the lost TimeInterval commit.

2023-06-19 17:05 UTC, merged

2023-06-19 17:06 UTC, Jamie-SA commented
Hopefully everything is fixed now...