Fix pre-commit hook
semanticarts/gist pull request #889
Opened 2023-06-22 20:08 UTC by rjyounes

Fixes #884.

2023-06-22 21:00 UTC, dylan-sa requested changes
The only speed bump I ran into was needing to make `setup.cmd` executable. After that, everything seemed to work as expected. We can commit an executable version, right?

See comments on `gistCore.ttl` and `rdf-toolkit.jar`, too.

2023-06-22 21:18 UTC, rjyounes commented on gistCore.ttl
> +	a owl:Class
Now I'm confused - if the pre-commit hook is working, this shouldn't have been committed. I did see it catching the error, so I'll have to check again.

2023-06-22 21:21 UTC, rjyounes commented on tools/serializer/rdf-toolkit.jar
Apparently I checked in a version that's executable (see 100644 → 100755). It doesn't need to be, so I'll change it back.

2023-06-22 21:21 UTC, rjyounes commented
@Jamie-SA Converting back to draft to address Dylan's comments. Don't review yet.

2023-06-22 21:25 UTC, rjyounes commented
> The only speed bump I ran into was needing to make setup.cmd executable. After that, everything seemed to work as expected. We can commit an executable version, right?

Without the change to the serializer pre-commit hook, the serializer was running but not calling rdf-toolkit. I had to make that change to get it to work. 

It's fine to commit an executable version. But I believe when you check it out it becomes non-executable, at least on Mac, because I've had to make that change multiple times.

2023-06-22 21:28 UTC, rjyounes commented on gistCore.ttl
> +	a owl:Class
Aha, I see what happened: I had committed a test version when the serializer still wasn't working, and forgot to remove it. Then, because the file hadn't changed, the serializer didn't catch it once it did start working. All should be correct now.

2023-06-22 21:29 UTC, rjyounes commented
@Jamie-SA @dylan-sa Undrafted - ready for review.

2023-06-22 21:56 UTC, dylan-sa approved these changes
Seems to be working on my end. The tweak to `tools/serializer/pre-commit` makes sense to me.

2023-06-22 21:56 UTC, dylan-sa commented on tools/serializer/pre-commit
> +  for fileToBeCommitted in $(git diff --cached --name-only) ; do
Ah, I see why `--cached` is necessary--to get files that are staged but not yet committed, right?

2023-06-23 02:07 UTC, Jamie-SA approved these changes

2023-06-23 14:24 UTC, merged