Update gist namespace in subclass generator. Fixes #893.
semanticarts/gist pull request #895
Opened 2023-06-23 17:44 UTC by rjyounes

Fixes #893.

2023-06-27 00:20 UTC, stevenchalem commented
@dylan-sa Please review. Thanks!

2023-06-27 15:08 UTC, dylan-sa requested changes
A couple small adjustments. Otherwise looks good, pending alignment with the work in #896.

2023-06-28 17:23 UTC, dylan-sa approved these changes
Approved w/ one last suggestion on wording

2023-06-28 17:23 UTC, dylan-sa commented on tools/subclass_inferences/materialize_subclass_inferences.py
> +        (SKOS.scopeNote, Literal("This ontology contains supplementary subclass assertions that are logically entailed by gist but are not inferred by some automated reasoners. For example, an OWL RL
One minor suggestion, to avoid a syntactic ambiguity:

```suggestion
        (SKOS.scopeNote, Literal("This ontology contains supplementary subclass assertions that are logically entailed by gist but are not inferred by some automated reasoners. For example, an OWL RL reasoner would not infer that gist:Commitment is a subclass of gist:Intention, even though it follows from the ontology axioms. More precisely, it contains (1) subclass assertions derived using an OWL DL reasoner and (2) the subclass assertions that are already explicit in gistCore.", datatype=XSD.string)),
```

2023-06-28 18:49 UTC, merged