Feature/883 namespace
semanticarts/gist pull request #896
Opened 2023-06-26 16:38 UTC by coltonglasgow

2023-06-26 16:43 UTC, coltonglasgow commented on bundle.yaml
The formatting changes to this and other files are from a formatting extension (prettier) in VSCode. Let me know if these need to reverted and I will recreate the PR.

2023-06-26 17:13 UTC, Jamie-SA commented on docs/Namespace.md
Looks like we might have dueling markdown reformatters. I think I originally formatted this file with the the "#" for titles and, IIRC, Rebecca rewrote it (I assumed due to a formatter) to use the "====" underneath convention.

I personally prefer the use of the "#", "##", "###", etc., format for titles. It is the original, and I think more standard, markdown format, it is more consistent no matter the title "level", and doesn't add extra lines.

I don't know if we have a written style guide about this.

2023-06-26 17:17 UTC, stevenchalem commented on bundle.yaml
I'd like to hear from @Jamie-SA and @rjyounes before you back out anything, but I would prefer not to make formatting changes at the same time as we're making these other changes.

2023-06-26 17:24 UTC, Jamie-SA requested changes
A couple of comments...

2023-06-26 17:24 UTC, Jamie-SA commented on docs/ReleaseNotes.md
> +  - The gist ontology IRIs have changed from `https://ontologies.semanticarts.com/o/<ontology-name>` to `https://w3id.org/semanticarts/<ontology-name>`. For example, `https://ontologies.semanticarts.
```suggestion
  - The gist ontology IRIs have changed from `https://ontologies.semanticarts.com/o/<ontology-name>` to `https://w3id.org/semanticarts/ontology/<ontology-name>`. For example, `https://ontologies.semanticarts.com/o/gistCore` is now `https://w3id.org/semanticarts/ontology/gistCore`.
```

2023-06-26 17:24 UTC, Jamie-SA commented on gistMediaTypes.ttl
>  <https://w3id.org/semanticarts/gistMediaTypes>
This same issue might appear in other non-gistCore ontology files, such as gistPrefixDeclarations.ttl, these should be checked.
```suggestion
<https://w3id.org/semanticarts/ontology/gistMediaTypes>
```

2023-06-26 17:24 UTC, Jamie-SA commented on gistPrefixDeclarations.ttl
This file has a couple of ontology URIs that need to be updated.

2023-06-26 17:24 UTC, Jamie-SA commented on gistSubClassAssertions.ttl
>  <https://w3id.org/semanticarts/gistSubClassAssertions.ttl>
```suggestion
<https://w3id.org/semanticarts/ontology/gistSubClassAssertions.ttl>
```

2023-06-26 17:24 UTC, Jamie-SA commented on gistValidationAnnotations.ttl
>  <https://w3id.org/semanticarts/gistValidationAnnotations>
```suggestion
<https://w3id.org/semanticarts/ontology/gistValidationAnnotations>
```

2023-06-26 17:24 UTC, Jamie-SA commented on gistValidationAnnotations.ttl
> +	owl:imports <https://w3id.org/semanticarts/ontology/gistCore> ;
Not related to this PR, but I think imports should always use a versioned URI. I will add a new issue for this.

2023-06-26 17:25 UTC, stevenchalem commented
There are a lot of real changes that need to be reviewed here. Having formatting changes mixed in makes that more difficult. Can we any formatting changes until after this major release?

Sent from my iPhone

On Jun 26, 2023, at 10:13 AM, Jamie-SA ***@***.***> wrote:

﻿

@Jamie-SA commented on this pull request.

________________________________

On docs/Namespace.md<https://github.com/semanticarts/gist/pull/896#discussion_r1242505017>:

Looks like we might have dueling markdown reformatters. I think I originally formatted this file with the the "#" for titles and, IIRC, Rebecca rewrote it (I assumed due to a formatter) to use the "====" underneath convention.

I personally prefer the use of the "#", "##", "###", etc., format for titles. It is the original, and I think more standard, markdown format, it is more consistent no matter the title "level", and doesn't add extra lines.

I don't know if we have a written style guide about this.

—
Reply to this email directly, view it on GitHub<https://github.com/semanticarts/gist/pull/896#pullrequestreview-1499020058>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO4OODROQZKDLKTVEIOUX2DXNG7LJANCNFSM6AAAAAAZUNKQOQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2023-06-26 17:53 UTC, Jamie-SA commented on bundle.yaml
Generally I prefer to make formatting changes in separate PRs away from code changes as it can make it difficult to see what the important changes were.

In this case, using the github "ignore whitespace" option does ignore all the simple whitespace format changes.

In this specific case, since it has already been done, I don't have a strong opinion about "undoing" the formatting or accepting it.

2023-06-26 18:46 UTC, stevenchalem commented
@coltonglasgow I'm sorry to have to ask you to do this, but please back out the formatting changes. Some of the changes alter long-standing practices and I don't want to make those changes without discussion. Also I'm finding it difficult to review changes across 38 files with the formatting changes mixed in. The github hide-whitespace option hides some of the formatting changes but not all of them.

2023-06-26 18:48 UTC, stevenchalem requested changes
Please revert the formatting changes and re-create the PR. See discussion.

2023-06-26 19:50 UTC, rjyounes commented on docs/Namespace.md
The conventions are self-documenting in `docs/.markdownlint.json`. Please add another issue if you want to discuss it.  I agree with @stevenchalem that this is not the time to make these changes.

2023-06-26 19:52 UTC, rjyounes commented on docs/ReleaseNotes.md
> +  - The gist ontology IRIs have changed from `https://ontologies.semanticarts.com/o/<ontology-name>` to `https://w3id.org/semanticarts/<ontology-name>`. For example, `https://ontologies.semanticarts.
@Jamie-SA is correct.

2023-06-26 19:53 UTC, rjyounes commented on gistSubClassAssertions.ttl
>  <https://w3id.org/semanticarts/gistSubClassAssertions.ttl>
The ontology and namespace IRIs may need to be changed in the script that generates the subclass file: `tools/subclass_inferences/materialize_subclass_inferences.py`.

2023-06-26 19:54 UTC, rjyounes commented on gistValidationAnnotations.ttl
> +	owl:imports <https://w3id.org/semanticarts/ontology/gistCore> ;
Agreed.

2023-06-26 23:05 UTC, coltonglasgow commented on docs/Namespace.md
> +Welcome to the `gist` namespace.
Not sure where this came from... Regardless, I personally like having gist in an inline code block here, makes it bolder to the reader. I can remove if unwanted. Again, unsure where this edit came from.

2023-06-26 23:09 UTC, coltonglasgow commented on gistSubClassAssertions.ttl
>  <https://w3id.org/semanticarts/gistSubClassAssertions.ttl>
The script that updates the subclass file has been updated with the latest ontology and namespace IRIs.

2023-06-26 23:11 UTC, coltonglasgow commented on gistValidationAnnotations.ttl
> +	owl:imports <https://w3id.org/semanticarts/ontology/gistCore> ;
@Jamie-SA or @rjyounes, would one of you please resolve this conversation when the new issue has been created.

2023-06-26 23:12 UTC, coltonglasgow commented
> @coltonglasgow I'm sorry to have to ask you to do this, but please back out the formatting changes. Some of the changes alter long-standing practices and I don't want to make those changes without discussion. Also I'm finding it difficult to review changes across 38 files with the formatting changes mixed in. The github hide-whitespace option hides some of the formatting changes but not all of them.

No worries! The formatting has been reverted and the conversations have been resolved. Ready for review. 
FYI @stevenchalem @rjyounes @Jamie-SA

2023-06-26 23:13 UTC, coltonglasgow commented on docs/Namespace.md
@Jamie-SA @rjyounes, please resolve this conversation when the new issue has been created.

2023-06-26 23:14 UTC, coltonglasgow commented on bundle.yaml
Formatting has been removed from this PR. Only ontology and namespace URIs have been updated.

2023-06-26 23:50 UTC, stevenchalem approved these changes

2023-06-27 04:46 UTC, Jamie-SA commented on docs/Namespace.md
> The conventions are self-documenting in docs/.markdownlint.json

I wouldn't call this self-documenting :)
> "MD013": false,

I have added a new issue so I will mark this as resolved.

2023-06-27 04:53 UTC, Jamie-SA requested changes
I think I found one more change.

2023-06-27 04:53 UTC, Jamie-SA commented on docs/ReleaseNotes.md
> +  - The gist namespace has changed from `https://ontologies.semanticarts.com/gist` to `https://w3id.org/semanticarts/ontology/gist`.
```suggestion
  - The gist namespace has changed from `https://ontologies.semanticarts.com/gist` to `https://w3id.org/semanticarts/ns/ontology/gist/`.
```

2023-06-27 05:09 UTC, stevenchalem commented on docs/ReleaseNotes.md
> +  - The gist namespace has changed from `https://ontologies.semanticarts.com/gist` to `https://w3id.org/semanticarts/ontology/gist`.
Good catch, Jamie!

2023-06-27 15:50 UTC, Jamie-SA approved these changes

2023-06-28 12:31 UTC, rjyounes approved these changes

2023-06-28 12:31 UTC, rjyounes commented on docs/Namespace.md
> +Welcome to the `gist` namespace.
OK for me as long as we're consistent throughout the file.

2023-06-28 12:31 UTC, rjyounes commented on docs/Namespace.md
> +Welcome to the `gist` namespace.
Just checked - that's the only occurrence.

2023-06-28 12:31 UTC, rjyounes commented on docs/ReleaseNotes.md
>  - - Documentation updates. Issues [#567](https://github.com/semanticarts/gist/issues/567), [#576](https://github.com/semanticarts/gist/issues/576), [#734](https://github.com/semanticarts/gist/issues/
Extra "-". I've created a sub-branch to fix this, will issue a PR when it's completed.

2023-06-28 12:31 UTC, rjyounes commented on docs/ReleaseNotes.md
>  - - Documentation updates. Issues [#567](https://github.com/semanticarts/gist/issues/567), [#576](https://github.com/semanticarts/gist/issues/576), [#734](https://github.com/semanticarts/gist/issues/
PR merged.

2023-06-28 12:31 UTC, merged