Bundle.yaml updates. Fixes #922
semanticarts/gist pull request #930
Opened 2023-07-25 21:18 UTC by rjyounes

Fixes #922.

Two changes:
* gistValidationAnnotations.ttl is not included in download package
* rdfsAnnotations files have versioned filenames

I've tested these on my end. Please run the bundler and test for both of these changes.

2023-07-25 22:22 UTC, dylan-sa requested changes
Minor wording tweak to release note, but otherwise looking good to me.

2023-07-25 22:22 UTC, dylan-sa commented on docs/release_notes/issue-922-bundler
> +  - Renamed `rdfsAnnotations` to `gistRdfsAnnotations` and add version number to the filenames.
```suggestion
  - Renamed `rdfsAnnotations` to `gistRdfsAnnotations` and added version number to the filenames.
```

2023-07-25 23:22 UTC, stevenchalem approved these changes
This worked fine for me.

2023-07-26 15:00 UTC, dylan-sa approved these changes

2023-07-26 15:01 UTC, merged