Removed properties related to occupying a location.
semanticarts/gist pull request #941
Opened 2023-07-27 18:26 UTC by uscholdm

- Removed properties related to occupying a location. Issue [#809](https://github.com/semanticarts/gist/issues/809). Changes:
  - Removed properties: `gist:occupiesGeographically` and `gist:occupiesGeographicallyPermanently`.
  - Updated restriction on `gist:Landmark` due to property being removed.
  - Updated annotations for `gist:hasPhysicalLocation` regarding location temporality.

This will impact inference, so is strictly speaking, a major update. In practice, it is unlikely to affect anyone.

2023-07-28 14:32 UTC, rjyounes requested changes
Sorry about this, I forgot the current protocol for deprecation. I'm going to update the issue with the new implementation decision.

2023-07-28 14:32 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "This property does not distinguish between things whose locations vary over different time periods. E.g. a fire hydrant vs. a car."^^xsd:string ;
```suggestion
	skos:scopeNote "This property does not distinguish between things whose locations are relatively stable and those that vary over different time periods; e.g., a fire hydrant vs. a car. Use a temporal relation if you need to explicitly model a time-delimited location."^^xsd:string ;
```

The first sentence is a grammar adjustment. The second sentence is added content which you may or may not agree with - I don't have strong feelings so don't mind if you drop it.

2023-07-28 14:32 UTC, rjyounes commented on gistCore.ttl
> -gist:occupiesGeographically
I apologize for not thinking through this when we discussed the implementation. We have a new strategy for deprecation: https://github.com/semanticarts/gist/blob/develop/docs/DeprecationAndDeletionPolicy.md. The upshot is:
1. Rather than deleting the terms, we mark them as `owl:deprecated true` but keep them in the gistCore file (no gistDeprecated.ttl).
2. The restrictions stay the same for now in order to maintain backward compatibility. 
3. On the next major release, we will delete the terms and adjust the restriction.

2023-07-28 14:32 UTC, rjyounes commented on docs/release_notes/Issue-809-occupiesGeographically.md
> +- Removed properties related to occupying a location. Issue [#809](https://github.com/semanticarts/gist/issues/809). Changes:
```suggestion
- Deprecated properties related to occupying a location. Issue [#809](https://github.com/semanticarts/gist/issues/809). Changes:
```

2023-07-28 14:32 UTC, rjyounes commented on docs/release_notes/Issue-809-occupiesGeographically.md
> +  - Updated restriction on `gist:Landmark` due to property being removed.
```suggestion

```

2023-07-29 13:52 UTC, dylan-sa reviewed
I just had one clarification question on the new deprecation policy. Otherwise looking good to me!

2023-07-29 13:52 UTC, dylan-sa commented on gistCore.ttl
> +	skos:editorialNote "On the next major release gist:occupiesGeographicallyPermanently will be gone. The restriction above will use gist:hasPhysicalLocation. Use subClassOf instead of equivalentClass.
I'm refreshing my memory on the new deprecation policy. One part of the policy is:

> If the term slated for removal is referenced by other term definitions, as in a domain axiom or property restriction, such that a change to that reference constitutes a major change, the term cannot be deprecated in a minor release. The change or removal must wait until the next major release, when the references to it can be appropriately modified or removed.

In this case, the term slated for removal (`occupiesGeographicallyPermanently`) is used in a property restriction. If we were to use `hasPhysicalLocation` in the restriction instead, would that rise to the level of a major change, meaning that `occupiesGeographicallyPermanently` should not be deprecated in a minor release? Am I interpreting this part of the policy correctly? @rjyounes

2023-08-07 21:22 UTC, rjyounes commented
I'm inclined to hold hard to the line that any change in inferencing outcomes constitutes a major change; otherwise, the criteria are too subjective. In software development, one would not say "Yeah, changing this method name breaks backward compatibility, but no one uses the method anyway, so let's call it a minor change." I recommend closing this PR and tagging the issue as "deferred to major release." Let's bring this up at a meeting because it's a significant issue that should be resolved as a group.

2023-08-07 21:38 UTC, rjyounes commented on gistCore.ttl
> +	skos:editorialNote "On the next major release gist:occupiesGeographicallyPermanently will be gone. The restriction above will use gist:hasPhysicalLocation. Use subClassOf instead of equivalentClass.
Now I'm not sure I correctly captured our intent in the documentation. I think we might have said that we can deprecate the term, but not change the restrictions or other references. @marksem Do you recall?

2023-08-10 15:15 UTC, rjyounes commented
MarkW: Policy should be to deprecate (with OWL annotation) but keep any references as is.

Given this policy, the PR should not represent a major change. Michael will check.

Rebecca: check documentation.

2023-08-16 12:32 UTC, rjyounes requested changes

2023-08-16 12:32 UTC, rjyounes commented on docs/release_notes/Issue-809-occupiesGeographically.md
> +  - Added editorialNote on `gist:Landmark` to update the restriction on the next major release.
```suggestion

```
This doesn't need to be in the release note.

2023-08-16 12:32 UTC, rjyounes commented on gistCore.ttl
> +	skos:editorialNote "On the next major release gist:occupiesGeographicallyPermanently will be gone. The restriction above will use gist:hasPhysicalLocation. Use subClassOf instead of equivalentClass.
```suggestion
	skos:editorialNote "See guidance on removing the term in the next major release at https://github.com/semanticarts/gist/issues/947#issuecomment-1679566885."^^xsd:string ;
```

This is the format we agreed on for the editorial notes. It goes without saying, according to our deprecation policy, that it will be removed on the next release, and I don't think the ontology should be littered with such comments, nor the documentation of exactly what changes will be made.

2023-08-16 19:47 UTC, uscholdm commented
> @uscholdm Please remember to add "Fixes #nnn" to the description of the PR so that when the PR is merged, the issue is automatically closed. This also helps readers easily find the issue.

Done

2023-08-16 21:25 UTC, rjyounes approved these changes

2023-08-16 21:25 UTC, merged