897 owl imports
semanticarts/gist pull request #976
Opened 2023-09-22 19:54 UTC by uscholdm

Fixes #897

2023-09-26 12:07 UTC, sa-bpelakh approved these changes
👍

2023-10-11 12:03 UTC, rjyounes requested changes
I recommend a wording tweak in the release note.

2023-10-11 12:03 UTC, rjyounes commented on docs/release_notes/897-owl-imports.md
> +- In `gistPrefixDeclarations`, `gistSubClassAssertions`, and `gistValidationAnnotationsUpdated`, the statements importing gist now import a versioned IRI. Also, they all have versioned IRIs of their
```suggestion
- Changed gist import in `gistPrefixDeclarations`, `gistSubClassAssertions`, and `gistValidationAnnotations` to use a versioned IRI, and add version IRIs of their own. Issue [#897](https://github.com/semanticarts/gist/issues/897).
```

2023-10-12 12:05 UTC, rjyounes approved these changes

2023-10-12 12:05 UTC, merged