Implement versioning ontology per issue 979
semanticarts/gist pull request #982
Opened 2023-10-12 18:45 UTC by rjyounes

Fixes #979.

2023-10-12 18:47 UTC, rjyounes commented
Putting into draft state - forgot to check documentation for necessary updates.

2023-10-12 19:48 UTC, rjyounes commented
This can't be finalized until #983 is complete, since the versioning and ops files can't be downloaded so the checks fail.

2023-10-13 01:06 UTC, uscholdm requested changes
Looks good, one wording suggestion.

2023-10-13 13:18 UTC, rjyounes commented on docs/release_notes/issue979-versioning
> +  * Add version dependency range to the versioning ontology.
Done.

2023-10-13 13:21 UTC, rjyounes commented
Keeping in draft state until:
* Issue #989 has been merged.
* `bundle.yaml` runs versioning validation queries.
  * The queries should be put into a sub-module, but can do that later.

2023-10-13 13:58 UTC, rjyounes commented
@sa-bpelakh @uscholdm Do you think it's necessary to state the version and dependencies in the ancillary ontologies as well as gistCore? It looks like a bit of overkill, and these ontologies are always versioned with gist and would likely not have dependencies different from gist's. On the other hand, for absolute correctness I suppose they are needed.

2023-10-18 08:57 UTC, pmcb55 commented
I'm just curious really - but in reference to '_absolute correctness_' around dependencies, dependency ranges, and the like, did you folks look into [PLOW](https://ebooks.iospress.nl/pdf/doi/10.3233/SSW220015)? (As indeed, I think 'absolute correctness' is definitely a most worthy goal, as dependency issues have a very nasty habit of getting convoluted/unwieldy/nightmarish pretty quickly once out in the 'real-world'.)

2024-02-14 20:35 UTC, rjyounes commented
Moved to 12.2.0

2024-04-25 16:09 UTC, rjyounes commented
@sa-bpelakh: @uscholdm has raised the point that you should make sure this implementation doesn't clash with the new units and magnitudes model (shouldn't, because there is no dependency on gist, but worth checking).

2024-09-10 19:19 UTC, uscholdm commented
> This can't be finalized until #983 is complete, since the versioning and ops files can't be downloaded so the checks fail.

@rjyounes This now works.

2024-09-10 19:21 UTC, uscholdm commented
> Keeping in draft state until:
> 
> * Issue [Issue 372 text datatype properties #989](https://github.com/semanticarts/gist/pull/989) has been merged.

@rjyounes This has now been merged.

2025-08-04 15:12 UTC, rjyounes commented
We now need to consider whether we want to adopt this approach to ontology versioning or @Jamie-SA's proposal. @Jamie-SA, if you could post your slides here it would be interesting to get external feedback. This proposal does not entail any changes to gist, since gist doesn't import any other ontologies, but would obviate the need to add a version definition in terms of the versioning ontology.

2025-10-24 20:47 UTC, closed without merging

2025-10-24 20:47 UTC, rjyounes commented
No action here for over a year. Closing.