Updated definition of hasMember
semanticarts/gist pull request #990
Opened 2023-10-26 00:31 UTC by uscholdm

Updated definition of hasMember

2023-10-26 15:17 UTC, rjyounes commented on docs/release_notes/439-hasMember-definition.md
> +- Updated definition of hasMember
```suggestion
- Updated definition of `gist:hasMember` 
```

2023-10-26 15:18 UTC, rjyounes commented on gistCore.ttl
>  	gist:domainIncludes gist:Collection ;
```suggestion
	gist:domainIncludes gist:Collection , gist:Organization
```

2023-10-27 13:07 UTC, rjyounes requested changes

2023-10-27 13:07 UTC, rjyounes commented on docs/release_notes/439-hasMember-definition.md
> +- Updated definition of hasMember
```suggestion
- Updated definition of `gist:hasMember`. 
```

2023-10-29 14:38 UTC, rjyounes requested changes
Change looks good, just a question about the release note.

2023-10-29 14:38 UTC, rjyounes commented on docs/release_notes/439-hasMember-definition.md
> +- Updated definition of `gist:hasMember`.
```suggestion
- Updated definition of `gist:hasMember`. Issue [#439](https://github.com/semanticarts/gist/issues/439). 
```

Similar comment to the one I made on PR #995.

2023-10-30 13:55 UTC, uscholdm reviewed
Made recommended changes.

2023-11-07 22:50 UTC, rjyounes approved these changes

2023-11-07 22:51 UTC, merged