Update gist:Category skos:definition in gistCore.ttl
semanticarts/gist pull request #994
Opened 2023-10-26 19:18 UTC by irinafilitovich

2023-10-27 13:06 UTC, rjyounes requested changes
You will also need to add a release note. See https://github.com/semanticarts/gist/blob/develop/docs/Contributing.md#release-notes.

2023-10-27 13:06 UTC, rjyounes commented on gistCore.ttl
>  	skos:scopeNote "Often a 'bucket' can be modeled either as an owl:Class or as a gist:Category. Use the latter if you don't care much about the formal structure of the different types, or if there is
```suggestion
	skos:scopeNote "Often a type can be modeled either as an owl:Class or as a gist:Category. Use the latter if you don't care much about the formal structure of the different types, or if there is a whole hierarchy of types that are going to be managed by a group separate from the ontology developers. The formal structure may be defined elsewhere and linked to, if necessary."^^xsd:string ;
```

2023-10-27 14:23 UTC, uscholdm commented on gistCore.ttl
> +	skos:definition "A concept or label used to categorize other instances without formal semantics. Things that can be thought of as types are usually Categories."^^xsd:string ;
I agree with @rjyounes's suggested rewording, albeit with one possible exception. How about .
- "without specifying any formal semantics"
rather than
- "without conferring any formal semantics"

2023-10-27 14:24 UTC, uscholdm approved these changes
One minor suggestion use 'specifying' rather than 'conferring'.

2023-10-27 14:34 UTC, uscholdm commented
> You will also need to add a release note. See https://github.com/semanticarts/gist/blob/develop/docs/Contributing.md#release-notes.

Oops yes, I should not have approved w/o requesting this change.

2023-10-27 18:46 UTC, irinafilitovich commented
@rjyounes, @uscholdm, I made changes according to suggestions and added release notes, PR is ready for the review.

2023-10-29 14:36 UTC, rjyounes approved these changes

2023-10-29 14:36 UTC, merged