Updated annotations for gist:Transaction
semanticarts/gist pull request #995
Opened 2023-10-27 19:11 UTC by uscholdm

Fixes #521

2023-10-29 14:35 UTC, rjyounes requested changes

2023-10-29 14:35 UTC, rjyounes commented on docs/release_notes/521-definition-of-transaction.md
> +- Updated definition of `gist:Transaction`
```suggestion
- Updated definition of `gist:Transaction`. Issue [#521](https://github.com/semanticarts/gist/issues/521). 
```

The way you have this makes it look like there are multiple changes associated with the issue. Or are you proposing a new format for release notes?

2023-10-30 13:51 UTC, uscholdm reviewed
Recommended change made.

2023-11-07 22:50 UTC, rjyounes approved these changes
Approved.

2023-11-07 22:50 UTC, merged