531 extend symbol predicates
semanticarts/gist pull request #997
Opened 2023-10-29 20:21 UTC by uscholdm

Fixes #531 .
- Deprecated predicates: `gist:unitSymbol`, `gist:unitSymbolHtml` and `gist:unitSymbolUnicode`. 
- Added predicates: `gist:symbol`, `gist:symbolHtml` and `gist:symbolUnicode`.
- Added symbol triples for existing units, anticipating the removeal of `gist:UnitSymbol`.

2023-10-29 21:57 UTC, rjyounes requested changes
I've suggested what I think are more precise definitions; they could still use more work. We should also settle on whether to put letters and symbols in single quotes or not in the annotations, and apply this consistently.

2023-10-29 21:57 UTC, rjyounes commented on docs/release_notes/531-extend-symbol-predicates.md
> +- Added symmbol triples for existing units, anticipating the removeal of `gist:UnitSymbol`.
```suggestion
- Added symbol triples for existing units, anticipating the removal of `gist:unitSymbol`.
```

2023-10-29 21:57 UTC, rjyounes commented on docs/release_notes/531-extend-symbol-predicates.md
> +- Deprecated `gist:unitSymbol`, `gist:unitSymbolHtml` and `gist:unitSymbolUnicode`. Issue [#531](https://github.com/semanticarts/gist/issues/531).
Since these are all one issue and a set of interrelated changes, there should be one primary bullet point and sub-bullets.

2023-10-29 21:57 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "A symbol for something in HTML format for pretty printing, may use special characters."^^xsd:string ;
```suggestion
	skos:definition "A symbol in HTML format for displaying on a web page; may use HTML-encoded characters."^^xsd:string ;
```

2023-10-29 21:57 UTC, rjyounes commented on gistCore.ttl
> +	gist:intendedDomain gist:UnitOfMeasure ;
```suggestion
	gist:domainIncludes gist:UnitOfMeasure ;
```

2023-10-29 21:57 UTC, rjyounes commented on gistCore.ttl
> +	skos:scopeNote "This is for when Unicode not supported and the display will be HTML format."^^xsd:string ;
```suggestion
	skos:example "For square meter, the letter m with the HTML representation of superscript 2 rather than the ASCII version m^2; i.e., 'm&sup2;'"^^xsd:string ;
	skos:prefLabel "symbol HTML"^^xsd:string ;
	skos:scopeNote "Use when Unicode is not supported and the display will be in HTML."^^xsd:string ;
```

2023-10-29 21:57 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "E.g. to show square meter as the letter m with superscript 2 rather than m^2, the value of this property would be the unicode symbol for 'm' followed by the unicode symbol for 'supersc
```suggestion
	skos:definition "The Unicode symbol for something."^^xsd:string ;
	skos:example "For square meter (ASCII 'm^2', the Unicode symbol for 'm' followed by the Unicode symbol for superscript 2, i.e., 'U+006D U+00B2'"^^xsd:string ;
```

2023-10-29 21:57 UTC, rjyounes commented on gistCore.ttl
> +	skos:definition "A symbol for something NOT using any special characters."^^xsd:string ;
```suggestion
	skos:definition "A symbol for something using only ASCII characters."^^xsd:string ;
```

2023-10-29 21:57 UTC, rjyounes commented on gistCore.ttl
>  	skos:definition "Used for folksonomy style categories (non controlled vocabulary)"^^xsd:string ;
```suggestion
	skos:definition "Used for folksonomy categories (non-controlled vocabularies)"^^xsd:string ;
```

2023-10-29 21:57 UTC, rjyounes commented on gistCore.ttl
> +	skos:example "The symbol for square meter is m^2."^^xsd:string ;
```suggestion
	skos:example "The ASCII symbol for square meter is m^2."^^xsd:string ;
```

2023-10-30 13:46 UTC, uscholdm commented on docs/release_notes/531-extend-symbol-predicates.md
> +- Deprecated `gist:unitSymbol`, `gist:unitSymbolHtml` and `gist:unitSymbolUnicode`. Issue [#531](https://github.com/semanticarts/gist/issues/531).
Good idea.

2023-10-30 13:46 UTC, uscholdm reviewed
Recommended changes made.

2023-10-30 14:57 UTC, uscholdm commented
There is a failed check that I cannot track down.  I looked in the ontologyShapes.ttl and property_type_construct.rq files and found no message text that matched.  The property, `symbolUnicode` is very much like `symbol` and `symbolHtml`.. Could it be tripping over the Unicode symbols? That's the only thing that seems different enough to cause a problem. 

![image](https://github.com/semanticarts/gist/assets/10777545/11b3a9c5-4cbf-4b8d-b977-0f2792517c23)

2023-10-30 15:16 UTC, rjyounes requested changes
I noticed that the `rdfs:domain` assertions didn't get removed from the new predicates.

2023-10-30 15:16 UTC, rjyounes commented on gistCore.ttl
> +	rdfs:domain gist:UnitOfMeasure ;
```suggestion
```

2023-10-30 15:16 UTC, rjyounes commented on gistCore.ttl
> +	rdfs:domain gist:UnitOfMeasure ;
```suggestion

```

2023-10-30 15:16 UTC, rjyounes commented on gistCore.ttl
> +	rdfs:domain gist:UnitOfMeasure ;
```suggestion

```

2023-10-30 15:17 UTC, rjyounes commented
@uscholdm The new symbol predicates don't conform to this shape:

```
gshapes:PropertyShape
	a sh:NodeShape ;
	skos:prefLabel "Property Shape"^^xsd:string ;
	sh:or (
		gshapes:LowerCase
		gshapes:NonConformingLabel
	) ;
	sh:property gshapes:MandatoryDefinition ;
	sh:targetClass
		owl:AnnotationProperty ,
		owl:DatatypeProperty ,
		owl:ObjectProperty
		;
	.
```

You should put these into gistValidationAnnotations.ttl file - you'll see an example there.

BTW, I also noticed that the `rdfs:domain` assertions haven't yet been removed from the new predicates.

2023-10-30 16:41 UTC, uscholdm commented
> The new symbol predicates don't conform to this shape:
```
gshapes:PropertyShape
	a sh:NodeShape ;
	skos:prefLabel "Property Shape"^^xsd:string ;
	sh:or (
		gshapes:LowerCase
		gshapes:NonConformingLabel
	) ;
	sh:property gshapes:MandatoryDefinition ;
	sh:targetClass
		owl:AnnotationProperty ,
		owl:DatatypeProperty ,
		owl:ObjectProperty
		;
	.
```

The property mentioned in the error message as being invalid is:
```
gist:symbolUnicode
	a owl:DatatypeProperty ;
	rdfs:range xsd:string ;
	skos:definition "The Unicode symbol for something."^^xsd:string ;
	skos:example "For square meter (ASCII 'm^2'), the Unicode symbol for 'm' followed by the Unicode symbol for superscript 2, i.e., 'U+006D U+00B2'"^^xsd:string ;
	skos:prefLabel "symbol Unicode"^^xsd:string ;
	gist:domainIncludes gist:UnitOfMeasure ;
	.
```

The label is not non-conforming. I tested it against the regex for `gshapes:LowerCase` at [Regex101](https://regex101.com/https://regex101.com/). So, the `sh:or` clause is obeyed.  There is also a `skos:definition`, so `gshapes:MandatoryDefinition` is obeyed. I am still not seeing the problem. 

![image](https://github.com/semanticarts/gist/assets/10777545/9c7fd209-0864-479c-90ca-62c6858a83db)

2023-10-30 17:48 UTC, rjyounes commented
The regex in the` gshapes:LowerCase` constraint is:

`^([a-z]+|[A-Z][A-Z]+)([- ]([a-z]+|[A-Z][A-Z]+|[0-9]+))*$`

[a-z]+| - 1 or more lowercase letters or
[A-Z][A-Z]+ - 1 or more uppercase letters (I.e., an acronym like UNRWA)

([- ]([a-z]+|[A-Z][A-Z]+|[0-9]+))*$ = 
0 or more of: (space or hyphen plus (1 or more lowercase letters or 1 or more uppercase letters or one or more digits)) end-of-string

"symbol Unicode" doesn't conform. "symbol HTML" does conform.

2023-10-31 01:58 UTC, uscholdm commented
Thanks for that explanation. I misread the regex. Is the regex really what we want? Why rule out capitalized words, they are not that unusual.

2023-11-07 22:56 UTC, rjyounes approved these changes

2023-11-07 22:57 UTC, rjyounes commented
@uscholdm The PR has been approved but has conflicts with `develop` that must be resolved before merging.

2023-11-08 14:08 UTC, merged